#+TITLE: Automatic tools for cleaning up music downloads
#+FILETAGS: @project:@music
* Development directory is [[file:~/Dev/music-cleaner/][here]]
* Technologies
  - python
  - mutagen for tag editing
  - image manipulation with 
    - PIL
    - ImageMagick
* Reference
** Album Art
   - Linux.com :: Album Cover Art Downloader makes iPod a touch nicer
     http://www.linux.com/archive/feature/125125
   - Album Cover Art Downloader
     http://www.unrealvoodoo.org/hiteck/projects/albumart/
   - Download Album Cover Art in Linux with Coverfinder - Associated
     Content - associatedcontent.com
     http://www.associatedcontent.com/article/378348/download_album_cover_art_in_linux_with.html?cat=15
   - Learning to love GeekTool - A primer (Part 1) - Page 2 - MacTalk Forums
     http://forums.mactalk.com.au/18/51020-learning-love-geektool-primer-part-1-a-2.html
   - Using Amazon Web Services
     - Getting album art using Amazon Web Services « Exploding Pixels
       http://explodingpixels.wordpress.com/2008/06/24/getting-album-art-using-amazon-web-services/
     - boto - Project Hosting on Google Code
       http://code.google.com/p/boto/
     - boto Documentation — boto v1.9 (r1423)
       http://boto.s3.amazonaws.com/index.html
     - Amazon Web Services Developer Community : Amazon EC2 Library
       for Query in Python
       http://developer.amazonwebservices.com/connect/entry!default.jspa?categoryID=85&externalID=552&fromSearchPage=true
   - Album Cover Art Downloader
     http://www.unrealvoodoo.org/hiteck/projects/albumart/
   - Print Page - Write cover / album art images to MP3s - Mac Python
     script / Win EXE now avail
     http://forums.sabnzbd.org/index.php?action=printpage;topic=1190.0
   - Discogs API Documentation
     http://www.discogs.com/help/api
*** Using AWS
    - Getting album art using Amazon Web Services « Exploding Pixels
      http://explodingpixels.wordpress.com/2008/06/24/getting-album-art-using-ama$
    - boto
      - boto - Project Hosting on Google Code
        http://code.google.com/p/boto/
      - boto's boto at master - GitHub
        http://github.com/boto/boto
      - boto: A Python interface to Amazon Web Services — boto v2.0 (rHEAD)
        http://boto.cloudhackers.com/
    - PyAWS - A Python wrapper for Amazon Web Service
      http://pyaws.sourceforge.net/
    - Write cover / album art images to MP3s - Mac Python script / Win EXE
      now avail
      http://forums.sabnzbd.org/index.php?topic=1190.75
    - Amazon Web Services Developer Community : Getting Started with AWS
      and Python
      http://developer.amazonwebservices.com/connect/entry.jspa?categoryID=55&ext$
    - Rich Burridge's Blog : Weblog
      http://blogs.sun.com/richb/entry/updated_be_informed_when_used
    - Hack 79 Program AWS with Python / Amazon Hacks
      http://www.freeopenbook.com/amazon-hacks/amazonhks-chp-6-sect-13.html
      - pyamazon
        http://www.josephson.org/projects/pyamazon/
* Ui Ideas
  - To pick cover art, build a jpg with all the candidates and label
    them with a number. At the same time, ask for the number at the
    command line.
* Converting as needed
  I don't keep FLAC or other lossless files around. So they would be
  automagically converted to AAC. Of course, metadata must be copied
  over.
  - Maybe script [[http://sbooth.org/Max/][Max]] to do this. Some leads [[http://forums.sbooth.org/viewtopic.php%3Ff%3D2&t%3D1655&start%3D0][here]].
* Verify tagging and add album art
** Tasks to perform for each album
   - Verify that all tagging info is present and accurate
     - Manual / visual inspection by a human is acceptable, but data
       should be presented correctly.
     - Tag data to verify:
       - Artist name
       - Album name
       - Track name
       - Track number
       - Year
       - Genre
       - Total tracks
       - Album art
       - Compilation status (different artists on the same album)
     - Verify file name:
       - Non-compilation:
         track number - track name.ext
       - Compilation:
         track number - artist name - track name.ext
   - Get album art from a variety of sources
     - Discogs
     - Amazon
     - Album Art
* Sort loose files into directories
* Merge new albums into current collection
  - Current collection
