#+TITLE: Automatic tools for cleaning up music downloads
#+FILETAGS: @project:@music
* Development directory is [[file:~/Dev/music-cleaner/][here]]
* Technologies
  - python
  - mutagen for tag editing
  - image manipulation with 
    - PIL
    - ImageMagick
* Reference
** Album Art
   - Linux.com :: Album Cover Art Downloader makes iPod a touch nicer
     http://www.linux.com/archive/feature/125125
   - Album Cover Art Downloader
     http://www.unrealvoodoo.org/hiteck/projects/albumart/
   - Download Album Cover Art in Linux with Coverfinder - Associated
     Content - associatedcontent.com
     http://www.associatedcontent.com/article/378348/download_album_cover_art_in_linux_with.html?cat=15
   - Learning to love GeekTool - A primer (Part 1) - Page 2 - MacTalk Forums
     http://forums.mactalk.com.au/18/51020-learning-love-geektool-primer-part-1-a-2.html
   - Using Amazon Web Services
     - Getting album art using Amazon Web Services « Exploding Pixels
       http://explodingpixels.wordpress.com/2008/06/24/getting-album-art-using-amazon-web-services/
     - boto - Project Hosting on Google Code
       http://code.google.com/p/boto/
     - boto Documentation — boto v1.9 (r1423)
       http://boto.s3.amazonaws.com/index.html
     - Amazon Web Services Developer Community : Amazon EC2 Library
       for Query in Python
       http://developer.amazonwebservices.com/connect/entry!default.jspa?categoryID=85&externalID=552&fromSearchPage=true
   - Album Cover Art Downloader
     http://www.unrealvoodoo.org/hiteck/projects/albumart/
   - Print Page - Write cover / album art images to MP3s - Mac Python
     script / Win EXE now avail
     http://forums.sabnzbd.org/index.php?action=printpage;topic=1190.0
   - Discogs API Documentation
     http://www.discogs.com/help/api
   - amazon web services cover art - Google Search
     http://www.google.ca/search?client=safari&rls=en&q=amazon+web+services+cover+art&ie=UTF-8&oe=UTF-8&redir_esc=&ei=Lo_NTNL-HYf9nAeOn90c
   - Getting album art using Amazon Web Services « Exploding Pixels
     http://explodingpixels.wordpress.com/2008/06/24/getting-album-art-using-amazon-web-services/
   - python aws boto album art - Google Search
     http://www.google.ca/search?hl=en&client=safari&rls=en&q=python+aws+boto+album+art&aq=f&aqi=&aql=&oq=&gs_rfai=
   - boto - Project Hosting on Google Code
     http://code.google.com/p/boto/
   - boto's boto at master - GitHub
     http://github.com/boto/boto
   - boto: A Python interface to Amazon Web Services — boto v2.0 (rHEAD)
     http://boto.cloudhackers.com/
   - Getting Started with AWS and Python : Articles & Tutorials : Amazon Web Services
     http://aws.amazon.com/articles/3998
   - Rich Burridge's Blog : Weblog
     http://blogs.sun.com/richb/entry/updated_be_informed_when_used
   - Hack 79 Program AWS with Python / Amazon Hacks
     http://www.freeopenbook.com/amazon-hacks/amazonhks-chp-6-sect-13.html
   - No Open Blockers: Getting Started with Amazon EC2 using Python
     http://noopenblockers.com/2010/04/27/getting-started-with-amazon-ec2-using-python/
   - dive into mark » Projects
     http://diveintomark.org/projects/#pyamazon
   - SABnzbd script - write cover / album art images to MP3s
     http://kins.net/wordpress/2008/09/27/sabnzbd-script-write-cover-album-art-images-to-mp3s/
   - Hands-on Tutorial for Getting Started with Amazon SimpleDB | Packt Publishing Technical & IT Book Store
     http://www.packtpub.com/article/hands-on-tutorial-for-getting-started-with-amazon-simpledb
   - API Documentation
     http://www.discogs.com/help/api
   - python discogs api - Google Search
     http://www.google.ca/search?client=safari&rls=en&q=python+discogs+api&ie=UTF-8&oe=UTF-8&redir_esc=&ei=d4_NTI2uCoOnnAfGqYnFDw
   - API / python discogs class example
     http://www.discogs.com/help/forums/topic/173819
   - pylywi - Project Hosting on Google Code
     http://code.google.com/p/pylywi/
   - http://pylywi.googlecode.com/svn-history/r5/trunk/lybot/Discogs.py
     http://pylywi.googlecode.com/svn-history/r5/trunk/lybot/Discogs.py

*** Using AWS
    - Getting album art using Amazon Web Services « Exploding Pixels
      http://explodingpixels.wordpress.com/2008/06/24/getting-album-art-using-ama$
    - boto
      - boto - Project Hosting on Google Code
        http://code.google.com/p/boto/
      - boto's boto at master - GitHub
        http://github.com/boto/boto
      - boto: A Python interface to Amazon Web Services — boto v2.0 (rHEAD)
        http://boto.cloudhackers.com/
    - PyAWS - A Python wrapper for Amazon Web Service
      http://pyaws.sourceforge.net/
    - Write cover / album art images to MP3s - Mac Python script / Win EXE
      now avail
      http://forums.sabnzbd.org/index.php?topic=1190.75
    - Amazon Web Services Developer Community : Getting Started with AWS
      and Python
      http://developer.amazonwebservices.com/connect/entry.jspa?categoryID=55&ext$
    - Rich Burridge's Blog : Weblog
      http://blogs.sun.com/richb/entry/updated_be_informed_when_used
    - Hack 79 Program AWS with Python / Amazon Hacks
      http://www.freeopenbook.com/amazon-hacks/amazonhks-chp-6-sect-13.html
      - pyamazon
        http://www.josephson.org/projects/pyamazon/

*** Using Google images
    - Python Library for Google Search - good coders code, great reuse
      http://www.catonmat.net/blog/python-library-for-google-search/
    - Google Image Results
      http://www.mit.edu/~kimo/blog/google_image.html
    - Black Code SEO » Blog Archive » Google Image Search in Python
      http://blackcodeseo.com/google-image-search-in-python/
    - Beautiful Soup: We called him Tortoise because he taught us.
      http://www.crummy.com/software/BeautifulSoup/

*** Updating in files
    - How do you embed album art into an MP3 using Python? - Stack Overflow
      http://stackoverflow.com/questions/409949/how-do-you-embed-album-art-into-an-mp3-using-python
    - Source Checkout - pyalbumart - An album art grabber written in python. - Google Project Hosting
      http://code.google.com/p/pyalbumart/source/checkout

* Ui Ideas
  - To pick cover art, build a jpg with all the candidates and label
    them with a number. At the same time, ask for the number at the
    command line.
* Converting as needed
  I don't keep FLAC or other lossless files around. So they would be
  automagically converted to AAC. Of course, metadata must be copied
  over.
  - Maybe script [[http://sbooth.org/Max/][Max]] to do this. Some leads [[http://forums.sbooth.org/viewtopic.php%3Ff%3D2&t%3D1655&start%3D0][here]].
* Verify tagging and add album art
** Tasks to perform for each album
   - Verify that all tagging info is present and accurate
     - Manual / visual inspection by a human is acceptable, but data
       should be presented correctly.
     - Tag data to verify:
       - Artist name
       - Album name
       - Track name
       - Track number
       - Year
       - Genre
       - Total tracks
       - Album art
       - Compilation status (different artists on the same album)
     - Verify file name:
       - Non-compilation:
         track number - track name.ext
       - Compilation:
         track number - artist name - track name.ext
   - Get album art from a variety of sources
     - Discogs
     - Amazon
     - Album Art
* Sort loose files into directories
* Merge new albums into current collection
  - Current collection
