#+TITLE: Read a Twitter timeline through an RSS feed
#+DESCRIPTION: Use the twitter API to write the timeline (or lists) to an RSS feed, to be picked up by rss2email.
#+FILETAGS: @project:@twitter:@rss:@twit2rss

* Design
** [2012-01-17 Tue] Revisit as a cgi script
   - Run simply via http request (instead of writing an xml feed file
     that has to be served).
   - Keep the most recent tweet served as a preference and continue
     from there.
** [2012-01-27 Fri] Revisit as a simple executable
   - Just spit out the xml for the RSS feed to stdout.
   - Mod rss2email to accept executables as well as http[s]
     links. Added the "exec:" URL. Still a hack, but it's localized
     and works.
*** TODO publish rss2email hack on BitBucket

* Ideas
** TODO [#A] Deference links.
   : curl --silent --head <link> | grep Location:
   gives
   : Location: <link>
   if there's a redirect, and nothing if there is not (final link).

* Links
** [2012-01-17 Tue]
   - WebOb — WSGI request and response objects
     http://www.webob.org/
   - JSON-RPC Example — WebOb 1.2b2 documentation
     http://docs.webob.org/en/latest/jsonrpc-example.html
   - Ian Bicking: a blog :: What Does A WebOb App Look Like?
     http://blog.ianbicking.org/2010/03/12/a-webob-app-example/
   - Deploy Python Code with WSGI using uWSGI and nginx on Ubuntu 10.10 (Maverick) – Linode Library
     http://library.linode.com/web-servers/nginx/python-uwsgi/ubuntu-10.10-maverick
   - Deploying circuits.web with Nginx/uwsgi » KBeezie
     http://kbeezie.com/view/circuits-nginx-uwsgi/

** [2011-11-20 Sun]
   - tweepy/tweepy - GitHub
     https://github.com/tweepy/tweepy
   - sclm/tweepy-examples - GitHub
     https://github.com/sclm/tweepy-examples
   - » Streaming Tweets With Tweepy » John Hobbs on coding, Omaha, and life in general » Blog Archive
     http://www.velvetcache.org/2010/07/05/streaming-tweets-with-tweepy
   - GET lists/statuses | Twitter Developers
     https://dev.twitter.com/docs/api/1/get/lists/statuses
