#+TITLE: My book list
#+DESCRIPTION: My personal book list.
#+LAST_MOBILE_CHANGE: 2012-01-18 11:27:36
#+FILETAGS: :@books:
#+TODO: READING(!) TOREAD TOBUY | READ(@) ABANDONED(@)

* Hints
** C-u C-c C-t to change state.
** Thumbnails
*** In books subdirectory
*** Resize using =mogrify -resize x100=
*** Insert using =file://books/<imagefile>

* READING Abaddon's Gate - James S.A. Corey
  :LOGBOOK:
  - State "READING"    from "TOBUY"      [2014-03-27 Thu 10:28]
  :END:
  file://books/james-sa-corey-abaddons-gate.jpg
  
  For generations, the solar system -- Mars, the Moon, the Asteroid
  Belt -- was humanity's great frontier. Until now. The alien artifact
  working through its program under the clouds of Venus has appeared
  in Uranus's orbit, where it has built a massive gate that leads to a
  starless dark.

  Jim Holden and the crew of the Rocinante are part of a vast flotilla
  of scientific and military ships going out to examine the
  artifact. But behind the scenes, a complex plot is unfolding, with
  the destruction of Holden at its core. As the emissaries of the
  human race try to find whether the gate is an opportunity or a
  threat, the greatest danger is the one they brought with them.

* READ Caliban's War - James S.A. Corey
  :LOGBOOK:
  - State "READ"       from "READING"     [2014-03-26 Wed 10:27]
  - State "READING"    from "TOBUY"      [2014-01-27 Mon 10:33]
  :END:
  books/james-sa-corey-calibans-war.jpg

  We are not alone.

  On Ganymede, breadbasket of the outer planets, a Martian marine
  watches as her platoon is slaughtered by a monstrous
  supersoldier. On Earth, a high-level politician struggles to prevent
  interplanetary war from reigniting. And on Venus, an alien
  protomolecule has overrun the planet, wreaking massive, mysterious
  changes and threatening to spread out into the solar system.

  In the vast wilderness of space, James Holden and the crew of the
  Rocinante have been keeping the peace for the Outer Planets
  Alliance. When they agree to help a scientist search war-torn
  Ganymede for a missing child, the future of humanity rests on
  whether a single ship can prevent an alien invasion that may have
  already begun...

* READ Leviathan Wakes - James S.A. Corey
  :LOGBOOK:
  - State "READ"       from "READING"    [2014-01-27 Mon 10:32]
  - State "READING"    from ""           [2014-01-27 Mon 10:26]
  :END:
  books/james-sa-corey-leviathan-wakes.jpg

  Humanity has colonized the solar system - Mars, the Moon, the
  Asteroid Belt and beyond - but the stars are still out of our reach.

  Jim Holden is XO of an ice miner making runs from the rings of
  Saturn to the mining stations of the Belt. When he and his crew
  stumble upon a derelict ship, The Scopuli, they find themselves in
  possession of a secret they never wanted. A secret that someone is
  willing to kill for - and kill on a scale unfathomable to Jim and
  his crew. War is brewing in the system unless he can find out who
  left the ship and why.

  Detective Miller is looking for a girl. One girl in a system of
  billions, but her parents have money and money talks. When the trail
  leads him to The Scopuli and rebel sympathizer Holden, he realizes
  that this girl may be the key to everything.

  Holden and Miller must thread the needle between the Earth
  government, the Outer Planet revolutionaries, and secretive
  corporations - and the odds are against them. But out in the Belt,
  the rules are different, and one small ship can change the fate of
  the universe.

* READ The Last Oracle - James Rollins
  :LOGBOOK:
  - State "READ"       from "READING"      [2014-01-27 Mon 10:25]
  - State "READING" from "" [2013-10-23 Wed 07:56]
  :END: 
  file://books/james-rollins-the-last-oracle.jpg

  In Washington, D.C., a homeless man takes an assassin's bullet and
  dies in Commander Gray Pierce's arms. A bloody coin clutched in the
  dead man's hand--an ancient relic that can be traced back to the
  Greek Oracle of Delphi--is the key to a conspiracy that dates back
  to the Cold War and threatens the very foundation of humanity. For
  what if it were possible to bioengineer the next great prophet--a
  new Buddha, Muhammad, or even Jesus? Would this Second Coming be a
  boon . . . or would it initiate a chain reaction that would result
  in the extinction of humankind?

  Vital seconds are ticking rapidly away as Pierce races across the
  globe in search of answers, one step ahead of ruthless killers
  determined to reclaim the priceless artifact. Suddenly the future of
  all things is balanced on the brink between heaven and hell--and
  salvation or destruction rests in the hands of remarkable children.

* READ Rule 34 - Charles Stross
  :LOGBOOK:
  - State "READ"       from "READING"    [2013-10-23 Wed 07:56]
  - State "READING" from "" [2013-10-03 Thu 17:15]
  :END:
  file://books/charles-stross-rule-34.jpg

  Meet Edinburgh Detective Inspector Liz Kavanaugh, head of the
  Innovative Crimes Investigation Unit, otherwise known as the Rule 34
  Squad. They monitor the Internet for potential criminal activity,
  analyzing trends in the extreme fringes of explicit content. And
  occasionally, even more disturbing patterns arise… Three ex-cons
  have been murdered in Germany, Italy, and Scotland. The only things
  they had in common were arrests for spamming—and a taste for
  unorthodox entertainment. As the first officer on the scene of the
  most recent death, Liz finds herself sucked into an international
  investigation that isn’t so much asking who the killer is, but
  what—and if she doesn't find the answer soon, the homicides could go
  viral.

* READ The Girl Who Kicked the Hornet's Nest - Stieg Larsson
  :LOGBOOK: - State "READING" from "TOREAD" [2013-09-12 Thu 19:07] -
    State "READ" from "READING" [2013-10-03 Thu 17:13] :END:
  file:books/stieg-larsson-the-girl-who-kicked-the-hornets-nest.jpg

  In the concluding volume of Stieg Larsson’s Millennium trilogy,
  Lisbeth Salander lies in critical condition in a Swedish hospital, a
  bullet in her head.
 
  But she’s fighting for her life in more ways than one: if and when
  she recovers, she’ll stand trial for three murders. With the help of
  Mikael Blomkvist, she’ll need to identify those in authority who
  have allowed the vulnerable, like herself, to suffer abuse and
  violence. And, on her own, she’ll seek revenge—against the man who
  tried to kill her and against the corrupt government institutions
  that nearly destroyed her life.

* READ The Girl Who Played with Fire - Stieg Larsson
  :LOGBOOK:
  - State "READ"       from "READING"    [2013-09-12 Thu 19:06]
  - State "READING"    from "TOREAD"     [2013-08-22 Thu 11:56]
  :END:
  file://books/stieg-larsson-the-girl-who-played-with-fire.jpg

  Mikael Blomkvist, crusading publisher of the magazine Millennium,
  has decided to run a story that will expose an extensive sex
  trafficking operation. On the eve of its publication, the two
  reporters responsible for the article are murdered, and the
  fingerprints found on the murder weapon belong to his friend, the
  troubled genius hacker Lisbeth Salander. Blomkvist, convinced of
  Salander’s innocence, plunges into an investigation. Meanwhile,
  Salander herself is drawn into a murderous game of cat and mouse,
  which forces her to face her dark past.

* READ The Girl With the Dragon Tattoo - Stieg Larsson
  :LOGBOOK:
  - State "READ"       from "READING"    [2013-08-22 Thu 11:52]
  - State "READING"    from "TOREAD"      [2013-08-01 Thu 11:51]
  :END:
  file://books/stieg-larsson-the-girl-with-the-dragon-tattoo.jpg

  Harriet Vanger, a scion of one of Sweden's wealthiest families
  disappeared over forty years ago. All these years later, her aged
  uncle continues to seek the truth. He hires Mikael Blomkvist, a
  crusading journalist recently trapped by a libel conviction, to
  investigate. He is aided by the pierced and tattooed punk prodigy
  Lisbeth Salander. Together they tap into a vein of unfathomable
  iniquity and astonishing corruption.

* READ The Judas Strain - James Rollins
  :LOGBOOK:
  - State "READ"       from "READING"    [2013-08-01 Thu 11:46]
  - State "READING"    from ""     [2013-07-25 Thu 12:05]
  :END:
  file://books/james-rollins-the-judas-strain.jpg

  From the depths of the Indian Ocean, a horrific plague has arisen to
  devastate humankind--a disease that's unknown, unstoppable . . . and
  deadly. But it is merely a harbinger of the doom that is to
  follow. Aboard a cruise liner transformed into a makeshift hospital,
  Dr. Lisa Cummings and Monk Kokkalis--operatives of SIGMA
  Force--search for answers to the bizarre affliction. But there are
  others with far less altruistic intentions. In a savage and sudden
  coup, terrorists hijack the vessel, turning a mercy ship into a
  floating bio-weapons lab.

  A world away, SIGMA's Commander Gray Pierce thwarts the murderous
  schemes of a beautiful would-be killer who holds the first clue to
  the discovery of a possible cure. Pierce joins forces with the woman
  who wanted him dead, and together they embark upon an astonishing
  quest following the trail of the most fabled explorer in history:
  Marco Polo. But time is an enemy as a worldwide pandemic grows
  rapidly out of control. As a relentless madman dogs their every
  step, Gray and his unlikely ally are being pulled into an
  astonishing mystery buried deep in antiquity and in humanity's
  genetic code. And as the seconds tick closer to doomsday, Gray
  Pierce will realize he can truly trust no one, for any one of them
  could be . . . a Judas.

* READ Triggers - Robert J. Sawyer
  :LOGBOOK:
  - State "READ"       from "READING"      [2013-07-24 Wed 08:09]
  - State "READING"    from ""           [2013-06-14 Fri 13:29]
  :END:
  file://books/robert-j-sawyer-triggers.jpg

  On the eve of a secret military operation, an assassin's bullet
  strikes President Seth Jerrison. He is rushed to the hospital, where
  surgeons struggle to save his life.

  At the same hospital, researcher Dr. Ranjip Singh is experimenting
  with a device that can erase traumatic memories.

  Then a terrorist bomb detonates. In the operating room, the
  president suffers cardiac arrest. He has a near-death experience-but
  the memories that flash through Jerrison's mind are not his
  memories.

  It quickly becomes clear that the electromagnetic pulse generated by
  the bomb amplified and scrambled Dr. Singh's equipment, allowing a
  random group of people to access one another's minds.

  And now one of those people has access to the president's memories-
  including classified information regarding the upcoming military
  mission, which, if revealed, could cost countless lives. But the
  task of determining who has switched memories with whom is a
  daunting one- particularly when some of the people involved have
  reason to lie...

* READ Robocalypse - Daniel H. Wilson
  :LOGBOOK:
  - State "READ" from "READING" [2013-06-12 Wed 14:22] -
  - State "READING" from "" [2013-04-24 Wed 12:40]
 :END:
  file://books/daniel-h-wilson-robopocalypse-a-novel.jpg 

  Not far into our future, the dazzling technology that runs our world
  turns against us. Controlled by a childlike—yet massively
  powerful—artificial intelligence known as Archos, the global network
  of machines on which our world has grown dependent suddenly becomes
  an implacable, deadly foe. At Zero Hour—the moment the robots
  attack—the human race is almost annihilated, but as its scattered
  remnants regroup, humanity for the first time unites in a determined
  effort to fight back. This is the oral history of that conflict,
  told by an international cast of survivors who experienced this long
  and bloody confrontation with the machines. Brilliantly conceived
  and amazingly detailed, Robopocalypse is an action-packed epic with
  chilling implications about the real technology that surrounds us.

* READ Map of Bones - James Rollins
  :LOGBOOK:
  - State "READ"       from "TOBUY"      [2013-02-19 Tue 13:38] \\
    good yarn if a bit too corny in the romance stuff
  - State "READING" from "TOBUY" [2012-11-19 Mon 14:37]
  :END:
  file://books/james-rollins-map-of-bones.jpg

  During a crowded service at a cathedral in Germany, armed intruders
  in monks' robes unleash a nightmare of blood and destruction. But
  the killers have not come for gold; they seek a more valuable prize:
  the bones of the Magi who once paid homage to a newborn savior ... a
  treasure that could reshape the world.

* READ Wonder - Robert J. Sawyer
  :LOGBOOK:
  - State "READ" from "READING" [2012-11-19 Mon 14:35] \\ Good
    conclusion to the trilogy
  - State "READING" from "TOBUY" [2012-11-19 Mon 14:35]
  :END:
  file://books/robert-j-sawyer-www-wonder.jpg

  Webmind-the vast consciousness that spontaneously emerged from the
  infrastructure of the World Wide Web-has proven its worth to
  humanity by aiding in everything from curing cancer to easing
  international tensions. But the brass at the Pentagon see Webmind as
  a threat that needs to be eliminated.  Caitlin Decter-the once-blind
  sixteen-year-old math genius who discovered, and bonded with,
  Webmind-wants desperately to protect her friend. And if she doesn't
  act, everything-Webmind included-may come crashing down.

* READ Halting State - Charles Stross
  :LOGBOOK:
  - State "READ" from "TOBUY" [2012-11-19 Mon 14:33]
  - State "READING" from "TOREAD" [2012-07-19 Thu 13:00]
  :END:
  :PROPERTIES:
  :ID:       cab2fcaf-4b40-48de-aae4-597af50cb0a0
  :END:
  file://books/charles-stross-halting-state.jpg 

  In the year 2018, Sergeant Sue Smith of the Edinburgh constabulary
  is called in on a special case. A daring bank robbery has taken
  place at Hayek Associates, a dot-com startup company that's just
  been floated on the London stock exchange. The suspects are a band
  of marauding orcs, with a dragon in tow for fire support, and the
  bank is located within the virtual reality land of Avalon Four. For
  Smith, the investigation seems pointless. But she soon realizes that
  the virtual world may have a devastating effect in the real one-and
  that someone is about to launch an attack upon both...

* TOREAD Glasshouse - Charles Stross
  :PROPERTIES: :ID: eb347302-cfd1-4dfc-a7b8-90a8e1f30d77 :END:
  file://books/charles-stross-glasshouse.jpg
* TOBUY vN - Madeleine Ashby
  :PROPERTIES: :ID: 9c926e57-6367-404c-8960-54672e905792 :END:
* TOBUY Les maisons nature de Pierre Thibault au Quebec
  :PROPERTIES: :ID: 51d44390-27f4-4094-a0ab-0b35cdea010c :END:
  [2010-04-21 Wed 21:42]
* TOBUY Book: big book of Apple hacks
  :PROPERTIES: :ID: ec5a41c6-90ba-4b0c-a20b-6bd7727da1c0 :END:
  [2010-07-23 Fri 13:00]
* TOBUY Michel Houellebecq [[http://fr.wikipedia.org/wiki/H._P._Lovecraft._Contre_le_monde,_contre_la_vie][H. P. Lovecraft. Contre le monde, contre la vie]]
  :PROPERTIES: :ID: 2dbbbe87-bf91-47f9-a4b9-1c9e89cc8bce :END:
* TOBUY [[http://www.amazon.com/gp/product/1891830430?ie%3DUTF8&ref%3Daw_bottom_links&force-full-site%3D1][Blankets - Craig Thompson]] :@graphicnovel:
  :PROPERTIES: :ID: 8d3bb85b-3450-493a-9c59-5a3ceb762675 :END: At 592
  pages, Blankets may well be the single largest graphic novel ever
  published without being serialized first. Wrapped in the landscape
  of a blustery Wisconsin winter, Blankets explores the sibling
  rivalry of two brothers growing up in the isolated country, and the
  budding romance of two coming-of-age lovers. A tale of security and
  discovery, of playfulness and tragedy, of a fall from grace and the
  origins of faith. A profound and utterly beautiful work from Craig
  Thompson. The New Printing corrects 3 small typos, widening the
  spine graphics, but otherwise is identical to the first printing.
* READ Rollins, James - Sandstorm
  :LOGBOOK: - State "READ" from "READING" [2012-07-18 Wed 13:00]
    \\ Good yarn.  Fast paced with enough science to keep it
    interesting.  - State "READING" from "" [2012-03-21 Wed
    12:00] :END: :PROPERTIES: :ID:
    de970816-7589-4e78-8149-f7cb9bf464b5 :END:
* READ Dan Abnett - Embedded
  :LOGBOOK: - State "READ" from "READING" [2012-03-19 Mon 20:22] -
    State "READING" from "" [2012-01-18 Wed
    12:31] :END: :PROPERTIES: :ID:
    5ae886c3-16dd-412b-8dae-be08a276e9a4 :END:
* READ Stephen Baxter - Ark
  :LOGBOOK: - State "READ" from "READING" [2012-01-18 Wed 11:27] -
    State "READING" from "READ" [2011-11-02 Wed
    19:10] :END: :PROPERTIES: :ID:
    08EB595C-547D-447F-9B01-1A4239D0040B :END:
* READ Joe Haldeman - Starsbound
  :LOGBOOK: - State "READ" from "READING" [2011-11-02 Wed 19:09]
    \\ not at this date...  - State "READING" from "" [2011-06-29 Wed
    15:16] :END: :PROPERTIES: :ID:
    b9889b65-6841-414c-a857-b7f8b54d2efb :END:
* READ Robert J. Sawyer - Watch
  :LOGBOOK: - State "READ" from "READING" [2011-06-28 Tue 15:16] -
    State "READING" from "READING" [2011-05-19 Thu 13:44] :END:
* READ Greg Bear - Mariposa
  :LOGBOOK: - State "READ" from "READING" [2011-05-19 Thu 13:45] :END:
* READ John Scalzi - The Android's Dream
  :LOGBOOK: - State "READ" from "READING" [2011-03-19 Sat 13:44] -
    State "READING" from "READING" [2011-01-31 Mon
    16:37] :END: :PROPERTIES: :ID:
    93a97bfc-7c9e-40d9-a43a-26ce41a44e96 :END:
* READ Stephen Baxter - Manifold Time 
  :LOGBOOK: - State "READ" from "READING" [2011-01-31 Mon 16:36] -
    State "READING" from "" [2010-10-02 Sat
    14:47] :END: :PROPERTIES: :ID:
    B9A1A4CD-1170-4A99-95A0-DBC0634361A1 :END:
* READ John Varley - Rolling Thunder
  :LOGBOOK: - State "READ" from "READING" [2010-10-02 Sat 14:45] -
    State "READING" from "" [2010-07-20 Tue
    12:45] :END: :PROPERTIES: :ID:
    7146897B-07AA-4B79-A1C5-8B52FD1FD89A :END: [2010-07-20 Tue 12:41]
* READ The Ghost Brigades - John Scalzi
  :LOGBOOK: - State "READ" from "READING" [2009-11-18
    Wed] :END: :PROPERTIES: :ID:
    7D46EA2C-DA96-4D46-9222-909DE028CEA6 :END: [2009-11-04 Wed 13:14]
* READ The Last Colony - John Scalzi
  :LOGBOOK: - State "READ" from "READING" [2010-02-05 Fri] - State
    "READING" from "READING" [2009-12-02 Wed] :END: :PROPERTIES: :ID:
    91729768-3391-4190-9821-0FCF65A7973D :END:
* READ Marsbound - Joe Haldeman
  :LOGBOOK: - State "READ" from "READING" [2010-06-30 Wed 15:06] -
    State "READING" from "" [2010-02-09 Tue] :END: :PROPERTIES: :ID:
    151C88C1-9EC5-4208-A077-C9A3D0CDEFDB :END:
