
* [2010-03-20 Sat] Great EBow video                                 :@guitar:
  - YouTube - Phil Keaggy Ebow
    http://www.youtube.com/watch?v=wwq0i6jP7dQ&feature=related

* [2010-03-20 Sat] The Vibesware Resonator                          :@guitar:
  - How to play with the Vibesware Guitar Resonator | eHow.com
    http://www.ehow.com/how_5108858_play-vibesware-guitar-resonator.html
  - MySpace Video - Vibesware's Video Channel & Video Clips
    http://vids.myspace.com/index.cfm?fuseaction=vids.channel&vanity=vibesware

* TODO [2010-03-20 Sat] RockSchool Keep downloading!            :@todownload:
  :PROPERTIES:
  :ID:       2098A03D-EF5A-4EA0-812A-3ACC1F0EDF57
  :END:
  - YouTube - Rockschool - Series 1 - Ep.3 - Techniques (Part 3 of 3)
    http://www.youtube.com/watch?v=dWkN6dldYt8&feature=related

* [2010-03-20 Sat] Spas et massages
  - Strom spa nordique - Île-des-Soeurs Montréal
    https://www.stromspa.com/secure.asp?Lang=F&Pid=home.asp&STID=&Music=Off
  - Massages
    http://www.skyspa.ca/fr/services-et-tarifs/massotherapie
  - massage sous la pluie - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=massage+sous+la+pluie&ie=UTF-8&oe=UTF-8&redir_esc=&ei=DUulS_ydIcSAlAex3tT1Ag
  - Studio Bliss - Tarifs
    http://www.studiobliss.ca/tarifs.html
  - Laser Spa. Clinique de soins corporels - Épilation Laser - Esthétique
    http://www.laser-spa.com/
  - Vague Tropicale
    http://www.vaguetropicale.ca/index.htm

* [2010-03-20 Sat] Using Handbrake from the command line             :@video:
  - CLIGuide – HandBrake
    http://trac.handbrake.fr/wiki/CLIGuide

* [2010-03-20 Sat] Logging for iPhone development              :@dev:@iPhone:
  - iPhone Dev » How to Implement Grabbing a Sprite with Cocos2d and Box2d
    http://iphonedev.net/2009/08/05/how-to-grab-a-sprite-with-cocos2d-and-box2d/
  - Logs » Chris-Software.com
    http://chris-software.com/index.php/2009/04/29/logs/
  - How to Log to the Console Using NSLog
    http://getsetgames.com/2009/12/22/iphonedev-advent-tip-22-how-to-log-to-the-console-using-nslog/

* [2010-03-20 Sat] Adding trackers to torrents                     :@torrent:
  - PublicBitTorrent - An open tracker project
    http://publicbt.com/tracker_modify.html

* [2010-03-20 Sat] Remote control for transmission   :@torrent:@transmission:
  - man/transmission-remote – Transmission
    http://trac.transmissionbt.com/wiki/man/transmission-remote

* [2010-03-20 Sat] Emacs Mac OS X tweaks                             :@emacs:
  - EmacsWiki: Mac OSTweaks
    http://www.emacswiki.org/emacs/MacOSTweaks#toc22

* [2010-03-23 Tue] Time machine tips                      :@mac:@timemachine:
  - Migrate a Time Machine backup | Business Center | Working Mac | Macworld
    http://www.macworld.com/article/146085/2010/02/migratebackups.html
  - Access alternate Time Machine drives | Mac OS X | Mac OS X Hints | Macworld
    http://www.macworld.com/article/147185/2010/03/alttimemachinedrives.html?lsrc=nl_mwhints_h_crawl

* [2010-03-28 Sun] Relaxation music
  - Alex Theory - Wikipedia, the free encyclopedia
    http://en.wikipedia.org/wiki/Alex_Theory
  - Amazon.com: Alex Theory: Music
    http://www.amazon.com/exec/obidos/search-handle-url?_encoding=UTF8&search-type=ss&index=music&field-artist=Alex%20Theory
  - - Sounds True - Full Spectrum Sound Healing
    http://shop.soundstrue.com/shop.soundstrue.com/SelectProd.do;jsessionid=7CAD05B248360D7F13BE93888D37ACA4?prodId=2214&manufacturer=Sounds%20True&category=Meditation%20&%20Massage%20Music&name=Full%20Spectrum%20Sound%20Healing

* [2010-03-28 Sun] Logging with NSLog              :@objectivec:@development:
  - CocoaDev: NSLog
    http://www.cocoadev.com/index.pl?NSLog
  - CocoaDev: UsingTheDescriptionMethod
    http://www.cocoadev.com/index.pl?UsingTheDescriptionMethod
* [2010-03-28 Sun] iPhone Bonjour                     :@dev:@iphone:@bonjour:
  - iPhone Dev Center: NSNetServices and CFNetServices Programming Guide: Introduction to NSNetServices and CFNetServices Programming Guide
    http://developer.apple.com/iphone/library/documentation/Networking/Conceptual/NSNetServiceProgGuide/Introduction.html
  - Tutorial: Networking and Bonjour on iPhone
    http://www.mobileorchard.com/tutorial-networking-and-bonjour-on-iphone/
  - MDNS and caffeine: How I got Bonjour running on my iPhone
    http://www.tuaw.com/2007/10/22/mdns-and-caffeine-how-i-got-bonjour-running-on-my-iphone/

* [2010-05-20 Thu]                                                 :@cocos2d:
  - iPhone Dev » How to Implement Grabbing a Sprite with Cocos2d and Box2d
    http://iphonedev.net/2009/08/05/how-to-grab-a-sprite-with-cocos2d-and-box2d/

* [2010-05-20 Thu]                                                     :@mac:
  - Better command history browsing in Terminal | Mac OS X | Mac OS X Hints | Macworld
    http://www.macworld.com/article/146015/2010/01/termhistory.html?lsrc=nl_mwhints_h_crawl

* Télécharger des sous-titres francais pour tous les films sans vous compliquer la vie à les resynchroniser. | Sub Synchro
   Source: [2010-10-31 Sun], [[http://www.subsynchro.com/][Télécharger des sous-titres francais pour tous les films sans vous compliquer la vie à les resynchroniser. | Sub Synchro:Safari]]

* [2010-11-05 Fri] Subtitle editing on the Mac                    :@subtitle:
  - les poupees russes subtitles - Google Search
    http://www.google.com/search?q=les+poupees+russes+subtitles
  - Features
    http://www.jubler.org/features/index.php
  - Submerge
    http://www.bitfield.se/submerge/
  - RoadMovie
    http://www.bitfield.se/roadmovie/index.html
  - D-Subtitler ObjectifMac
    http://www.objectifmac.com/dsubtitler.php
  - Browse Sears Files on SourceForge.net
    http://sourceforge.net/projects/sears/files/
* [2010-11-05 Fri] Misc
** CutyCapt - A Qt WebKit Web Page Rendering Capture Utility
   http://cutycapt.sourceforge.net/
** MuseScore | Free music composition & notation software :@linux:@musicmaker:@sequencer:
   http://musescore.org/
** VocProc @ HyperGlitch                      :@musicmaker:@harmonize:@linux:
   http://hyperglitch.com/dev/VocProc
* [2010-11-05 Fri] Monome                                           :@monome:
  - monome - flin is fun
    http://post.monome.org/comments.php?DiscussionID=38
  - app:flin [monome]
    http://docs.monome.org/doku.php?id=app:flin
* [2010-11-05 Fri] How to Create iPad Formatted Videos Using HandBrake or FFMpeg :@ipad:@video:
  http://www.ioncannon.net/meta/1040/how-to-create-ipad-formatted-videos-using-handbrake-or-ffmpeg/
* [2010-11-05 Fri] Normalizing Audio for Multiple AVI files
  - Mini Guide: Normalizing Audio for Multiple AVI files
    http://forum.videohelp.com/threads/255147-Mini-Guide-Normalizing-Audio-for-Multiple-AVI-files
  - Multimedia Dynamite | Linux Journal
    http://www.linuxjournal.com/article/9787
* [2010-11-05 Fri] Watching directories for new files
  - Linux.com - Automatically process new files with fsniper
    http://www.linux.com/archive/articles/150200
  - fsniper documentation
    http://files.minuslab.net/doc.html
  - Pyinotify
    http://trac.dbzteam.org/pyinotify
  - smash at blogs.perl.org: Watching directories for new files
    http://blogs.perl.org/users/smash/2010/07/watching-directories-for-new-files.html
* [2010-11-05 Fri] Twitter stuff                            :@twitter:@emacs:
  - MRR Software
    http://www.mrrsoftware.com/MRRSoftware/Syrinx.html
  - EmacsWiki: Twitter
    http://www.emacswiki.org/emacs/Twitter
  - EmacsWiki: Tw It
    http://www.emacswiki.org/emacs/TwIt
  - EmacsWiki: Twittering Mode
    http://www.emacswiki.org/emacs/TwitteringMode
  - EmacsWiki: Identica-mode
    http://www.emacswiki.org/emacs/Identica-mode
  - identica emacs - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=identica+emacs&ie=UTF-8&oe=UTF-8&redir_esc=&ei=YeHTTIe9GtCgnQeJ8eSGBg
  - Identi.ca mode for Emacs | Nethazard.net
    http://blog.nethazard.net/identica-mode-for-emacs/
  - Pwytter: Twitter for Windows, Mac, Linux » Free Twitter client for Windows, Mac & Linux
    http://www.pwytter.com/

* [2010-11-05 Fri] Backuppc stuff                                 :@backuppc:
  - Back Up Linux And Windows Systems With BackupPC - Page 3 | HowtoForge - Linux Howtos and Tutorials
    http://www.howtoforge.com/linux_backuppc_p3

* [2010-11-05 Fri] Check avi file for errors                         :@video:
  - Scanning AVI files for errors - MvixCommunity - Forums & Wiki Dedicated to Mvix Products - Powered by FusionBB
    http://mvixcommunity.com/showtopic.php?tid/1407
  - Program to verify quality of avi files
    http://forum.videohelp.com/threads/243934-Program-to-verify-quality-of-avi-files
  - HOWTO: Check avi file for errors
    http://606u.dir.bg/avicheck/

* [2011-01-03 Mon] Commander-like interface for emacs                :@emacs:
 - EmacsWiki: Sunrise Commander Tips
   http://www.emacswiki.org/emacs/Sunrise_Commander_Tips
 - EmacsWiki: Sunrise Commander
   http://www.emacswiki.org/emacs/Sunrise_Commander

* [2011-01-25 Tue] Yasnippet notes - usage for templates             :@emacs:
  - yasnippet - Project Hosting on Google Code
    http://code.google.com/p/yasnippet/
  - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/search?group=smart-snippet&q=new&qt_g=Search+this+group
  - Issue 124 in yasnippet: yas/new-snippet default template creates spurious 'k-e-y-b-i-n-d-i-n-g' binding - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/browse_thread/thread/7e6d0b3c6448a7f7/400e1c6ceecfd5da?lnk=gst&q=new#400e1c6ceecfd5da
  - Issue 150 in yasnippet: Insertion for new created file fails - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/browse_thread/thread/b3027718dc13bc/57c0d20087253021?lnk=gst&q=new#57c0d20087253021
  - Expand snippet on visiting new file? - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/browse_thread/thread/6299b29069be4cf0/1b06c9499669cd65?lnk=gst&q=new#1b06c9499669cd65

* [2011-04-13 Wed] Recording BBC 4 shows                :@internetradio:@bbc:
  - http://forums.linuxmint.com/viewtopic.php?f=48&t=62200#p357271
    Basically use
    : get_iplayer --modes=flashaacstd --pid  http://www.bbc.co.uk/iplayer/console/...
    where http://www.bbc... is the "listen now" link on the show page.

* [2011-06-07 Tue] Controlling iTunes - Example code           :@dev:@itunes:
  - Open Alexandria » Blog Archive » My Tunes Controller – control iTunes on menu bar
    http://openalexandria.com/2010/10/my-tunes-controller/
  - iTunesController.m - mytunescontroller - MyTunesController - Google Project Hosting
    http://code.google.com/p/mytunescontroller/source/browse/trunk/iTunesController.m

* [2011-06-07 Tue] Some Cocoa source code                       :@dev:@cocoa:
** Cocoa Source Code » Matt Legend Gemmell
   http://mattgemmell.com/source
** Details
  :PROPERTIES:
  :VISIBILITY: folded
  :END:
  - MGSplitViewController
     MGSplitViewController is an enhanced replacement for
     UISplitViewController on the iPad. It allows displaying the
     master view in either orientation, toggling it with animation,
     changing the split from horizontal to vertical, dragging the
     divider, and more.
   - MGImageUtilities
     MGImageUtilities is a collection of useful UIImage categories
     for iPad and iPhone, including image-tinting and image-cropping
     functionality(which explicitly supports multiple orientations,
     and high-resolution Retina Displays).
   - iPad VGA Output
     iPad VGA Output is an open source iPad application showing how
     you can display content on an external display via the iPad VGA
     adapter. It includes a window which goes on the external screen,
     and a window which goes on the iPad, and shows how to detect
     supported external resolutions.
   - iPad Multi Touch
     iPad Multi Touch is an open source iPad application which lets
     you visually track multiple touches, up to the maximum number
     the iPad supports simultaneously (which is eleven, by the
     way). It has some nice Core Animation effects too.
   - Shady
     Shady is an open source Mac OS X application which lets you dim
     the screen beyond its usual limit, ideal for tired (or
     photo-sensitive) eyes.
   - MGScopeBar
     MGScopeBar provides a scope/filter bar much like you’ll find in
     Mail, the Finder (in the Find/Spotlight window), iTunes and
     elsewhere. You can see a demo movie of it here.
   - MGTemplateEngine
     MGTemplateEngine is a native Cocoa system for generating text
     output based on templates and data. It’s a close cousin of
     systems like Smarty, FreeMarker, Django‘s template language, and
     other such systems.
     It’s ideal for Cocoa or iPhone apps needing to generate text
     output using variable-substitution (with looping and/or
     conditional logic), including HTML for export or for apps with
     WebKit-based UIs, invoices or printable templates, mail merge,
     data export or any number of other things. It’s also great (in
     combination with WebKit) for letting your users create
     themes/styles for your application.
   - Skinnable App
     This is a small application demonstrating how to use an embedded
     WebKit WebView to easily “skin” your applications, i.e. style
     your app’s UI using standard CSS files. It shows how to switch
     CSS themes dynamically, how to use Objective-C to add HTML
     content into a WebView, how to retrieve data from the HTML
     document, how to replace existing content, and how to allow HTML
     controls (form elements) to call methods in Cocoa objects.
   - MGTwitterEngine (on github) 
     MGTwitterEngine is a class which lets you integrate Twitter
     support into your Cocoa application, by making use of the
     Twitter API. The entire API is covered, and appropriate data is
     returned as simple Cocoa objects (NSArrays, NSDictionarys,
     NSStrings, NSDates and so on), for very easy integration with
     your code. Creating a TwitterEngine is as easy as instantiating
     it, setting your Twitter username and password, and you’re
     done. See this blog post for more.
   - NSImage+QuickLook
     A category on NSImage allowing you to get an image containing a
     Quick Look preview of the file at a given path. You can specify
     the size, and whether the preview should be rendered as an icon
     (i.e. with a document border, drop-shadow, page-curl and file
     type/extension label superimposed). If Quick Look can’t generate
     a preview for the specified file, you’ll be given the file’s
     Finder icon instead (which is how the Quick Look panel itself
     behaves in Leopard).
   - MAAttachedWindow
     A cool NSWindow subclass which lets you easily attach a view to
     another window, displayed in a floating “speech-bubble”-like
     borderless window. Very handy for contextual help, showing
     options for a certain control, or just to draw attention to
     things. Have a look at this screenshot to see how it works. You
     can also grab a project showing how to use an MAAttachedWindow
     with an NSStatusItem.
   - MATrackingArea
     A simple category on NSView and an accompanying class which
     together allow you to add “tracking areas” to your
     views. Tracking areas are like tracking rectangles but are more
     robust and effective, and can be configured to track the mouse
     either at all times, only when the view’s app is active, only
     when the view’s window is key, or only when the view is First
     Responder. You can also choose whether to use the view’s visible
     rect in preference to the rect you pass in. See the example for
     details.
   - MGViewAnimation
     An NSAnimation subclass which provides more desirable behaviour
     than NSViewAnimation itself in most circumstances; i.e. it
     animates the views’ frames itself in the same thread, leading to
     visually synchronised movement. Try out the included sample app
     to see the difference between regular NSViewAnimations and
     these.
   - NSColor+ContrastingLabelExtensions
     A category on NSColor which returns another NSColor for use when
     drawing label text on top of the receiver. Either white or black
     is returned, depending on which will have most visual contrast
     with the receiver’s color. In the event of the receiver’s
     colorspace not being converted to RGB, black is returned by
     default.
   - ImageCrop
     A category on NSImage allowing you to obtain a resized version
     of the image to fit an arbitrary size, with a choice of cropping
     or scaling methods (crop center, crop start, crop end, or scale
     to fit). Uses high-quality interpolation too.
   - HUDWindow
     An NSPanel subclass which creates a translucent window like
     iPhoto “Adjust” palette. Useful for graphics applications where
     a non-intrusive, high-contrast UI style is needed. Or just to
     look cool.
   - RoundedBox
     An NSBox subclass which draws a pretty rounded-rectangle box
     with a gradient background; take a look at the screenshot to see
     how it looks. Includes lots of configurable options, and it’s
     ready to drop right into your project.
   - TunesWindow
     A project which displays a window in the iTunes 5/6
     (i.e. “polished metal”) style. Like the Unified look, but
     darker. Get the iTunes look in your own apps easily.
   - iCal Calendars
     A simple application which reads iCal’s calendars and returns an
     NSDictionary whose keys are the names of the calendars, and
     whose values are Calendar objects, with fields “title”
     (NSString), “notes” (NSString), “color” (NSColor), and both GUID
     keys used by iCal to keep track of calendars and their source
     data.
   - NSBezierPath+StrokeExtensions
     A simple category on NSBezierPath allowing you stroke inside a
     path, rather than stroking centered on the path.
   - RoundedFloatingPanel
     An NSView subclass and accompanying NSWindow subclass which
     provide the same rounded floating panel overlay which the
     Panther application switcher uses.
   - iTableColumnHeader
     An NSTableHeaderCell subclass providing the metallic column
     headers seen in iApps, including the Calendars list in iCal and
     the Source list in iTunes.
   - iTableView (Source List and Colored Checkboxes)
     A pair of NSTextFieldCell and NSImageCell subclasses (and a
     simple NSTableView subclass) which provide the blue-gradient
     selection highlighting behaviour you see in iCal’s “Calendars”
     list, iTunes’ “Source” list, and the sidebar in the Panther
     Finder. Apple calls this kind of control a Source List.
     Also includes code to draw colored checkboxes as in iCal, using
     any color you want!
   - Address Book Test
     Shows how to make use of the Mac OS X 10.2 Address Book
     API. Includes a live-filtering field which locates Address Book
     entries by forename, surname or company, and demonstrates
     finding the primary email address for a specified person, as
     well as their name and picture.
   - Better TextFinder
     Easily implement Find and Replace in your application. Adapted
     and improved from TextEdit’s implementation. Includes both the
     class and a Nib file containing an appropriate Find panel. Read
     more about the improvements here.
   - SS_PrefsController
     A class which lets you easily create Mail/iTunes/Safari-style
     Preferences windows, with toolbars and multiple panes loaded
     from bundles. Loads of configurable options and flexibility, and
     professional results. Take a look at the class documentation
     (also included in the download).
   - Window Fade-out
     Ever felt the need to have a window fade out of existence,
     instead of just closing? Here’s how.
   - Grab-Scrolling
     Shows how to implement grab-scrolling, like in Preview,
     Photoshop, Acrobat and more. Includes the two requisite
     hand-cursors.
   - Screen Sharing
     Source for two apps, a client and a server, letting you send
     full-screen screenshots of your Mac via Rendezvous. This is a
     modification of Apple’s Picture Sharing code.


* [2011-10-04 Tue] Bash completion/expansion notes             :@linux:@bash:
   - Bash Alias Utilities
     http://www.logicalpoetry.com/bashalias/
   - Working more productively with bash 2.x/3.x
     http://caliban.org/bash/#completion
   - Bashrun - X11 application launcher based on bash
     http://bashrun.sourceforge.net/
   - An introduction to bash completion: part 1
     http://www.debian-administration.org/articles/316
   - revans/bash-it - GitHub
     https://github.com/revans/bash-it
   - robbyrussell/oh-my-zsh - GitHub
     https://github.com/robbyrussell/oh-my-zsh
   - Themes - GitHub
     https://github.com/robbyrussell/oh-my-zsh/wiki/themes

* [2011-11-08 Tue] Using ediff as a mercurial merge tool  :@emacs:@mercurial:
  - emacs - Using ediff as git mergetool - Stack Overflow
    http://stackoverflow.com/questions/1817370/using-ediff-as-git-mergetool
  - configuration - How can I use ediff (emacs diff) as a diff/merge tool in Windows ClearCase? - Stack Overflow
    http://stackoverflow.com/questions/658127/how-can-i-use-ediff-emacs-diff-as-a-diff-merge-tool-in-windows-clearcase
  - Flow-Geek: Using Emacs ediff as a graphical merge tool for Subversion
    http://zaakbeekman.blogspot.com/2011/04/using-emacs-ediff-as-graphical-merge.html
  - MergingWithEmacs - Mercurial
    http://mercurial.selenic.com/wiki/MergingWithEmacs
  - MergeToolConfiguration - Mercurial
    http://mercurial.selenic.com/wiki/MergeToolConfiguration
  - ExtdiffExtension - Mercurial
    http://mercurial.selenic.com/wiki/ExtdiffExtension
  - Merging with Emacs and ediff-mode
    http://www.selenic.com/pipermail/mercurial/2008-November/022599.html

* [2011-11-08 Tue] mkv/ac3 Conversion          :@video:@conversion:@mkv:@ac3:
  - Convert mkv movies into mp4 - Page 4 - MacRumors Forums
    http://forums.macrumors.com/showthread.php?t=301017&page=4
  - Convert mkv movies into mp4 - Page 5 - MacRumors Forums
    http://att.macrumors.com/showthread.php?t=301017&page=5
  - Converting an MKV (h264) File to PS3 MP4 Without Re-encoding on Mac OS X « Just Another Odd Man Out
    http://oddmanout.wordpress.com/2008/01/26/converting-an-mkv-h264-file-to-ps3-mp4-without-re-encoding-on-mac-os-x/
  - Help: Need to put AC3 into MP4 with ffmpeg
    http://forum.videohelp.com/threads/311525-Help-Need-to-put-AC3-into-MP4-with-ffmpeg

* [2011-11-08 Tue] Ambient music                            :@music:@ambient:
  - www.darkwinter.com
    http://www.darkwinter.com/index1.html

* [2011-11-08 Tue] org-mode on MacOS                          :@orgmode:@mac:
  - org-protocol - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=org-protocol&ie=UTF-8&oe=UTF-8&redir_esc=&ei=wJKHTuaVH4XK0AH-iJ37Dw
  - Remember Mode Tutorial
    http://members.optusnet.com.au/~charles57/GTD/remember.html
  - org-protocol.el – Intercept calls from emacsclient to trigger custom actions
    http://orgmode.org/worg/org-contrib/org-protocol.html
  - Org and Mac OS X
    http://orgmode.org/worg/org-mac.html
  - org-mac-message.el – linking to messages in OS X Mail.app
    http://orgmode.org/worg/org-contrib/org-mac-message.html
  - claviclaws/org-mac-protocol - GitHub
    https://github.com/claviclaws/org-mac-protocol
  - org-mac-protocol.org at master from claviclaws/org-mac-protocol - GitHub
    https://github.com/claviclaws/org-mac-protocol/blob/master/org-mac-protocol.org
  - org-mac-protocol.el at master from claviclaws/org-mac-protocol - GitHub
    https://github.com/claviclaws/org-mac-protocol/blob/master/org-mac-protocol.el
  - org-note.applescript at master from claviclaws/org-mac-protocol - GitHub
    https://github.com/claviclaws/org-mac-protocol/blob/master/org-note.applescript

* [2011-11-08 Tue] Use Spotlight to globally index any text file :@spotlight:
  - 10.4: Use Spotlight to globally index any text file - Mac OS X Hints
    http://hints.macworld.com/article.php?story=2005052015041510

* [2011-11-08 Tue] Blade Runner soundtracks             :@bladerunner:@music:
  - The Blade Runner Soundtracks Ultimate Thread - Page 18
    http://forums.ffshrine.org/f92/blade-runner-soundtracks-ultimate-thread-72496/18.html#post1604062
  - blade runner esper retirement edition torrent - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=blade+runner+esper+retirement+edition+torrent&ie=UTF-8&oe=UTF-8&redir_esc=&ei=SDJ-TvfSBozp0QH4rqX4Dw
  - Scifi.dead-donkey.com • View topic - Blade Runner - Esper Retirement Edition
    http://scifi.dead-donkey.com/viewtopic.php?f=13&t=4553
  - Various Artists Blade Runner Esper 039 Retirement 039 Edit Torrent - TorrentFunk
    http://www.torrentfunk.com/torrent/2775394/various-artists-blade-runner-esper-039-retirement-039-edit.html
  - The Blade Runner Soundtracks Ultimate Thread - Page 28
    http://forums.ffshrine.org/f92/blade-runner-soundtracks-ultimate-thread-72496/28.html
  - blade runner ems2011 - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=blade+runner+ems2011&ie=UTF-8&oe=UTF-8&redir_esc=&ei=6DV-TsGgLqHy0gG91pzXDw
  - EMS Recombination
    http://emsrecombination.blogspot.com/
  - ems recombination definitive 3 disc edition - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=EMS+Recombination+Definitive+3+Disc+Edition&ie=UTF-8&oe=UTF-8&redir_esc=&ei=7zl-TsK7MILn0QG6rt0K
  - Do Androids Dream Of Lossless Audio Files? A Blade Runner Soundtrack Thread - Page 22
    http://forums.ffshrine.org/f92/do-androids-dream-lossless-audio-files-blade-75274/22.html

* [2011-11-08 Tue] tmux notes                              :@linux:@terminal:
  - tmux
    http://tmux.sourceforge.net/
  - Manual Pages: tmux(1)
    http://www.openbsd.org/cgi-bin/man.cgi?query=tmux&sektion=1
  - TMUX – The Terminal Multiplexer (Part 1) | Hawk Host Blog
    http://blog.hawkhost.com/2010/06/28/tmux-the-terminal-multiplexer/
  - TMUX – The Terminal Multiplexer (Part 2) | Hawk Host Blog
    http://blog.hawkhost.com/2010/07/02/tmux-%e2%80%93-the-terminal-multiplexer-part-2/
  - dayid's screen and tmux cheat sheet
    http://www.dayid.org/os/notes/tm.html

* [2011-11-08 Tue] Great color scheme                :@terminal:@colorscheme:
  - mayansmoke - Ergonomic light-background color scheme. : vim online
    http://www.vim.org/scripts/script.php?script_id=3065

* [2011-11-08 Tue] byobu notes                             :@byobu:@terminal:
  - Canonical Voices
    http://voices.canonical.com/tag/byobu/
  - Byobu - Community Ubuntu Documentation
    https://help.ubuntu.com/community/Byobu
  - Ubuntu Manpage: byobu - wrapper script for seeding a user's byobu configuration and
    http://manpages.ubuntu.com/manpages/oneiric/en/man1/byobu.1.html
  - byobu in Launchpad
    https://launchpad.net/byobu
  - From the Canyon Edge - :-Dustin Kirkland: Byobu
    http://blog.dustinkirkland.com/search/label/Byobu

* [2011-11-08 Tue] HOWTORead Feeds In Emacs Via Email    :@feeds:@wanderlust:
  - EmacsWiki: HOWTORead Feeds In Emacs Via Email
    http://www.emacswiki.org/emacs/HOWTOReadFeedsInEmacsViaEmail#toc5

* [2011-11-08 Tue] Cabinet simulator links              :@musicmaker:@cabsim:
  - Condor Cab Sim
    http://runoffgroove.com/condor.html
  - Op-Amp review page
    http://www.rock-grotto.co.uk/opamp.htm

* DONE [#A] [2011-11-08 Tue] Time machine tweaks           :@mac:timemachine:
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2012-03-29 Thu 10:37]
  :END:
  :PROPERTIES:
  :ID:       d0a001af-917a-4168-819a-97ea5208eb7e
  :END:
  - Good folders to exclude from Time Machine backups – Ryan Block
    http://ryanblock.com/2008/05/good-folders-to-exclude-from-time-machine-backups/

* [2011-11-08 Tue] Amp sim                              :@musicmaker:@ampsim:
  - Head Case | AcmeBarGig
    http://www.acmebargig.com/product/head-case/

* [2011-11-08 Tue] Impulse response AU plugins      :@musicmaker:@cabsim:@au:
  - Amplifikation Lite at Kuassa Amplifikation
    http://www.kuassa.com/products/amplifikation-lite
  - Mellowmuse IR1A - Zero Latency convolver RTAS, AudioUnit and VST plug-in for OSX and Windows
    http://www.mellowmuse.com/IR1A.html

* [2011-11-08 Tue] Embed album cover art from the command line :@music:@tag:@cover:
  - How do you embed album art into an MP3 using Python? - Stack Overflow
    http://stackoverflow.com/questions/409949/how-do-you-embed-album-art-into-an-mp3-using-python
  - Howto Write APIC Tag with Mutagen - Quod Libet Development | Google Groups
    http://groups.google.com/group/quod-libet-development/browse_thread/thread/72a19593a44d6243?pli=1
  - eyeD3 0.6.17
    http://eyed3.nicfit.net/
  - Embedded Album Covers, Your PSP, Amarok, and You – Kasperian Moving Parts
    http://movingparts.net/2007/12/09/embedded-album-covers-your-psp-amarok-and-you/

* [2011-11-08 Tue] Openbox links                        :@linux:@wm:@openbox:
  - Openbox guide « urukrama’s weblog
    http://urukrama.wordpress.com/openbox-guide/

* [2011-11-08 Tue] Remove accents from filenames/dirnames      :@dev:@python:
  - \xe9 - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=%5Cxe9&ie=UTF-8&oe=UTF-8&redir_esc=&ei=CPhvToKwGIH50gHKirn-CA
  - Python Unicode Objects
    http://effbot.org/zone/unicode-objects.htm
  - Converting Unicode Strings to 8-bit Strings
    http://effbot.org/zone/unicode-convert.htm
  - string.translate - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=string.translate&ie=UTF-8&oe=UTF-8&redir_esc=&ei=EI5wTrTfCqrD0AH4uYH3CQ
  - 7.1. string — Common string operations — Python v2.7.2 documentation
    http://docs.python.org/library/string.html
  - Python String translate() Method
    http://www.tutorialspoint.com/python/string_translate.htm
  - Simple Wrapper for string.translate « Python recipes « ActiveState Code
    http://code.activestate.com/recipes/303342-simple-wrapper-for-stringtranslate/
  - pythno string translate accented - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=pythno+string+translate+accented&ie=UTF-8&oe=UTF-8&redir_esc=&ei=rY5wToybEqjL0QHi2fn3CQ
  - library - What is the best way to remove accents in a python unicode string? - Stack Overflow
    http://stackoverflow.com/questions/517923/what-is-the-best-way-to-remove-accents-in-a-python-unicode-string
  - regex - Python String Cleanup + Manipulation (Accented Characters) - Stack Overflow
    http://stackoverflow.com/questions/930303/python-string-cleanup-manipulation-accented-characters
  - How to convert an accented character in an unicode string to its unicode character code using Python? - Stack Overflow
    http://stackoverflow.com/questions/3499087/how-to-convert-an-accented-character-in-an-unicode-string-to-its-unicode-charact
  - Latin1 to ASCII -- The UNICODE Hammer « Python recipes « ActiveState Code
    http://code.activestate.com/recipes/251871-latin1-to-ascii-the-unicode-hammer/

* [2011-11-09 Wed] Making Impulse Responses                 :@musicmaker:@ir:
  - Making Impulse Responses with Logic's IR Utility
    http://www.soundonsound.com/sos/feb08/articles/logictech_0208.htm
  - GuitarAmpModeling.com • View topic - Creating Your OWN IR Files in Cubase!!
    http://www.guitarampmodeling.com/viewtopic.php?f=32&t=12276
  - Creating Your OWN IR Files by Cubase! - YouTube
    http://www.youtube.com/watch?v=Z4-L5cPYHl4

* [2011-11-09 Wed] Music file tags on the command line          :@music:@tag:
- eyeD3 0.6.17
  http://eyed3.nicfit.net/
- EyeD3 | SavvyAdmin.com - Strip All Unwanted MP3 ID3 Tags
  http://savvyadmin.com/tag/eyed3/
- mp3sort.pl - template based mp3 sorter using ID3 tags
  https://github.com/aptituz/mp3sort/blob/master/mp3sort.pl
- GNU Songanizer Home Page
  GNU Songanizer is a shell script to organize a directory containing
  a collection of Ogg Vorbis and MP3 files.
  http://www.gnu.org/s/songanizer/
- arename
  http://ft.bewatermyfriend.org/comp/arename.html
- arename - automatically rename audio files by tagging information
  http://ft.bewatermyfriend.org/comp/arename/arename.html
- ftblog: audio helpers - zsh function atag()
  atag() provides a consistent way to the aforementioned file formats meta
  information
  http://bewatermyfriend.org/posts/2008/03-10.10-53-11-computer.html

* [2011-11-12 Sat] Python Music/MIDI               :@dev:@python:@musicmaker:
  - PythonInMusic - PythonInfo Wiki
    http://wiki.python.org/moin/PythonInMusic
** General Tools                                               :@audio:@midi:
   - The MusicKit V5.6.2
     http://musickit.sourceforge.net/
     The MusicKit is an object-oriented software system for building
     music, sound, signal processing, and MIDI applications.
** Audio Tools                                                       :@audio:
   - Python Audio Tools
     http://audiotools.sourceforge.net/
     Python Audio Tools are a collection of audio handling programs
     which work from the command line.
   - zyne - Modular synthesizer - Google Project Hosting
     http://code.google.com/p/zyne/
     Zyne is a Python modular synthesizer using pyo as its audio engine.
** MIDI Tools                                                         :@midi:
   - pyrtmidi – pkaudio
     http://trac.assembla.com/pkaudio/wiki/pyrtmidi
     pyrtmidi is a Python interface to RtMidi?. It provides real-time
     midi input and output.
   - mididings - a MIDI router/processor based on Python
     http://das.nasophon.de/mididings/
     mididings is a MIDI router and processor based on Python, supporting
     ALSA and JACK MIDI. It is available under the GNU GPL and currently
     runs on Linux. 
   - pyPortMidi
     http://alumni.media.mit.edu/~harrison/code.html
     pyPortMidi is a Python wrapper I wrote for PortMidi. PortMidi is a
     cross-platform C library for realtime MIDI control. Using
     pyPortMidi, you can send and receive MIDI data in realtime from
     Python.
   - pgreloaded - PyGame Reloaded - Multimedia Framework for Python
     http://code.google.com/p/pgreloaded/
     Pygame2 is a cross-platform multimedia framework for the
     excellent Python programming language. Its purpose is to make
     writing multimedia applications, such as games, with Python as easy
     as possible, while providing the developer a reliable and
     extensible programming interface.

* [2011-11-12 Sat] edna -- an MP3 server               :@mediaserver:@python:
  http://edna.sourceforge.net/
  edna allows you to access your MP3 collection from any networked
  computer. This software streams your MP3s via HTTP to any MP3 player
  that supports playing off a remote connection (e.g. Winamp, FreeAmp,
  Sonique, XMMS, WMP).

* [2011-11-13 Sun] virtualenv                                  :@python:@dev:
  - virtualenvwrapper - Doug Hellmann
    http://www.doughellmann.com/projects/virtualenvwrapper/
  - virtualenvwrapper 2.10.1 — virtualenvwrapper v2.10.1 documentation
    http://www.doughellmann.com/docs/virtualenvwrapper/
  - Presentation: pip and virtualenv | mathematism
    http://mathematism.com/2009/07/30/presentation-pip-and-virtualenv/
  - virtualenvwrapper on Vimeo
    http://vimeo.com/5894881

* [2011-11-20 Sun] Tagging audio files       :@python:@audio:@music:@discogs:
  - oliparcol/tagog - GitHub
    https://github.com/oliparcol/tagog
  - API / DiscogsTagger: A console based python metadata tagger based on the Discogs API
    http://www.discogs.com/help/forums/topic/251892
  - jesseward/discogstagger - GitHub
    https://github.com/jesseward/discogstagger
  - Requests: Python HTTP Module
    http://kennethreitz.com/requests-python-http-module.html
  - requests 0.8.2 : Python Package Index
    http://pypi.python.org/pypi/requests
  - kennethreitz/requests - GitHub
    https://github.com/kennethreitz/requests
  - discogs python api - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=discogs+python&ie=UTF-8&oe=UTF-8&redir_esc=&ei=eXnJTvrnBMn20gHN2tEP#sclient=psy-ab&hl=en&client=safari&rls=en&source=hp&q=discogs+python+api&pbx=1&oq=discogs+python+api&aq=f&aqi=g-v1&aql=&gs_sm=e&gs_upl=37951l38255l0l38530l4l3l0l0l0l0l146l429l0.3l3l0&bav=on.2,or.r_gc.r_pw.r_cp.,cf.osb&fp=1c55a80a74b83adf&biw=1033&bih=871
  - API v2.0 Documentation
    http://www.discogs.com/help/api
  - discogs/discogs-python-client - GitHub
    https://github.com/discogs/discogs-python-client

* [2011-11-20 Sun] Move windows on Macos                          :@dev:@mac:
  - cocoa - How can I programatically move one Terminal.app window to another space? - Stack Overflow
    http://stackoverflow.com/questions/2308820/how-can-i-programatically-move-one-terminal-app-window-to-another-space
  - Move window to second display | Cocoabuilder
    http://www.cocoabuilder.com/archive/cocoa/213109-move-window-to-second-display.html
  - objective c - Controlling OSX windows - Stack Overflow
    http://stackoverflow.com/questions/1730859/controlling-osx-windows

* [2011-11-20 Sun] Blogging with org-mode                    :@blog:@orgmode:
  - Blorgit: Org-Mode based, git amenable, blogging engine
    http://orgmode.org/worg/blorgit.html
  - Using org to Blog with Jekyll
    http://orgmode.org/worg/org-tutorials/org-jekyll.html

* [2011-11-20 Sun] org-mode tagging                           :@orgmode:@tag:
  - http://lisperati.com/tagging.html
    http://lisperati.com/tagging.html
  - EmacsWiki: Bookmark Plus
    http://www.emacswiki.org/emacs-se/BookmarkPlus#BookmarkTags
  - EmacsWiki: free-tagging.el
    http://www.emacswiki.org/emacs/free-tagging.el
  - Tag searches - The Org Manual
    http://orgmode.org/manual/Tag-searches.html#Tag-searches
  - Org-Mode for GNU Emacs
    http://comments.gmane.org/gmane.emacs.orgmode/34038
  - Generate list of all tags in use?
    http://permalink.gmane.org/gmane.emacs.orgmode/34069
  - Automatic global tag list?
    http://permalink.gmane.org/gmane.emacs.orgmode/33995

* [2011-11-20 Sun] Static blog generation and scm   :@blog:@python:@markdown:
  - Byteflow - a Python/Django Blog Engine
    http://byteflow.su/
  - blohg
    http://blohg.org/
    - blohg » About blohg
      http://blohg.org/about/
    - Welcome to blohg’s documentation! — blohg v0.8 documentation
      http://docs.blohg.org/
  - dz/chisel - GitHub
    https://github.com/dz/chisel
  - Cyrax — Cyrax v2.5
    http://cyrax.readthedocs.org/en/latest/index.html
  - lakshmivyas/hyde - GitHub
    https://github.com/lakshmivyas/hyde
  - Hyde - A Python Static Website Generator
    http://ringce.com/hyde
    - Ringce : Introducing Hyde
      http://ringce.com/blog/2009/introducing_hyde
    - Hyde Templates - GitHub
      https://github.com/lakshmivyas/hyde/wiki/Templating-Guide
    - Hyde | Google Groups
      http://groups.google.com/group/hyde-dev
    - New Hyde Layout based on Bootstrap - Hyde | Google Groups
      http://groups.google.com/group/hyde-dev/browse_thread/thread/7b928bddc29d74f0#
    - auzigog/hyde-bootstrap - GitHub
      https://github.com/auzigog/hyde-bootstrap
    - Bootstrap, from Twitter
      http://twitter.github.com/bootstrap/
    - Merlin Rebrovic
      http://merlin.rebrovic.net/
    - Hyde Starter Kit
      http://merlin.rebrovic.net/hyde-starter-kit/
    - Template links
      - Use Templates in Django | Webmonkey | Wired.com
        http://www.webmonkey.com/2010/02/use_templates_in_django/
      - Django snippets: Tag "template"
        http://djangosnippets.org/tags/template/
      - JeffCroft.com: Django Templates: The Power of Inheritance
        http://jeffcroft.com/blog/2006/feb/25/django-templates-the-power-of-inheritance/
      - 960 Grid System
        http://960.gs/
      - Django Slingshot - Home
        http://www.djangoslingshot.com/
  - Tahchee
    http://ivy.fr/tahchee/
  - Markdoc Documentation » Index
    http://markdoc.org/
  - Markdoc Documentation » Barebones Wikis
    http://markdoc.org/tips/barebones
  - obensonne / poole / overview — Bitbucket
    https://bitbucket.org/obensonne/poole
  - Static Blog Generators
    http://www.subspacefield.org/~travis/static_blog_generators.html
  - xfire/growl - GitHub
    https://github.com/xfire/growl/tree
  - jek / blatter / overview — Bitbucket
    https://bitbucket.org/jek/blatter/
  - Welcome to lanyon’s documentation! — Lanyon v6 documentation
    http://lanyon.readthedocs.org/en/latest/index.html
  - ikiwiki
    http://ikiwiki.info/
    - features
      http://ikiwiki.info/features/
    - blog
      http://ikiwiki.info/examples/blog/
  - What is FlatPress?
   http://flatpress.org/home/
  - Stacey, The Lightweight Content Management System
    http://staceyapp.com/
    - In Use, Stacey
      http://staceyapp.com/in-use/
  - Blogofile
    http://www.blogofile.com/
    - Blogofile
      http://www.blogofile.com/blog/
    - Documentation Blogofile Blogofile v1.0 DEV documentation
      http://www.blogofile.com/documentation/
  - welcome to Mako!
    http://www.makotemplates.org/
  - obensonne / poole overview / Bitbucket
    https://bitbucket.org/obensonne/poole
  - Hyde - A Python Static Website Generator
    http://ringce.com/hyde
    - lakshmivyas/hyde - GitHub
      https://github.com/lakshmivyas/hyde
    - sjl/stevelosh - GitHub
      https://github.com/sjl/stevelosh
    - Blog / Steve Losh
      http://stevelosh.com/blog/
    - Moving from Django to Hyde / Steve Losh
      http://stevelosh.com/blog/2010/01/moving-from-django-to-hyde/
  - Stango - Static web site generator for Python programmers
    http://www.digip.org/stango/
  - Welcome Jinja2 to Jinja2 2.7-dev documentation
    http://jinja.pocoo.org/docs/
  - jinja2 themes - Google Search
    https://www.google.com/search?q=jinja2+themes
  - FlatPress     # Flask-Themes Flask-Themes v0.1 documentation
    http://packages.python.org/Flask-Themes/
  - python hyde themes - Google Search
    https://www.google.com/search?hl=en&q=python+hyde+themes&oq=python+hyde+themes&aq=f&aqi=&aql=&gs_sm=e&gs_upl=34704l35805l0l36032l7l7l0l0l0l1l235l457l2-2l2l0
  - Pelican vs. Hyde- static website generators? : Python
    http://www.reddit.com/r/Python/comments/jaqn2/pelican_vs_hyde_static_website_generators/
  - Kenneth Reitz
    http://kennethreitz.com/
  - poxd/hyde-themes - GitHub
    https://github.com/poxd/hyde-themes
  - Pelican - Pelican v2 documentation
    http://readthedocs.org/docs/pelican/en/2.7.2/
    - Getting started — Pelican v2 documentation
      http://readthedocs.org/docs/pelican/en/2.7.2/getting_started.html#writing-articles-using-pelican
    - Settings — Pelican v2 documentation
      http://readthedocs.org/docs/pelican/en/2.7.2/settings.html#theming
    - notmyidea-cms/screenshot.png at master from ametaireau/pelican-themes - GitHub
      https://github.com/ametaireau/pelican-themes/blob/master/notmyidea-cms/screenshot.png
  - marcoarment/secondcrack - GitHub
    https://github.com/macoarment/secondcrack
  
* [2011-11-20 Sun] System info on a web page :@server:@homenetwork:@monitoring:
  - phpSysInfo
    http://phpsysinfo.sourceforge.net/
  - System information: vz-web-3.sog (192.168.42.1)
    http://phpsysinfo.sourceforge.net/phpsysinfo/index.php?disp=dynamic

* NEXT [#A] [2011-11-20 Sun] Managing dotfiles with revision control :@dotfiles:@hg:
  :PROPERTIES:
  :ID:       d66b1892-6916-4703-a04c-a27d45930805
  :END:
** Requirements
** Links
  - Mercurial
    - Smarter Code: Versioning Dotfiles in Mercurial
      http://blog.smartercode.net/2010/02/versioning-dotfiles-in-mercurial.html
    - Smarter Code: Managing Divergent Dotfiles with Mercurial Queues
      http://blog.smartercode.net/2010/02/managing-divergent-dotfiles-with.html
    - Carousel is a <i>lie!</i>: Mercurial for dotfiles
      http://saintaardvarkthecarpeted.com/blog/archive/2009/02/Mercurial_for_dotfiles.html
    - SingleDeveloperMultipleComputers - Mercurial
      http://mercurial.selenic.com/wiki/SingleDeveloperMultipleComputers
  - git
    - garybernhardt/dotfiles - GitHub
      https://github.com/garybernhardt/dotfiles
  - dotfiles « xyld
    http://xylld.wordpress.com/tag/dotfiles/

* [2011-11-20 Sun] Quicksilver notes                           :@quicksilver:
  - osasubr - a OS X unix command-line utility to pass arguments to an applescript.
    http://www.turbozen.com/mac/osasubr/
  - some Quicksilver goodness | Tamara Temple's Blog - Run [with arguments]
    http://www.tamaratemple.com/2010/08/20/some-quicksilver-goodness/
  - Quicksilver and the Command Line — Apple News, Tips and Reviews
    http://gigaom.com/apple/quicksilver-and-the-command-line/
  - "Open In" or "Run In" - Blacktree: Quicksilver | Google Groups
    http://groups.google.com/group/blacktree-quicksilver/browse_thread/thread/6dd5162d3e3108a7/e0377dca6988620e?lnk=gst&q=arguments&pli=1
  - Console commands using QS - Google Groups
    https://groups.google.com/forum/#!topic/blacktree-quicksilver/_EbnWc4oCM4
  - Executing actions - Quicksilver Wiki
    http://qsapp.com/wiki/Executing_actions
  - How to use Quicksilver's Shelf
    http://lifehacker.com/111278/how-to-use-quicksilvers-shelf
  - Mac snippet solution: Quicksilver Shelf | dotjay.co.uk
    http://dotjay.co.uk/2008/apr/mac-snippet-solution-quicksilver-shelf

* [2011-11-23 Wed] Emacs links                                       :@emacs:
** Deft                                                      :@deft:@orgmode:
   - A Lightweight Alternative To Emacs Org Mode | Irreal
     http://irreal.org/blog/?p=252
   - emacs-fu: quick note-taking with deft and org-mode
     http://emacs-fu.blogspot.com/2011/09/quick-note-taking-with-deft-and-org.html
   - Deft
     http://jblevins.org/projects/deft/
** Security                                                     :@encryption:
   - emacs-fu: keeping your secrets secret
     http://emacs-fu.blogspot.com/2011/02/keeping-your-secrets-secret.html

* [2011-11-26 Sat]                                             :@python:@mac:
  - Multiple Python Versions on OSX with Virtualenv and Homebrew | insomnihack
    http://www.insomnihack.com/?p=442

* [2011-11-26 Sat]                                           :@linux:@rescue:
  - Rescatux - Super Grub Disk
    Rescatux is a GNU/Linux rescue cd (and eventually also Windows)
    but it is not like other rescue disks. Rescatux comes with
    Rescapp. Rescapp is a nice wizard that will guide you through your
    rescue tasks.
    http://www.supergrubdisk.org/rescatux/

* [2011-11-26 Sat] MacOS Location handling                             :@mac:
  - MarcoPolo - Context-aware computing for Mac OS X
    http://www.symonds.id.au/marcopolo/
  - Location X — The Power of X, to Go!
    http://homepage.mac.com/locationmanager/
  - Mac OS X LocationChanger - TECH.inhelsinki.nl
    http://tech.inhelsinki.nl/locationchanger/

* [2011-11-26 Sat] PaulStretch for MacOS                        :@audio:@mac:
  - Paul's Extreme Sound Stretch
    http://hypermammut.sourceforge.net/paulstretch/
  - PaulStretch 2.1 is Out! New build instructions + new x86 OS X build | Do My Eyes Look Scary?
    http://music.cornwarning.com/2011/02/11/paulstretch-2-1-is-out-new-build-instructions-new-x86-os-x-build/

* [2011-11-26 Sat] Bandwidth monitoring                        :@homenetwork:
  - wrtbwmon - Per-user bandwidth monitoring tool for linux-based routers - Google Project Hosting
    http://code.google.com/p/wrtbwmon/
  - IPTables Bandwidth Monitor - Soft-hausWiki
    http://soft-haus.com/wiki/index.php5?title=IPTables_Bandwidth_Monitor
  - The OpenNMS Project
    http://www.opennms.org/

* [2011-12-08 Thu 14:04] Quicksilver scripting            :@mac:@quicksliver:
  - AppleScript Action template - Quicksilver Wiki
    http://qsapp.com/wiki/AppleScript_Action_template

* [2011-12-08 Thu 14:45] LaTeX Tutorial - YouTube                    :@latex:
  https://www.youtube.com/playlist?list=PLDD406480D35CE390

* [2011-12-08 Thu 15:04] GRC | Ultra High Security Password Generator :@online:@password:
  https://www.grc.com/passwords.htm

* [2011-12-09 Fri 12:51] YouTube video formats                     :@youtube:
  - YouTube - Wikipedia, the free encyclopedia
    http://en.wikipedia.org/wiki/YouTube#Quality_and_codecs

* [2011-12-09 Fri 15:48] Displaying notifications without Growl :@mac:@notifications:
  - cocoaDialog
    http://mstratman.github.com/cocoadialog/

* [2011-12-11 Sun] Using VLC as a media center on AppleTV     :@vlc:@appletv:
  - Mount a Remote Drive via SMBFS - AwkwardTV
    http://wiki.awkwardtv.org/wiki/Mount_a_Remote_Drive_via_SMBFS
  - Mount a Remote Drive via AFP under 1.1 - AwkwardTV
    http://wiki.awkwardtv.org/wiki/Mount_a_Remote_Drive_via_AFP_under_1.1
  - Mount external drive via SMB on AppleTV « Jiradett BLOG
    http://kerdsri.com/2010/01/13/mount-external-drive-via-smb-on-appletv/
  - Applications Menu - AwkwardTV
    http://wiki.awkwardtv.org/wiki/Applications_Menu
  - AwkwardTV Plugin Directory
    http://plugins.awkwardtv.org/det.php?recordID=applauncher

* [2011-12-13 Tue 12:24] find duplicate mails in maildir   :@maildir:@python:
  - maildir-deduplicate.py at master from kdeldycke/scripts - GitHub
    https://github.com/kdeldycke/scripts/blob/master/maildir-deduplicate.py

* [2011-12-15 Thu 10:47] Progess for pipes                :@linux:@scripting:
  - ivarch.com: Pipe Viewer
    http://www.ivarch.com/programs/pv.shtml

* [2011-12-15 Thu 10:48] Execute scripts on entering directory :@linux:@scripting:
  - OnDir - SwapOff
    http://swapoff.org/ondir.html
  - mikas blog » Blog Archive » Directory specific shell configuration with Zsh
    http://michael-prokop.at/blog/2009/05/30/directory-specific-shell-configuration-with-zsh/

* [2011-12-15 Thu] Emacs as a Python IDE                     :@emacs:@python:
  - Configuring Emacs as a Python IDE | Pedro Kroger
    http://pedrokroger.com/2010/07/configuring-emacs-as-a-python-ide-2/
  - IPython: Productive Interactive Computing — IPython
    http://ipython.org/
  - EnigmaCurry
    http://www.enigmacurry.com/2008/05/09/emacs-as-a-powerful-python-ide/
  - Setup Perfect Python Environment In Emacs « The website of Lei Chen
    http://hide1713.wordpress.com/2009/01/30/setup-perfect-python-environment-in-emacs/
  - rope python refactoring library
    http://rope.sourceforge.net/
    - ropemacs, rope in emacs
      http://rope.sourceforge.net/ropemacs.html
    - agr / ropemacs / overview — Bitbucket
      https://bitbucket.org/agr/ropemacs
    - Using Rope As A Library
      http://rope.sourceforge.net/library.html
  - pinard/Pymacs - GitHub
    https://github.com/pinard/Pymacs

* [2011-12-25 Sun] Some pedalboard links                :@guitar:@pedalboard:
  - Bottom Plate For Small Bear 125-B, BOSS, Ibanez
    http://www.smallbearelec.com/Detail.bok?no=973
  - Dual Lock Reclosable Fasteners - 3M US
    http://solutions.3m.com/wps/portal/3M/en_US/3M-Industrial/Adhesives/Promotions-New-Products/Reclosable-Fasteners/

* [2012-01-03 Tue 10:31] Scripting ffmpeg with python :@dev:@scripting:@video:
  - pyffmpeg - Python FFmpeg wrapper - Google Project Hosting
    http://code.google.com/p/pyffmpeg/
  - ffvideo - A python wrapper around ffmpeg - Google Project Hosting
    http://code.google.com/p/ffvideo/
  - PyMedia - Python module for avi, mp3, dvd, wma, ogg processing - pymedia
    http://pymedia.org/faq.html
  - »Using ffmpeg in Python« by David Murmann — thefoundation.de
    http://www.thefoundation.de/david/2008/sep/11/using-ffmpeg-python/

* [2012-01-03 Tue 16:40] Podcatchers                              :@podcasts:
  - Podracer - The winner of the pod race - Home
    http://podracer.sourceforge.net/
  - BashPodder - the best podcatcher
    http://lincgeek.org/bashpodder/
  - Armangil's podcatcher
    http://podcatcher.rubyforge.org/
  - Podget: A Simple Podcast Aggregator.
    http://podget.sourceforge.net/
  - grabpod
    http://jbaber.freeshell.org/scripts/grabpod/
  - Software Gubbins by Matthew Gates
    http://porpoisehead.net/mysw/index.php?pgid=mpodder
  - GoldenPod
    http://random.zerodogg.org/goldenpod

* [2012-01-04 Wed 11:19] Time machine for Windows     :@windows:@timemachine:
  - Genie9 (Formerly Genie-soft) Free Timeline | Download Free Backup Software for Windows
    http://www.genie9.com/Free_products/free_timeline.aspx
  - Time Machine for Windows - Altaro Oops!Backup
    http://www.altaro.com/home-pc-backup/index.php
  - Windows Backup Software - Continuous Data Protection - Like a Time Machine for Windows
    http://rebit.com/products/rebit/

* [2012-01-04 Wed 17:10] Bash initialization notes                    :@bash:
  - Bash: about .bashrc, .bash_profile, .profile, /etc/profile, etc/bash.bashrc and others | Stefaan Lippens' webface
    http://stefaanlippens.net/bashrc_and_others
  - .bash_profile vs .bashrc
    http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html
  - Execution sequence for .bash_profile, .bashrc, .bash_login, .profile and .bash_logout
    http://www.thegeekstuff.com/2008/10/execution-sequence-for-bash_profile-bashrc-bash_login-profile-and-bash_logout/

* [2012-01-05 Thu 10:00] Vector editing tools                   :@svg:@ctrlr:
  - Delineate - raster to SVG converter
    http://delineate.sourceforge.net/index.html
  - sK1 Project
    http://sk1project.org/
  - Skencil, a vector drawing program
    http://www.skencil.org/
  - Intaglio — Macintosh Drawing & Illustration
    http://www.purgatorydesign.com/Intaglio/
  - Freeverse: Mac: Games & Apps: Lineform
    http://www.freeverse.com/mac/product/?id=6020
  - Synfig Studio :: Home
    http://www.synfig.org/cms/

* [2012-01-05 Thu 11:48] Download Tou.tv videos     :@download:@flash:@video:
  - Accès à tou.tv à partir d’un Système libre
    http://store-it.appspot.com/tou/tou.html
  - Unable to play RTMP files off Tou.TV. Are they RTMPE? - Audio/video stream recording forums
    http://stream-recorder.com/forum/unable-play-rtmp-files-off-tou-tv-t5883.html
  - get-flash-videos - A command line program to download flash videos - Google Project Hosting
    http://code.google.com/p/get-flash-videos/
  - Installation - get-flash-videos - How to install get_flash_videos - A command line program to download flash videos - Google Project Hosting
    http://code.google.com/p/get-flash-videos/wiki/Installation
  - Tou.pm - get-flash-videos - A command line program to download flash videos - Google Project Hosting
    http://code.google.com/p/get-flash-videos/source/browse/trunk/FlashVideo/Site/Tou.pm?r=364

* [2012-01-12 Thu 12:57] IP TV tuner                           :@htpc:@tuner:
  - HDHomeRun (US/CA) | Welcome to SiliconDust
    http://www.silicondust.com/products/hdhomerun/atsc/

* [2012-02-25 Sat] Packaging python scripts                    :@dev:@python:
  - PyInstaller
    http://www.pyinstaller.org/
  - py2app - Create standalone Mac OS X applications with Python
    http://svn.pythonmac.org/py2app/py2app/trunk/doc/index.html

* [2012-01-12 Thu 14:23] Python regexp checking              :@python:@regex:
  - Python Regex Tool
    http://www.pythonregex.com/
  - c THE dot retest - regular expression tester for Python
    http://cthedot.de/retest/

* [2012-01-20 Fri 16:32] Mail processing in python    :@script:@python:@mail:
  - 18.4. mailbox — Manipulate mailboxes in various formats — Python v2.7.2 documentation
    http://docs.python.org/library/mailbox.html
  - Processing Mailbox Files with mailbox.py - O'Reilly Media
    http://onlamp.com/pub/a/python/2007/06/28/processing-mailbox-files-with-mailboxpy.html
  - Processing Mailbox Files with mailbox.py - O'Reilly Media
    http://onlamp.com/pub/a/python/2007/06/28/processing-mailbox-files-with-mailboxpy.html?page=2
  - Processing Mailbox Files with mailbox.py - O'Reilly Media
    http://onlamp.com/pub/a/python/2007/06/28/processing-mailbox-files-with-mailboxpy.html?page=3

* [2012-01-24 Tue 13:55] Time management in plain text :@timemanagement:@plaintext:
  - Clocking Time with Emacs Org | sacha chua :: living an awesome life
    http://sachachua.com/blog/2007/12/clocking-time-with-emacs-org/
  - Org Mode - Organize Your Life In Plain Text!
    http://doc.norang.ca/org-mode.html#ClockSetup
  - kisom/timecard - GitHub
    https://github.com/kisom/timecard

* [2012-01-24 Tue 14:00] org-mode blogging        :@emacs:@orgmode:@blogging:
   - Org Blogs and Wikis
     http://orgmode.org/worg/org-blog-wiki.html
   - Quick start Guide
     http://renard.github.com/o-blog/
   - Using org to Blog with Jekyll
     http://orgmode.org/worg/org-tutorials/org-jekyll.html

* [2012-01-27 Fri 11:52] Emacs tips from Phil Hagelberg              :@emacs:
  - An interview with Phil Hagelberg
    http://phil.hagelberg.usesthis.com/
  - ELIM - Summary [Savannah]
    http://savannah.nongnu.org/projects/elim
  - EmacsWiki: ELIM
    http://www.emacswiki.org/emacs/ELIM
  - technomancy/scpaste - GitHub
    https://github.com/technomancy/scpaste
  - technomancy/erythrina - GitHub
    https://github.com/technomancy/erythrina

* [2012-02-23 Thu 12:05] Mail filtering        :@dovecot:@mailfilter:@incron:
  Refiltering mail when received in a folder. Some incron tips as well.
 - HowTo/RefilterMail - Dovecot Wiki
   http://wiki.dovecot.org/HowTo/RefilterMail
 - LDA - Dovecot Wiki
   http://wiki.dovecot.org/LDA
 - LDA/Sieve - Dovecot Wiki
   http://wiki.dovecot.org/LDA/Sieve#Plus_Addressed_mail_filtering

* [2012-02-24 Fri 10:27] xpra                                     :@linux:@x:
  [[http://xpra.org/][Xpra]] is 'screen for X': it allows you to run X programs, usually on
  a remote host, direct their display to your local machine, and then
  to disconnect from these programs and reconnect from the same or
  another machine, without losing any state.

* [2012-03-23 Fri] org/markdown/static blog notes :@org:@markdown:@staticblog:
  - Re: [O] embed markdown?
    http://lists.gnu.org/archive/html/emacs-orgmode/2011-03/msg00637.html
  - github/markup
    https://github.com/github/markup
  - Pandoc - About pandoc
    http://johnmacfarlane.net/pandoc/
  - A new Hyde?
    https://github.com/hyde/hyde
** NEXT [#A] Investigate this - Org-mode to Jekyll
   :PROPERTIES:
   :ID:       2644f6d5-bc47-4037-ba2a-725ec5b39c6d
   :END:
   - org-jekyll, export blog posts from org-mode
     http://juanreyero.com/open/org-jekyll/
   - juanre/org-jekyll
     https://github.com/juanre/org-jekyll
   - Using org to Blog with Jekyll
     http://orgmode.org/worg/org-tutorials/org-jekyll.html
   - mojombo/jekyll
     https://github.com/mojombo/jekyll
** NEXT [#A] Investigate
   :LOGBOOK:
   - State "NEXT"       from "CANCELLED"  [2012-04-03 Tue 17:46]
   - State "CANCELLED"  from "NEXT"       [2012-04-02 Mon 16:41] \\
     Old version of Hyde. See [[file:links.org::*%5B2012-04-02%20Mon%5D%20Hyde%20notes%20and%20examples][{2012-04-02 Mon} Hyde notes and examples]]
   :END:
   :PROPERTIES:
   :ID:       c4479868-a2d3-4384-b912-2aad50726798
   :END:
  - punchagan/blog-files
    https://github.com/punchagan/blog-files
  - Rustic Reverie: WP to org-mode + hyde + disqus
    http://punchagan.muse-amuse.in/blog/wp-to-org-mode-hyde-disqus
  - punchagan/org-hyde
    https://github.com/punchagan/org-hyde


* [2012-03-28 Wed] MAX-based iPad controller                :@max:@ipad:@osc:
  - preview of a new multitouch iPad OSC controller, used to play the
    ag.granular.suite on Vimeo
    http://vimeo.com/27190010
  - Jamoma.org
    http://jamoma.org/
  - Software - ag.granular.suite for Max/MSP
    http://www.audibledata.com/Software.html

* NEXT [#A] [2012-03-29 Thu] Installing meld on Mac OS X             :@macos:
  :PROPERTIES:
  :ID:       ff47397d-9e16-4c8e-b751-b537a419165d
  :END:
  - How to install meld in Mac OS X Lion
    http://scoobygalletas.blogspot.ca/2011/09/how-to-install-meld-in-mac-os-x-lion.html

* [2012-04-02 Mon] Static CMS generator                :@python:@static:@cms:
   - AYM CMS
     http://aymcms.com/

* CANCELLED [#A] [2012-04-02 Mon] Hyde notes and examples :@python@hyde:@prt:@blog:
  :LOGBOOK:
  - State "CANCELLED"  from "NEXT"       [2012-04-03 Tue 17:45] \\
    Turns out that the "other" hyde may be better...
  - State "NEXT"       from ""           [2012-04-02 Mon 16:42]
  :END:
   - Hyde Starter Kit | About
     http://merlin.rebrovic.net/hyde-starter-kit/about.html
   - Overview
     http://hyde.github.com/
   - Overview
     http://hyde.github.com/
   - hyde/hyde
     https://github.com/hyde/hyde
   - hyde/hyde-mode
     https://github.com/hyde/hyde-mode
   - auzigog/hyde-bootstrap
     https://github.com/auzigog/hyde-bootstrap
   - Hyde Powered · hyde/hyde Wiki
     https://github.com/hyde/hyde/wiki/Hyde-Powered
   - latest entries - aleph.nu
     http://aleph.nu/
   - idank / site / source — Bitbucket
     https://bitbucket.org/idank/site/src
   - Adam's Blog » Blog Archive » Website Overhaul UpdateHyde research/examples/deployment
     http://www.adamtindale.com/blog/uncategorized/145/
   - jd's homepage | Julien Danjou
     http://julien.danjou.info/

* [2012-04-16 Mon] File tagging for Linux / universal              :@tagging:
  - What's a good solution for file-tagging in linux? - Super User
   http://superuser.com/questions/81563/whats-a-good-solution-for-file-tagging-in-linux/97245#97245
  - Talking Point: Could Linux Abandon Directories In Favour Of Tagging? | Linux Journal
    http://www.linuxjournal.com/content/talking-point-could-linux-abandon-directories-favour-tagging
  - www.tagsistant.net
    http://www.tagsistant.net/
  - TMSU
    http://tmsu.org/

* [2012-04-17 Tue 12:15] Scripting window manager           :@script:@window:
  - [[http://www.burtonini.com/blog/computers/devilspie][Devil's Pie]]
    - [[http://www.foosel.org/linux/devilspie][Devil's Pie documentation]]]
    - [[http://live.gnome.org/DevilsPie][DevilsPie Help]]
  - [[http://tomas.styblo.name/wmctrl/][wmctrl]] A command line tool to interact with an EWMH/NetWM
    compatible X Window Manager.
    - [[http://www.joeldare.com/wiki/linux:resize_a_window_with_the_wmctrl_command][Resize a Window with the wmctrl Command - Joel Dare]]
    - [[http://spiralofhope.com/wmctrl-examples.html][wmctrl-examples]]
  - [[http://code.google.com/p/wmectrl/][wmectrl]] - An enhanced window manager control.
  - [[http://code.google.com/p/xctrl/][xctrl]] - Shared library to control an X11 window manager. 
  - [[http://melp.nl/2011/01/10-must-have-key-and-mouse-binding-configs-in-openbox/][10 must-have key and mouse binding configs in Openbox]]

* [2012-04-17 Tue 14:17] Backpack                    :@laptop:@backpack:@bag:
  - [[http://www.chromebagsstore.com/bags/laptop-bags/soyuz.html][Soyuz - Laptop Bags - Bags | CHROME | Official Site]]
  - [[http://www.booqbags.com/laptop-backpacks-laptop-bags/15-inch-macbook-pro-bags/Mamba-shift-M-denim][Laptop Backpacks by booq - Mamba-shift-M-denim]]
  - [[http://www.tombihn.com/page/001/PROD/300/TB0103][The Smart Alec Backpack is cooler than you. Even cooler than: TOM BIHN]]
  - [[http://www.timbuk2.com/tb2/custom#/features/13][Timbuk2 - Build Your Own Bag - Choose Your Bag]]
  - [[http://www.rickshawbags.com/customize/custom-bag/fabric_selection/skinny-commuter-backpack#!cordura-steel/cordura-foliage/label-turquoise][Skinny Commuter Backpack | Rickshaw Bag Customizer]]
    - Detachable key ring, usable for USB key
    - Ordered - [2012-04-18 Wed]

* [2012-04-26 Thu] Running foobar2000 on Linux/Mac        :@wine:@foobar2000:
  - foobar2000 for Mac OS X - Hydrogenaudio Forums
    http://www.hydrogenaudio.org/forums/index.php?showtopic=77261
  - WineBottler - Run Windows Programs directly on OS X
    http://winebottler.kronenberg.org/
  - Running Foobar in Linux - Hydrogenaudio Forums
    http://www.hydrogenaudio.org/forums/index.php?showtopic=54933
  - polishlinux.org » Foobar2000 under Wine in Ubuntu
    http://polishlinux.org/apps/multimedia/foobar2000-under-wine-in-ubuntu/
  - wine osx - Google Search
    https://www.google.com/search?q=wine+osx
  - MacOSX/Installing - The Official Wine Wiki
    http://wiki.winehq.org/MacOSX/Installing
  - Wineskin, Play your favorite Windows games on Mac OS X without needing Microsoft Windows
    http://wineskin.doh123.com/
  - Home - PlayOnMac - Run your Windows applications on Mac easily!
    http://www.playonmac.com/en

* [2012-05-02 Wed] Graphics engines                          :@dev:@graphics:
   - cairographics.org
     http://www.cairographics.org/
   - Anti-Grain Geometry -
     http://www.antigrain.com/

* [2012-05-02 Wed] Using org-mode as an agenda - notifications  :@emacs:@org:
   - orgmode.org/w/?p=org-mode.git;a=blob_plain;f=contrib/lisp/org-notify.el;hb=HEAD
     http://orgmode.org/w/?p=org-mode.git;a=blob_plain;f=contrib/lisp/org-notify.el;hb=HEAD
   - Org-mode Frequently Asked Questions
     http://orgmode.org/worg/org-faq.html
   - todo items and email
     http://thread.gmane.org/gmane.emacs.orgmode/6112
   - automatic reminders in Emacs as pop ups was: Re: Survey results
     http://article.gmane.org/gmane.emacs.orgmode/5271
   - EmacsWiki: Appointment Mode
     http://www.emacswiki.org/emacs/AppointmentMode
   - EmacsWiki: Diary Mode
     http://www.emacswiki.org/emacs/DiaryMode
   - emacs-fu: showing pop-ups
     http://emacs-fu.blogspot.ca/2009/11/showing-pop-ups.html

* [2012-05-03 Thu] Textastic                           :@ipad:@tobuy:@bought:
  - [[http://www.textasticapp.com/][Textastic - Text, Code and Markup Editor with Syntax Highlighting - FTP, SFTP, Dropbox - for iPad]]
  - [[http://itunes.apple.com/gb/app/textastic-code-editor/id383577124?mt][http://www.textasticapp.com/]]

* [2012-07-05 Thu] Parcel re-mailing sevices from US             :@remailing:
  - [[http://www.shipito.com/][Shipito - USA Address & Mail Forwarding]]
    Seems to be the favorite and cheapest.
  - [[http://www.myus.com/][MyUS.com]]
  - [[http://myusaddress.ca/][MyUSAddress.ca]]
  - [[http://www.reship.com/?gclid=CJWAwsOug7ECFekZQgod9DTJZA][Reship.com]]

* [2012-08-11 Sat] emacs and python                          :@emacs:@python:
  - [[http://jesselegg.com/archives/2010/03/14/emacs-python-programmers-2-virtualenv-ipython-daemon-mode/][Emacs for Python Programmers #2: Virtualenv, IPython & Daemon Mode | JesseLegg.com]]
  - [[http://stackoverflow.com/questions/304049/emacs-23-and-ipython][python - Emacs 23 and iPython - Stack Overflow]]
  - [[http://sunnyeves.blogspot.ca/2011/04/debugging-python-on-emacs-ide.html][An Engineer's Options & Futures: Debugging Python on Emacs IDE]]
  - [[http://page.sourceforge.net/tricks.html][Python Tricks]]
  - [[http://pythonconquerstheuniverse.wordpress.com/2009/09/10/debugging-in-python/][Debugging in Python « Python Conquers The Universe]]
  - [[http://bashdb.sourceforge.net/pydb/][Pydb - Extended Python Debugger]]
  - [[http://code.google.com/p/pydbgr/][pydbgr - Modular Python Debugger - Google Project Hosting]]

* [2012-08-11 Sat] Amazon and python                        :@amazon:@python:
  - [[http://pypi.python.org/pypi/python-amazon-product-api][python-amazon-product-api 0.2.5 : Python Package Index]]
  - [[http://stackoverflow.com/questions/4589813/amazon-book-api-for-python-or-ruby][Amazon Book API for Python or Ruby? - Stack Overflow]]

* [2012-08-11 Sat] LoopDelay Max for Live device                :@maxforlive:
  - [[http://www.maxforlive.com/library/device/1150/loopdelay][LoopDelay]] a live looping and pitchshifting plugin. The loop can be
    reversed, pitched and modulated by two sinewaves which can result in
    frequency modulated granular screeches of subtle stutter effects.
    The audiobuffer can be constantly refreshed or locked. Bufferlength
    in sync with BPM or choose milliseconds. Also you can scroll through
    the buffer with your mouse or of course through plain and simple
    automation.

* [2012-08-11 Sat] Making fractals                     :@art:@fractal:@image:
  - [[http://fractalarchitect.net/][Fractal Architect 2 - Flame Fractal Designer & Editor for Mac OS X]]

* [2012-08-11 Sat] Handle MTP device without Windoze                   :@mtp:
  - [[http://sourceforge.net/projects/playedit/][MTP Playlist Editor | Free Audio & Video software downloads at SourceForge.net]]
  - [[http://www.linux-magazine.com/Issues/2009/104/MTP-in-Linux][MTP in Linux - Linux Magazine Online]]

* [2012-08-11 Sat] Remux mkv files to mp4                       :@video:@mp4:
  - [[http://code.google.com/p/mkvtomp4/][mkvtomp4 - Convert H.264 mkv files (without re-encoding the video) to mp4 files playable on the PS3 - Google Project Hosting]]

* [2012-08-11 Sat] One-liner for-loop in bash            :@commandline:@bash:
  - [[http://penguinpetes.com/b2evo/index.php?p=215][Penguin Pete's Blog - How the One-Liner For-Loop in Bash Goes]]
    : for FILE in *; do [COMMAND using $FILE]; done

* [2012-08-13 Mon 13:51] Making my own YubNub          :@python:@web:@yubnub:
  - [[http://bottlepy.org/docs/dev/][Bottle: Python Web Framework — Bottle 0.11.dev documentation]]
  - [[http://blog.coderonfire.com/running-bottle-python-micro-framework-on-drea][Running Bottle Python Micro-Framework on Dreamhost - Coder on Fire. Blog]]
  - [[http://hitesh.in/2011/running-a-bottle-py-app-on-dreamhost/][Running a bottle.py app on Dreamhost | Hitesh Sarda]]
  - [[http://wiki.dreamhost.com/Flask][Flask - DreamHost]]
    Applies to running bottle as well. Helps with virtualenv setup.
  - [[http://code.activestate.com/recipes/475148-fuzzy-matching-dictionary/][Fuzzy matching dictionary « Python recipes « ActiveState Code]]

* [2012-08-24 Fri] Writing bookmarklets         :@dev:@bookmarklet:@workflow:
  - [[http://teamtreehouse.com/blog/creating-bookmarklets-for-fun-and-profit][Creating Bookmarklets for Fun and Profit | Treehouse BlogTreehouse Blog]]
  - [[http://coding.smashingmagazine.com/2010/05/23/make-your-own-bookmarklets-with-jquery/][Make Your Own Bookmarklets With jQuery | Smashing Coding]]
  - [[http://betterexplained.com/articles/how-to-make-a-bookmarklet-for-your-web-application/][How To Make a Bookmarklet For Your Web Application | BetterExplained]]
  - [[http://net.tutsplus.com/tutorials/javascript-ajax/create-bookmarklets-the-right-way/][How to Create Bookmarklets | Nettuts+]]
  - [[http://alexkehayias.tumblr.com/post/20526151518/how-to-make-an-interactive-bookmarklet-part-1][Alex Kehayias's Blog • How to make an interactive bookmarklet part 1]]
  - [[http://alexkehayias.tumblr.com/post/21324220210/how-to-make-an-interactive-bookmarklet-part-2][Alex Kehayias's Blog • How to make an interactive bookmarklet part 2]]
  - [[http://alexkehayias.tumblr.com/post/22191305271/how-to-make-an-interactive-bookmarklet-part-3][Alex Kehayias's Blog • How to make an interactive bookmarklet part 3]]

* [2012-09-14 Fri] Zooming presentations                      :@presentation:
  - [[http://prezi.com/][Prezi - The Zooming Presentation Editor]]
  - [[https://github.com/adityab/Awwation][adityab/Awwation]]
  - [[https://github.com/bartaz/impress.js][bartaz/impress.js]]
  - [[http://www.1stwebdesigner.com/css/creating-stunning-visualizations-with-impress-js/][Creating Stunning Visualizations With Impress.js]]
  - [[https://github.com/hsivaramx/Impressionist][hsivaramx/Impressionist]]
  - [[https://github.com/kinjo/org-impress-js.el][kinjo/org-impress-js.el]]
  - [[http://dontkry.com/jmpress.js/#/home][jmpress.js | a jQuery plugin to build a website on the infinite canvas]]
  - [[http://meyerweb.com/eric/tools/s5/][S5: A Simple Standards-Based Slide Show System]]
  - [[http://www.linuxforu.com/2010/05/s5-a-simple-web-based-slideshow-system/][S5: A Simple Web-based Presentation System - LINUX For You]]

* [2012-12-14 Fri 10:45] Recording internet radio            :@internetradio:
  - [[http://judsonsnotes.com/notes/index.php?option=com_content&view=article&id=591:recording-an-internet-audio-stream-automatically&catid=37:tech-notes&Itemid=59][Recording an internet audio stream automatically]]
  - [[http://blog.nguyenvq.com/2012/04/13/record-streaming-radio-with-streamripper/][Super Nerdy Cool » Record streaming radio with streamripper]]
  - [[http://www.sciencetext.com/recording-internet-radio-stream.html][Recording an Internet Radio Stream]]
  - [[http://crunchbang.org/forums/viewtopic.php?id=21471][How To rip your fav Web-Radio Station to mp3 from the commandline (Page 1) / Tips, Tricks & Scripts / CrunchBang Linux Forums]]
  - [[http://blog.tdobson.net/2012/11/how-to-script-the-recording-of-your-favourite-online-radio-show/][How to script the recording of your favourite online radio show « Tim Dobson]]
  - [[http://www.instructables.com/id/Schedule-Streaming-Audio-Recordings-in-Ubuntu/][Schedule Streaming Audio Recordings in Ubuntu]]

* [2013-01-23 Wed 15:17] More blogging from org-mode :@org:@jekyll:@blogging:
  - [[http://juanreyero.com/open/org-jekyll/][org-jekyll, export blog posts from org-mode]] 
    Extracts subtrees from your org-publish project files that have
    a :blog: keyword and an :on: property with a timestamp, and
    exports them to a subdirectory _posts of your project's publishing
    directory in the year-month-day-title.html format that Jekyll
    expects. Properties are passed over as yaml front-matter in the
    exported files. The title of the entry is the title of the
    subtree.
  - [[https://github.com/punchagan/org-hyde][punchagan/org-hyde · GitHub]]

* [2013-01-24 Thu 17:33] Using python to do shell scripting  :@python:@shell:
  - [[http://amoffat.github.com/sh/][sh 1.07 documentation]]
    Too cool!+

* [2013-01-24 Thu 17:39] Copy a file with progress in Python        :@python:
  - [[http://stackoverflow.com/questions/274493/how-to-copy-a-file-in-python-with-a-progress-bar][How to copy a file in Python with a progress bar? - Stack Overflow]]
    Not sure about reading and writing a whole big file in a python
    script, though. I trust things like rsync more...

* [2013-01-25 Fri 13:05] More small Linux computers                :@diy:@pi:
  - [[https://www.olimex.com/Products/OLinuXino/A13/A13-OLinuXino/][A13-OLinuXino]]
  - [[http://cubieboard.org/][Cubieboard | Open ARM Box]]
  - [[http://liliputing.com/2012/03/mele-a1000-is-a-70-hackable-linux-friendly-arm-based-pc.html][Mele A1000 is a $70 hackable, Linux-friendly ARM-based PC - Liliputing]]

* [2013-02-06 Wed] Notetaking on iPad                          :@ipad:@notes:
  - [[http://www.gingerlabs.com/cont/notability.php][Notability - Unleash Your Note Taking Ability.]]
  - [[http://readdle.com/products/remarks/][Readdle]]
  - [[http://mypaperdesk.com/][PaperDesk ● note beautifully]]
  - [[http://inotesapp.com/features][iNotes App ~ The best note taking experience on your iPad]]
  - [[http://leethibaultdev.com/?q=smartnote][smartNote for iPad | Mobile software development]]

* [2013-03-02 Sat] Subtitles in mp4 files                 :@video:@subtitles:
  - [[http://www.m4.com/blog/video/adding-burned-in-subtitles-to-your-ripped-movies/][Adding Burned-in Subtitles to Your Ripped Movies]]
  - [[http://pier.morel.perso.sfr.fr/subfix/english.html][Download SubFix]]  
  - [[http://www.bitfield.se/submerge/index.html][Submerge]]

* [2013-03-02 Sat] Streaming to AirTunes            :@audio:@music:@airtunes:
  - [[http://blogs.gnome.org/danni/2009/10/22/streaming-to-airtunes-airport-express-with-pulseaudio/][Streaming to Airtunes (Airport Express) with PulseAudio]]

* [2013-03-07 Thu 09:58] Working with subtitles on Linux :@subtitles:@video:@authoring:
  - [[http://archive09.linux.com/feature/125978][Subtitle manipulation tools for Linux]]
  - [[http://www.dedoimedo.com/computers/linux-subtitles.html][Working with subtitles (create, edit, embed) in Linux]]

* [2013-03-08 Fri] Compress movie volume                :@video:@compression:
  - [[http://lifehacker.com/5920290/how-to-fix-movies-that-are-really-quiet-then-really-loud][How to Fix Movies that Are Really Quiet, then REALLY LOUD]]

* [2013-03-08 Fri] Button class for iOS                           :@dev:@ios:
  - [[http://www.cocoacontrols.com/platforms/ios/controls/imageless-gradient-buttons][Imageless Gradient Buttons for iOS - Cocoa Controls]]

* [2013-03-08 Fri 07:09] UIButton tips                  :@dev:@ios:@uibutton:
  - [[http://robots.thoughtbot.com/post/33427366406/designing-for-ios-taming-uibutton][Designing for iOS: Taming UIButton]]
  - [[http://robots.thoughtbot.com/post/36591648724/designing-for-ios-graphics-performance][Designing for iOS: Graphics & Performance]]

* [2013-03-08 Fri 07:13] OSX Accessibility API     :@dev:@osx:@accessibility:
  - [[http://googlemac.blogspot.ca/2008/01/accessibilityfs-all-access-pass-to-your.html][Official Google Mac Blog: AccessibilityFS: An All-Access Pass to Your UI]]
  - [[https://developer.apple.com/library/mac/#documentation/Cocoa/Conceptual/Accessibility/cocoaAXIntro/cocoaAXintro.html][Accessibility Programming Guidelines for Mac: Introduction to Accessibility Programming Guidelines for Cocoa]]
  - [[http://stackoverflow.com/questions/5052266/accessibility-api-cocoa][objective c - Accessibility API - Cocoa - Stack Overflow]]
  - [[http://pfiddlesoft.com/uibrowser/][UI Browser]]
  - [[http://stackoverflow.com/questions/6836278/api-for-accessing-ui-elements-in-mac-os-x][osx - API for accessing UI elements in Mac OS X - Stack Overflow]]
  - [[http://developer.apple.com/library/mac/#samplecode/UIElementInspector/Introduction/Intro.html#//apple_ref/doc/uid/DTS10000728-Intro-DontLinkElementID_2][UIElementInspector]]

* [2013-03-08 Fri 12:28] Using Emacs for Objective-C :@development:@emacs:@objc:
  - [[http://thread.gmane.org/gmane.emacs.code-browser/1841][ECB with Objective C]]
  - [[http://alexott.net/en/writings/emacs-devenv/EmacsCedet.html][A Gentle introduction to CEDET]]
  - [[http://technyooz.blogspot.ca/2010/01/emacs-crash-course-and-tutorial.html][TechNyooz: Emacs ECB Crash Course and Tutorial]]
  - [[http://cxwangyi.wordpress.com/2010/08/21/using-cedet-with-emacs/][Using CEDET and ECB with Emacs | Yi Wang's Tech Notes]]
  - [[http://www.appsintheopen.com/articles/1-setting-up-emacs-for-rails-development/part/6-setting-up-the-emacs-code-browser][AppsInTheOpen]]
  - [[http://stackoverflow.com/questions/3509919/emacs-c-opening-corresponding-header-file][Emacs C++, opening corresponding header file - Stack Overflow]]
  - [[http://rawsyntax.com/blog/learn-emacs-fit-your-workflow/][Learn Emacs: Fit your Workflow - Raw Syntax]]

* [2013-03-15 Fri 14:22] LaTeX links                                 :@latex:
  - [[http://www.latextemplates.com/][LaTeX Templates]]
  - [[https://spandex.io/][SpanDeX - Dashboard]]
  - [[http://www.howtotex.com/templates/template-added-color-font-article/][LaTeX template of a modern article | howtoTeX.com - Your LaTeX resource site]]
  - [[http://www.howtotex.com/category/templates/][Templates | howtoTeX.com - Your LaTeX resource site]]
  - [[http://www.howtotex.com/general/a-guide-to-building-a-plain-and-simple-latex-cv/][A guide to building a plain and simple LaTeX CV | howtoTeX.com - Your LaTeX resource site]]
  - [[http://www.latex-community.org/viewtopic.php?f=5&t=1597][Modern Looking Latex Styles • General • LaTeX Community]]
  - [[https://groups.google.com/forum/?fromgroups=#!topic/comp.text.tex/fpXB2vrEf0E][Can I make a document that looks like this? - Google Groups]]
  - [[http://www.latex-community.org/know-how/429-latex-templates][LaTeX Templates]]
  - [[http://tex.stackexchange.com/questions/31473/theming-latex-documents][templates - Theming LaTeX documents - TeX - LaTeX]]
  - [[http://tex.stackexchange.com/questions/1319/showcase-of-beautiful-typography-done-in-tex-friends][big list - Showcase of beautiful typography done in TeX & friends - TeX - LaTeX]]
  - [[http://www.ctan.org/tex-archive/macros/latex/contrib/memoir/][CTAN: tex-archive/macros/latex/contrib/memoir/]]
  - [[http://texblog.org/tag/memoir/][memoir | LaTeX Matters]]
  - [[http://www.youtube.com/watch?feature=player_embedded&v=cFgjhXE7MZo#!][Introduction to memoir - YouTube]]
  - [[http://mrskrummel.com/tutorials][LaTeX Tutorials]]
  - [[http://www.xm1math.net/texmaker/][Texmaker (free cross-platform latex editor)]]

* [2013-03-28 Thu 14:55] From [[http://ergoemacs.org/emacs/emacs_dired_tips.html][Xah Lee]]                           :@emacs:blog:
  In a file, how to go to its directory and place cursor on the file
  name?  Use the command dired-jump 【Ctrl+x Ctrl+j】.

* [2013-04-04 Thu 11:41] "Clustered" Handbrake  :@video:@encoding:@handbrake:
  - [[http://revxatlarge.blogspot.ca/2011/10/clustered-handbrake-encoder.html][Revx At Large: Clustered Handbrake Encoder]]
  - [[https://code.google.com/p/clustered-handbrake/wiki/README][README - clustered-handbrake - A distributed system for farming out handbrake encoding tasks. - Google Project Hosting]]

* [2013-04-04 Thu 14:20] Use tmux instead of screen     :@linux:@shell:@tmux:
 - [[http://tmux.sourceforge.net/][tmux]]
 - [[http://blog.hawkhost.com/2010/06/28/tmux-the-terminal-multiplexer/][TMUX – The Terminal Multiplexer (Part 1) | Hawk Host Blog]]
 - [[http://blog.hawkhost.com/2010/07/02/tmux-%e2%80%93-the-terminal-multiplexer-part-2/][TMUX – The Terminal Multiplexer (Part 2) | Hawk Host Blog]]
 - [[https://mutelight.org/practical-tmux][Practical Tmux]]

* [2013-04-04 Thu 15:46] Sending growl notifications  :@growl:@python:
  - [[https://github.com/kfdm/gntp][kfdm/gntp · GitHub]]
  - [[http://pythonhosted.org/gntp/][GNTP Basics — Growl Notification Transport Protocol Python Bindings 1.0 documentation]]

* [2013-04-28 Sun 13:18] Audio file splitting and tagging :@audio:@music:@tagging:
  - [[http://www.commandlinefu.com/commands/view/2042/split-lossless-audio-ape-flac-wav-wv-by-cue-file][Split lossless audio (ape, flac, wav, wv) by cue file | commandlinefu.com]]
  - [[http://home.gna.org/lltag/howto][lltag - Automatic command-line mp3/ogg/flac file tagger and renamer - How-To?]]
  - [[http://www.cyberciti.biz/faq/linux-unix-bash-for-loop-one-line-command/][HowTo: Use bash For Loop In One Line]]
    : for i in *; do echo $i; done

* [2013-04-28 Sun 13:53] Movie trackers                     :@torrent:@movie:
  - [[http://lifehacker.com/5897095/whats-a-private-bittorrent-tracker-and-why-should-i-use-one][What's a Private BitTorrent Tracker, and Why Should I Use One?]]
  - [[http://filenetworks.blogspot.ca/search/label/Private%20Trackers][FILEnetworks Blog: Private Trackers]]
  - [[http://www.torrent-invites.com/bittorrent-discussion/222375-right-path-top-movie-trackers.html][The right path to the top movie trackers?]]
  - [[http://www.torrent-invites.com/tracker-reviews/][Tracker Reviews]]
  - [[http://www.torrent-invites.com/bittorrent-discussion/212426-best-movie-tracker-quantity-quality.html][Best movie tracker for Quantity/Quality?]]
  - [[http://www.torrent-invites.com/bittorrent-discussion/144925-best-movie-tracker-best-tv-tracker.html][Best movie tracker & Best TV tracker]]

* [2013-04-28 Sun 13:54] Convert iTunes URL to standard Podcast :@itunes:@podcasts:
  - [[http://picklemonkey.net/feedflipper-home/?https%3A%2F%2Fitunes.apple.com%2Fus%2Fpodcast%2Fechoes-feature-just-music%2Fid77320816%3Fi%3D127653748=https%3A%2F%2Fitunes.apple.com%2Fus%2Fpodcast%2Fechoes-feature-just-music%2Fid77320816%3Fi%3D127653748][Feed Flipper | picklemonkey.net]]

* [2013-04-28 Sun 13:55] Using the Amazon API with python :@dev:@python:@amazon:
  - [[http://stackoverflow.com/questions/12531612/how-to-get-book-cover-picture-through-amazon-api-using-python-code][How to get book cover picture through amazon API using python code? - Stack Overflow]]
  - [[http://stackoverflow.com/questions/4589813/amazon-book-api-for-python-or-ruby][Amazon Book API for Python or Ruby? - Stack Overflow]]
  - [[https://pypi.python.org/pypi/python-amazon-product-api/0.2.1][python-amazon-product-api 0.2.1 : Python Package Index]]
  - [[https://bitbucket.org/basti/python-amazon-product-api/wiki/Home][basti / python-amazon-product-api / wiki / Home — Bitbucket]]
  - [[https://github.com/aurorasoftware/bottlenose][aurorasoftware/bottlenose · GitHub]]
  - [[https://www.amazon.com/ap/signin?openid.assoc_handle=aws&openid.return_to=https%3A%2F%2Fportal.aws.amazon.com%2Fgp%2Faws%2FsecurityCredentials&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&action=&disableCorpSignUp=&clientContext=&marketPlaceId=&poolName=&authCookies=&pageId=aws.ssop&siteState=&accountStatusPolicy=P1&sso=&openid.pape.preferred_auth_policies=MultifactorPhysical&openid.pape.max_auth_age=600&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&server=%2Fap%2Fsignin%3Fie%3DUTF8&accountPoolAlias=&showIAMLink=0&forceMobileLayout=0][Amazon Web Services Sign In]]
  - [[http://stackoverflow.com/questions/4171733/sample-python-code-for-using-google-books-api][django - Sample python code for using Google books api - Stack Overflow]]
  - [[https://developers.google.com/books/docs/v1/using][Using the API - Google Books API Family — Google Developers]]

* [2013-04-28 Sun 13:59] Power Monitoring                            :@power:
  - [[http://www.p3international.com/products/special/p4400/p4400-ce.html][P3 - Kill A Watt]]
  - [[http://store.greengadgets.ca/products/P4400.html][P4400 - Kill-a-Watt Power Monitor]]

* [2013-05-07 Tue 20:11] Setting DISPLAY when connecting by ssh :@osx:@ssh:@x11:
  - [[http://apple.stackexchange.com/questions/80470/display-is-not-set-on-remote-host-when-i-do-ssh-from-mac-to-another-machine][mountain lion - DISPLAY is not set on remote host when I do ssh from mac to another machine - Ask Different]]

* [2013-05-12 Sun 18:29] Writing a résumé in LaTeX                   :@latex:
  - [[http://www.mcnabbs.org/andrew/linux/latexres/][Andrew McNabb]]
  - [[https://www.google.com/search?q=resume+using+latex][resume using latex - Google Search]]
  - [[http://texblog.org/2012/04/25/writing-a-cv-in-latex/][Writing a CV in LaTeX | texblog]]
  - [[http://www.wikihow.com/Write-a-Resume-in-LaTeX][6 Ways to Write a Resume in LaTeX - wikiHow]]
  - [[http://kyle.mathews2000.com/blog/2011/05/21/how-create-resume-using-latex][How to create a resume using Latex | KYLE MATHEWS]]
  - [[http://kjhealy.github.io/kjh-vita/][kjhealy/kjh-vita @ GitHub]]
  - [[https://github.com/kjhealy/kjh-vita][kjhealy/kjh-vita · GitHub]]
  - [[http://wiki.contextgarden.net/Main_Page][ConTeXt wiki]]
  - [[http://www.toofishes.net/blog/why-i-do-my-resume-latex/][toofishes.net - Why I do my résumé in LaTeX]]
  - [[http://www.thelinuxdaily.com/2008/10/latex-resume-examples/][LaTeX Resume Examples | The Linux Daily]]

* [2013-05-12 Sun 18:26] Blender / Mocap                    :@blender:@mocap:
  - [[http://cgcookie.com/blender/2010/05/13/game-enginecharacter-part-1/][Game Engine: Simple Character - Part 1 | Blender Cookie]]
  - [[http://wiki.blender.org/index.php/Doc:2.4/Manual/Game_Engine][Doc:2.4/Manual/Game Engine - BlenderWiki]]
  - [[http://www.ni-mate.com/][NI Mate]]
  - [[http://animata.kibu.hu/][Animata]]
 
* [2013-05-12 Sun 18:30] GeekTool calendar                        :@geektool:
  - [[http://www.macosxtips.co.uk/geeklets/system/calendar-with-colored-day/][Calendar with colored day | Geeklets]]
  - [[http://pastebin.com/f56e5608f][[PHP] dvil88 - Pastebin.com]]
  - [[http://forums.macrumors.com/showthread.php?t=925333][Geektool Calendar issue - MacRumors Forums]]
  - [[http://forums.macrumors.com/showpost.php?p=10501085&postcount=2177][MacRumors Forums - View Single Post - [Geektool] Your Geektool scripts]]
  - [[http://forums.macrumors.com/showpost.php?p=10785954&postcount=2258][MacRumors Forums - View Single Post - [Geektool] Your Geektool scripts]]
  - [[http://macgenius.co/apps/a-beginners-guide-to-running-geektool-on-lion/][A Beginners Guide to Running GeekTool on Lion | Mac Genius]]

* [2013-05-13 Mon 14:39] Installing a local version of srchcmd
  - [[http://fclef.wordpress.com/2013/01/12/bottle-virtualenv-uwsgi-nginx-installation-on-ubuntu-12-04-1-lts/][Python Bottle+virtualenv+uWSGI+Nginx installation on Ubuntu 12.04.1 LTS | Sean Wang's territory]]

* [2013-05-14 Tue 07:06] Verifying WPS deactivation       :@network:@hacking:
  - [[http://backtrack4beginners.blogspot.ca/2012/09/5-hacking-wpa2-with-wps-bruteforcing.html][Backtrack from begginer to advanced: # 5 Hacking WPA2 (With WPS Bruteforcing)]]

* [2013-05-15 Wed 15:54] European Usenet Providers                  :@usenet:
  - [[http://www.ngprovider.com/euro-based-usenet-providers.php][European (Dutch) Usenet Servers]]
  - [[https://www.tweaknews.eu/][TweakNews - Home - Free - Basic - Fast - Ultimate]]
  - [[https://www.ssl-news.info/signup.php?][SSL NEWS - Shop]]
  - [[http://new.xsnews.com/index.php/en/products/details/elite][XS News || products]]
  - [[http://www.xlned.com/][XLned - Usenet for everyone]]

* [2013-05-15 Wed 15:56] Anonymous surfing / torrenting  :@anonymous:@vpn:@torrent:
  - [[http://linuxpoison.blogspot.ca/2011/09/anonymous-web-surfing-using-tor-ubuntu.html][Anonymous web surfing using TOR - Ubuntu Linux | Linux Blog]]
  - [[http://askubuntu.com/questions/37412/how-can-i-insure-transmission-traffic-uses-a-vpn][server - How can I insure transmission traffic uses a VPN? - Ask Ubuntu]]
  - [[https://forum.transmissionbt.com/viewtopic.php?f=4&t=11452][Transmission • View topic - HowTo: Bind to a specific network interface]]

* [2013-05-17 Fri 08:15] Songs for Optikal Illusion reunion
  - [[http://www.youtube.com/watch?v=IBH97ma9YiI][Radiohead - Karma Police - YouTube]]
  - [[http://tabs.ultimate-guitar.com/r/radiohead/karma_police_tab.htm][Karma Police Tab by Radiohead @ Ultimate-Guitar.Com]]
  - [[http://www.youtube.com/watch?v=8MR9OH6BjOo][Red Hot Chili Peppers - Dani California - YouTube]]
  - [[http://tabs.ultimate-guitar.com/r/red_hot_chili_peppers/dani_california_ver3_tab.htm][Dani California Tab (ver 3) by Red Hot Chili Peppers @ Ultimate-Guitar.Com]]

* [2013-05-17 Fri 10:32] Objective-C command line parsing :@dev:@objc:@cmdline:
  - [[http://unixjunkie.blogspot.ca/2006/07/command-line-processing-in-cocoa.html][Unixjunkie Blog: Command Line Processing in Cocoa]]
  - [[http://perspx.com/archives/parsing-command-line-arguments-nsuserdefaults/][Parsing command line arguments with NSUserDefaults | Perspx]]
  - [[http://yken.org/2009/01/14/parsing-the-command-line-in-objective-c/][Parsing the command line in Objective-C | yken.org]]
  - [[http://www.dribin.org/dave/software/ddcli/api/][ddcli: ddcli: An Objective-C Command Line Helper]]
  - [[https://github.com/tomaz/GBCli][tomaz/GBCli · GitHub]]

* [2013-05-17 Fri 13:32] CoreMIDI and IAC                    :@dev:@coremidi:
  - [[http://xmidi.com/how-to-access-midi-devices-with-coremidi/][How to access MIDI devices with CoreMIDI » XMIDI]]

* [2013-06-07 Fri 14:07] Ambient playlist          :@youtube:@ambient:@music:
  - [[http://www.youtube.com/watch?v=bFep_qy9da0][PTARKH : Razval - YouTube]]
  - [[http://www.youtube.com/watch?v=OiHjceyENz4][Dark Ambient Playlist - YouTube]]
  - [[http://www.youtube.com/user/cryochamberlabel][cryochamberlabel - YouTube]]
  - [[http://cryochamber.bandcamp.com/][Cryo Chamber]]
  - [[http://www.youtube.com/watch?v=hctYB7Lpppo][Ambient Space music Julien H Mulder - Fragments "NOW AVAILABLE ON BANDCAMP" - YouTube]]
  - [[https://www.youtube.com/watch?v=RRWnRfd8aRc][Klaus Schulze - Kontinuum - YouTube]]
  - [[http://www.youtube.com/watch?v=RvOkZ8aYJs4][Klaus Schulze - Into The Blue - YouTube]]
  - [[http://blog.hos.com/2013/05/jeff-pearce-and-robert-rich-ambicon-concerts-on-youtube.html][Jeff Pearce and Robert Rich AMBIcon concerts on YouTube - hearts of space | news]]
  - [[http://www.youtube.com/watch?feature=player_embedded&v=jbgZ9n1PToo][AMBIcon 2013: JEFF PEARCE Full Concert (Production Video) - YouTube]]

* [2013-07-08 Mon 15:28] European Usenet servers                    :@usenet:
  - [[http://www.sunnyusenet.com/][Goedkoopste Usenet provider! Nummer 1 payserver | Sunny Usenet]]
  - [[http://www.thundernews.com/][ThunderNews]]
  - [[https://www.ssl-news.info/index.php][SSL NEWS - Home]]
  - [[http://www.ngprovider.com/euro-based-usenet-providers.php][European (Dutch) Usenet Servers]]
  - [[http://www.newsgrabber.nl/?page_id=5][Newsgrabber.nl Usenet Provider]]
  - [[https://www.eweka.nl/][Eweka Internet Services]]
  - [[http://www.newsgroupdirect.com/signup/][Pricing and Signup : NewsgroupDirect High Speed Usenet Newsgroups]]
  - [[http://www.xlned.com/][XLned - Usenet for everyone]]

* [2013-07-08 Mon 15:31] SpotWeb notes                     :@usenet:@spotweb:
  - [[https://github.com/spotweb/spotweb][spotweb/spotweb · GitHub]]
  - [[http://en.wikipedia.org/wiki/Spotnet][Spotnet - Wikipedia, the free encyclopedia]]
  - [[https://www.google.com/search?q=Spotlite][Spotlite - Google Search]]
  - [[http://www.binaries4all.com/spotlite/][SpotLite 2.0 tutorial (FTD alternative) | Binaries4all Usenet Tutorials]]
  - [[http://www.binaries4all.com/spotnet/][What is Spotnet? | Binaries4all Usenet Tutorials]]
  - [[http://www.binaries4all.com/spotlite/configuratie.php][SpotLite - Configuration | Binaries4all Usenet Tutorials]]
  - [[https://github.com/spotweb/spotweb/wiki][Home · spotweb/spotweb Wiki · GitHub]]
  - [[https://github.com/spotweb/spotweb/wiki/Configuring-NZB-handling][Configuring NZB handling · spotweb/spotweb Wiki · GitHub]]
  - [[https://github.com/spotweb/spotweb/wiki/Install-Spotweb-on-Ubuntu-12.04-LTS-%28Precise-Pangolin%29-%28english%29][Install Spotweb on Ubuntu 12.04 LTS (Precise Pangolin) (english) · spotweb/spotweb Wiki · GitHub]]
  - [[https://github.com/spotweb/spotweb/wiki][Home · spotweb/spotweb Wiki · GitHub]]

* [2013-07-08 Mon 15:33] Making a floating window in Max/Max for live  :@max:
  - [[http://cycling74.com/forums/topic/floating-window-2/][Topic: Floating Window? « Cycling 74]]

* [2013-07-08 Mon 15:34] Bookmark management notes               :@bookmarks:
  - [[https://github.com/Newky/PocketPy/blob/master/bin/operators.py][PocketPy/bin/operators.py at master · Newky/PocketPy · GitHub]]
  - [[https://www.google.com/search?q=python%20print%20dictionary%20keys#sclient=psy-ab&q=python%20delicious%20api&oq=&gs_l=&pbx=1&fp=93b6a10721ad7089&biw=1138&bih=816&pf=p&pdl=300&bav=on.2,or.r_cp.r_qf.&cad=b&sei=yOjVUemYAuOlyAGYtIHoCA][python delicious api - Google Search]]
  - [[https://github.com/mudge/python-delicious][mudge/python-delicious · GitHub]]
  - [[http://www.dzone.com/snippets/delicious-api-python][Del.icio.us API With Python | DZone]]
  - [[https://code.google.com/p/pydelicious/][pydelicious - pydelicious: from del.icio.us to Python - Google Project Hosting]]
  - [[https://www.google.com/search?q=deliciouspython][deliciouspython - Google Search]]
  - [[http://seb.so/readitlater-to-delicious-export-converter/][How to import your ReadItLater items into Delicious (python converter) - Seb Maynard :: seb.so]]
  - [[https://www.google.com/search?q=delicious%20api][delicious api - Google Search]]
  - [[https://www.google.com/search?q=delicious%20api%20add][delicious api add - Google Search]]
  - [[https://delicious.com/developers/rssurls][Developers – Delicious]]
  - [[http://txt.binnyva.com/2009/06/post-to-delicious-from-command-line/][txt » Post to Delicious From Command Line]]
  - [[http://superuser.com/questions/395664/how-to-use-delicious-api-from-command-line][wget - How to use delicious API from command line - Super User]]
  - [[https://www.google.com/search?q=delicious%20py][delicious py - Google Search]]
  - [[http://web.student.tuwien.ac.at/~e9608591/files/delicious.feeds/delicious.py][web.student.tuwien.ac.at/~e9608591/files/delicious.feeds/delicious.py]]

* [2013-07-08 Mon 15:35] Getting Google+ posts            :@googleplus:@mail:
  - [[https://developers.google.com/+/api/latest/activities/list#try-it][Activities: list - Google+ Platform — Google Developers]]
  - [[https://developers.google.com/+/api/latest/people/list#try-it][People: list - Google+ Platform — Google Developers]]
  - [[http://stackoverflow.com/questions/14623452/getting-posts-from-google-plus-page][api - Getting posts from google plus page - Stack Overflow]]
  - [[http://wescpy.blogspot.ca/2012/04/integrating-google-apis-and.html][Core Python Programming: Integrating Google APIs and Technologies]]

* [2013-07-08 Mon 15:35] Movie trackers          :@download:@torrent:@movies:
  - [[http://lifehacker.com/5897095/whats-a-private-bittorrent-tracker-and-why-should-i-use-one][What's a Private BitTorrent Tracker, and Why Should I Use One?]]
  - [[http://filenetworks.blogspot.ca/search/label/Private%20Trackers][FILEnetworks Blog: Private Trackers]]
  - [[http://www.torrent-invites.com/bittorrent-discussion/222375-right-path-top-movie-trackers.html][The right path to the top movie trackers?]]
  - [[http://www.torrent-invites.com/tracker-reviews/][Tracker Reviews]]
  - [[http://www.torrent-invites.com/bittorrent-discussion/212426-best-movie-tracker-quantity-quality.html][Best movie tracker for Quantity/Quality?]]
  - [[http://www.torrent-invites.com/bittorrent-discussion/144925-best-movie-tracker-best-tv-tracker.html][Best movie tracker & Best TV tracker]]

* [2013-07-23 Tue 11:28] Alchemy Sound Library                       :@tobuy:
  :PROPERTIES:
  :ID:       f1e37f14-fe99-407e-a2ab-00606cf5c1f4
  :END:
 - [[http://www.camelaudio.com/Ian-Boddy-Analogica-Sound-Sample-Library.php][Ian Boddy: Analogica - Sound & Sample Library - Ambient, Electronica & Soundtrack]]

* [2013-11-08 Fri 16:21] Download YouTube videos/playlists / another option :@youtube:
  - [[http://rg3.github.io/youtube-dl/][youtube-dl]]
  - [[https://github.com/rg3/youtube-dl/][rg3/youtube-dl · GitHub]]
  - [[http://xmodulo.com/2013/07/how-to-download-youtube-playlist-in-linux.html][How to download YouTube playlist in Linux - Linux FAQ]]
  - [[http://xmodulo.com/2013/03/how-to-save-youtube-videos-on-linux.html][How to save YouTube videos on Linux - Linux FAQ]]

* [2013-12-03 Tue 09:59] Tube preamp pedals      :@musicmaker:@pedal:@preamp:
  - [[http://www.effectrode.com/blackbird-vacuum-tube-preamp/][Blackbird Vacuum Tube Preamp | effectrode]]
  - [[http://www.mesaboogie.com/Product_Info/Out_of%20_Production/V-Twin/v-twin.html][Mesa Boogie V-Twin Pedals]]
  - [[http://www.blackstaramps.com/products/ht-dual/][HT-DUAL Guitar Pedal - Blackstar]]
  - [[http://www.adaamps.com/Products/ada-APP1/APP1.htm][A/DA (tm) - A/DA Pedal Preamp]]

* [2013-12-06 Fri 11:44] PyObjC links - Exporting iTunes playlists :@pyobjc:@dev:@python:@osx:
  - [[http://stackoverflow.com/questions/16065162/calling-applescript-from-python-without-using-osascript-or-appscript][osx - Calling AppleScript from Python without using osascript or appscript? - Stack Overflow]]
  - [[http://www.redstoyland.com/projects/code/pythonandobjectivec.html][Red's Toyland - Python and Objective C]]
  - [[http://www.friday.com/bbum/2007/10/27/pyobjc-20-pyobjc-in-leopard/][bbum's weblog-o-mat » Blog Archive » PyObjC 2.0 (PyObjC in Leopard)]]
  - [[http://www.deanandara.com/python/IntroToUsingPyObjC.OLD_BUT_COMPLETE.html][Intro to Using PyObjC]]
  - [[http://pythonhosted.org/pyobjc/][Introduction — PyObjC — the Python ⟷ Objective-C bridge]]
  - [[http://www.macdevcenter.com/pub/a/mac/2003/01/31/pyobjc_one.html][MacDevCenter.com]]
  - [[http://stackoverflow.com/questions/10902671/scripting-bridge-vs-pyobjc-vs-py2app][python - Scripting Bridge vs PyObjC vs py2app - Stack Overflow]]
  - [[https://pypi.python.org/pypi/py-applescript][py-applescript 1.0.0 : Python Package Index]]
