
* [2010-03-20 Sat] Great EBow video                                 :@guitar:
  - YouTube - Phil Keaggy Ebow
    http://www.youtube.com/watch?v=wwq0i6jP7dQ&feature=related

* [2010-03-20 Sat] The Vibesware Resonator                          :@guitar:
  - How to play with the Vibesware Guitar Resonator | eHow.com
    http://www.ehow.com/how_5108858_play-vibesware-guitar-resonator.html
  - MySpace Video - Vibesware's Video Channel & Video Clips
    http://vids.myspace.com/index.cfm?fuseaction=vids.channel&vanity=vibesware

* TODO [2010-03-20 Sat] RockSchool Keep downloading!            :@todownload:
  :PROPERTIES:
  :ID:       2098A03D-EF5A-4EA0-812A-3ACC1F0EDF57
  :END:
  - YouTube - Rockschool - Series 1 - Ep.3 - Techniques (Part 3 of 3)
    http://www.youtube.com/watch?v=dWkN6dldYt8&feature=related

* [2010-03-20 Sat] Spas et massages
  - Strom spa nordique - Île-des-Soeurs Montréal
    https://www.stromspa.com/secure.asp?Lang=F&Pid=home.asp&STID=&Music=Off
  - Massages
    http://www.skyspa.ca/fr/services-et-tarifs/massotherapie
  - massage sous la pluie - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=massage+sous+la+pluie&ie=UTF-8&oe=UTF-8&redir_esc=&ei=DUulS_ydIcSAlAex3tT1Ag
  - Studio Bliss - Tarifs
    http://www.studiobliss.ca/tarifs.html
  - Laser Spa. Clinique de soins corporels - Épilation Laser - Esthétique
    http://www.laser-spa.com/
  - Vague Tropicale
    http://www.vaguetropicale.ca/index.htm

* [2010-03-20 Sat] Using Handbrake from the command line             :@video:
  - CLIGuide – HandBrake
    http://trac.handbrake.fr/wiki/CLIGuide

* [2010-03-20 Sat] Logging for iPhone development              :@dev:@iPhone:
  - iPhone Dev » How to Implement Grabbing a Sprite with Cocos2d and Box2d
    http://iphonedev.net/2009/08/05/how-to-grab-a-sprite-with-cocos2d-and-box2d/
  - Logs » Chris-Software.com
    http://chris-software.com/index.php/2009/04/29/logs/
  - How to Log to the Console Using NSLog
    http://getsetgames.com/2009/12/22/iphonedev-advent-tip-22-how-to-log-to-the-console-using-nslog/

* [2010-03-20 Sat] Adding trackers to torrents                     :@torrent:
  - PublicBitTorrent - An open tracker project
    http://publicbt.com/tracker_modify.html

* [2010-03-20 Sat] Remote control for transmission   :@torrent:@transmission:
  - man/transmission-remote – Transmission
    http://trac.transmissionbt.com/wiki/man/transmission-remote

* [2010-03-20 Sat] Emacs Mac OS X tweaks                             :@emacs:
  - EmacsWiki: Mac OSTweaks
    http://www.emacswiki.org/emacs/MacOSTweaks#toc22

* [2010-03-23 Tue] Time machine tips                      :@mac:@timemachine:
  - Migrate a Time Machine backup | Business Center | Working Mac | Macworld
    http://www.macworld.com/article/146085/2010/02/migratebackups.html
  - Access alternate Time Machine drives | Mac OS X | Mac OS X Hints | Macworld
    http://www.macworld.com/article/147185/2010/03/alttimemachinedrives.html?lsrc=nl_mwhints_h_crawl

* [2010-03-28 Sun] Relaxation music
  - Alex Theory - Wikipedia, the free encyclopedia
    http://en.wikipedia.org/wiki/Alex_Theory
  - Amazon.com: Alex Theory: Music
    http://www.amazon.com/exec/obidos/search-handle-url?_encoding=UTF8&search-type=ss&index=music&field-artist=Alex%20Theory
  - - Sounds True - Full Spectrum Sound Healing
    http://shop.soundstrue.com/shop.soundstrue.com/SelectProd.do;jsessionid=7CAD05B248360D7F13BE93888D37ACA4?prodId=2214&manufacturer=Sounds%20True&category=Meditation%20&%20Massage%20Music&name=Full%20Spectrum%20Sound%20Healing

* [2010-03-28 Sun] Logging with NSLog              :@objectivec:@development:
  - CocoaDev: NSLog
    http://www.cocoadev.com/index.pl?NSLog
  - CocoaDev: UsingTheDescriptionMethod
    http://www.cocoadev.com/index.pl?UsingTheDescriptionMethod
* [2010-03-28 Sun] iPhone Bonjour                     :@dev:@iphone:@bonjour:
  - iPhone Dev Center: NSNetServices and CFNetServices Programming Guide: Introduction to NSNetServices and CFNetServices Programming Guide
    http://developer.apple.com/iphone/library/documentation/Networking/Conceptual/NSNetServiceProgGuide/Introduction.html
  - Tutorial: Networking and Bonjour on iPhone
    http://www.mobileorchard.com/tutorial-networking-and-bonjour-on-iphone/
  - MDNS and caffeine: How I got Bonjour running on my iPhone
    http://www.tuaw.com/2007/10/22/mdns-and-caffeine-how-i-got-bonjour-running-on-my-iphone/

* [2010-05-20 Thu]                                                 :@cocos2d:
  - iPhone Dev » How to Implement Grabbing a Sprite with Cocos2d and Box2d
    http://iphonedev.net/2009/08/05/how-to-grab-a-sprite-with-cocos2d-and-box2d/

* [2010-05-20 Thu]                                                     :@mac:
  - Better command history browsing in Terminal | Mac OS X | Mac OS X Hints | Macworld
    http://www.macworld.com/article/146015/2010/01/termhistory.html?lsrc=nl_mwhints_h_crawl

* Télécharger des sous-titres francais pour tous les films sans vous compliquer la vie à les resynchroniser. | Sub Synchro
   Source: [2010-10-31 Sun], [[http://www.subsynchro.com/][Télécharger des sous-titres francais pour tous les films sans vous compliquer la vie à les resynchroniser. | Sub Synchro:Safari]]

* [2010-11-05 Fri] Subtitle editing on the Mac                    :@subtitle:
  - les poupees russes subtitles - Google Search
    http://www.google.com/search?q=les+poupees+russes+subtitles
  - Features
    http://www.jubler.org/features/index.php
  - Submerge
    http://www.bitfield.se/submerge/
  - RoadMovie
    http://www.bitfield.se/roadmovie/index.html
  - D-Subtitler ObjectifMac
    http://www.objectifmac.com/dsubtitler.php
  - Browse Sears Files on SourceForge.net
    http://sourceforge.net/projects/sears/files/
* [2010-11-05 Fri] Misc
** CutyCapt - A Qt WebKit Web Page Rendering Capture Utility
   http://cutycapt.sourceforge.net/
** MuseScore | Free music composition & notation software :@linux:@musicmaker:@sequencer:
   http://musescore.org/
** VocProc @ HyperGlitch                      :@musicmaker:@harmonize:@linux:
   http://hyperglitch.com/dev/VocProc
* [2010-11-05 Fri] Monome                                           :@monome:
  - monome - flin is fun
    http://post.monome.org/comments.php?DiscussionID=38
  - app:flin [monome]
    http://docs.monome.org/doku.php?id=app:flin
* [2010-11-05 Fri] How to Create iPad Formatted Videos Using HandBrake or FFMpeg :@ipad:@video:
  http://www.ioncannon.net/meta/1040/how-to-create-ipad-formatted-videos-using-handbrake-or-ffmpeg/
* [2010-11-05 Fri] Normalizing Audio for Multiple AVI files
  - Mini Guide: Normalizing Audio for Multiple AVI files
    http://forum.videohelp.com/threads/255147-Mini-Guide-Normalizing-Audio-for-Multiple-AVI-files
  - Multimedia Dynamite | Linux Journal
    http://www.linuxjournal.com/article/9787
* [2010-11-05 Fri] Watching directories for new files
  - Linux.com - Automatically process new files with fsniper
    http://www.linux.com/archive/articles/150200
  - fsniper documentation
    http://files.minuslab.net/doc.html
  - Pyinotify
    http://trac.dbzteam.org/pyinotify
  - smash at blogs.perl.org: Watching directories for new files
    http://blogs.perl.org/users/smash/2010/07/watching-directories-for-new-files.html
* [2010-11-05 Fri] Twitter stuff                            :@twitter:@emacs:
  - MRR Software
  http://www.mrrsoftware.com/MRRSoftware/Syrinx.html
- EmacsWiki: Twitter
  http://www.emacswiki.org/emacs/Twitter
- EmacsWiki: Tw It
  http://www.emacswiki.org/emacs/TwIt
- EmacsWiki: Twittering Mode
  http://www.emacswiki.org/emacs/TwitteringMode
- EmacsWiki: Identica-mode
  http://www.emacswiki.org/emacs/Identica-mode
- identica emacs - Google Search
  http://www.google.ca/search?client=safari&rls=en&q=identica+emacs&ie=UTF-8&oe=UTF-8&redir_esc=&ei=YeHTTIe9GtCgnQeJ8eSGBg
- Identi.ca mode for Emacs | Nethazard.net
  http://blog.nethazard.net/identica-mode-for-emacs/
- Pwytter: Twitter for Windows, Mac, Linux » Free Twitter client for Windows, Mac & Linux
  http://www.pwytter.com/

* [2010-11-05 Fri] Backuppc stuff                                 :@backuppc:
  - Back Up Linux And Windows Systems With BackupPC - Page 3 | HowtoForge - Linux Howtos and Tutorials
    http://www.howtoforge.com/linux_backuppc_p3

* [2010-11-05 Fri] Check avi file for errors                         :@video:
  - Scanning AVI files for errors - MvixCommunity - Forums & Wiki Dedicated to Mvix Products - Powered by FusionBB
    http://mvixcommunity.com/showtopic.php?tid/1407
  - Program to verify quality of avi files
    http://forum.videohelp.com/threads/243934-Program-to-verify-quality-of-avi-files
  - HOWTO: Check avi file for errors
    http://606u.dir.bg/avicheck/

* [2011-01-03 Mon] Commander-like interface for emacs                :@emacs:
 - EmacsWiki: Sunrise Commander Tips
   http://www.emacswiki.org/emacs/Sunrise_Commander_Tips
 - EmacsWiki: Sunrise Commander
   http://www.emacswiki.org/emacs/Sunrise_Commander

* [2011-01-25 Tue] Yasnippet notes - usage for templates             :@emacs:
  - yasnippet - Project Hosting on Google Code
    http://code.google.com/p/yasnippet/
  - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/search?group=smart-snippet&q=new&qt_g=Search+this+group
  - Issue 124 in yasnippet: yas/new-snippet default template creates spurious 'k-e-y-b-i-n-d-i-n-g' binding - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/browse_thread/thread/7e6d0b3c6448a7f7/400e1c6ceecfd5da?lnk=gst&q=new#400e1c6ceecfd5da
  - Issue 150 in yasnippet: Insertion for new created file fails - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/browse_thread/thread/b3027718dc13bc/57c0d20087253021?lnk=gst&q=new#57c0d20087253021
  - Expand snippet on visiting new file? - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/browse_thread/thread/6299b29069be4cf0/1b06c9499669cd65?lnk=gst&q=new#1b06c9499669cd65

* [2011-04-13 Wed] Recording BBC 4 shows                :@internetradio:@bbc:
  - http://forums.linuxmint.com/viewtopic.php?f=48&t=62200#p357271
    Basically use
    : get_iplayer --modes=flashaacstd --pid  http://www.bbc.co.uk/iplayer/console/...
    where http://www.bbc... is the "listen now" link on the show page.
