
* [2010-03-20 Sat] Great EBow video                                 :@guitar:
  - YouTube - Phil Keaggy Ebow
    http://www.youtube.com/watch?v=wwq0i6jP7dQ&feature=related

* [2010-03-20 Sat] The Vibesware Resonator                          :@guitar:
  - How to play with the Vibesware Guitar Resonator | eHow.com
    http://www.ehow.com/how_5108858_play-vibesware-guitar-resonator.html
  - MySpace Video - Vibesware's Video Channel & Video Clips
    http://vids.myspace.com/index.cfm?fuseaction=vids.channel&vanity=vibesware

* TODO [2010-03-20 Sat] RockSchool Keep downloading!            :@todownload:
  :PROPERTIES:
  :ID:       2098A03D-EF5A-4EA0-812A-3ACC1F0EDF57
  :END:
  - YouTube - Rockschool - Series 1 - Ep.3 - Techniques (Part 3 of 3)
    http://www.youtube.com/watch?v=dWkN6dldYt8&feature=related

* [2010-03-20 Sat] Spas et massages
  - Strom spa nordique - Île-des-Soeurs Montréal
    https://www.stromspa.com/secure.asp?Lang=F&Pid=home.asp&STID=&Music=Off
  - Massages
    http://www.skyspa.ca/fr/services-et-tarifs/massotherapie
  - massage sous la pluie - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=massage+sous+la+pluie&ie=UTF-8&oe=UTF-8&redir_esc=&ei=DUulS_ydIcSAlAex3tT1Ag
  - Studio Bliss - Tarifs
    http://www.studiobliss.ca/tarifs.html
  - Laser Spa. Clinique de soins corporels - Épilation Laser - Esthétique
    http://www.laser-spa.com/
  - Vague Tropicale
    http://www.vaguetropicale.ca/index.htm

* [2010-03-20 Sat] Using Handbrake from the command line             :@video:
  - CLIGuide – HandBrake
    http://trac.handbrake.fr/wiki/CLIGuide

* [2010-03-20 Sat] Logging for iPhone development              :@dev:@iPhone:
  - iPhone Dev » How to Implement Grabbing a Sprite with Cocos2d and Box2d
    http://iphonedev.net/2009/08/05/how-to-grab-a-sprite-with-cocos2d-and-box2d/
  - Logs » Chris-Software.com
    http://chris-software.com/index.php/2009/04/29/logs/
  - How to Log to the Console Using NSLog
    http://getsetgames.com/2009/12/22/iphonedev-advent-tip-22-how-to-log-to-the-console-using-nslog/

* [2010-03-20 Sat] Adding trackers to torrents                     :@torrent:
  - PublicBitTorrent - An open tracker project
    http://publicbt.com/tracker_modify.html

* [2010-03-20 Sat] Remote control for transmission   :@torrent:@transmission:
  - man/transmission-remote – Transmission
    http://trac.transmissionbt.com/wiki/man/transmission-remote

* [2010-03-20 Sat] Emacs Mac OS X tweaks                             :@emacs:
  - EmacsWiki: Mac OSTweaks
    http://www.emacswiki.org/emacs/MacOSTweaks#toc22

* [2010-03-23 Tue] Time machine tips                      :@mac:@timemachine:
  - Migrate a Time Machine backup | Business Center | Working Mac | Macworld
    http://www.macworld.com/article/146085/2010/02/migratebackups.html
  - Access alternate Time Machine drives | Mac OS X | Mac OS X Hints | Macworld
    http://www.macworld.com/article/147185/2010/03/alttimemachinedrives.html?lsrc=nl_mwhints_h_crawl

* [2010-03-28 Sun] Relaxation music
  - Alex Theory - Wikipedia, the free encyclopedia
    http://en.wikipedia.org/wiki/Alex_Theory
  - Amazon.com: Alex Theory: Music
    http://www.amazon.com/exec/obidos/search-handle-url?_encoding=UTF8&search-type=ss&index=music&field-artist=Alex%20Theory
  - - Sounds True - Full Spectrum Sound Healing
    http://shop.soundstrue.com/shop.soundstrue.com/SelectProd.do;jsessionid=7CAD05B248360D7F13BE93888D37ACA4?prodId=2214&manufacturer=Sounds%20True&category=Meditation%20&%20Massage%20Music&name=Full%20Spectrum%20Sound%20Healing

* [2010-03-28 Sun] Logging with NSLog              :@objectivec:@development:
  - CocoaDev: NSLog
    http://www.cocoadev.com/index.pl?NSLog
  - CocoaDev: UsingTheDescriptionMethod
    http://www.cocoadev.com/index.pl?UsingTheDescriptionMethod
* [2010-03-28 Sun] iPhone Bonjour                     :@dev:@iphone:@bonjour:
  - iPhone Dev Center: NSNetServices and CFNetServices Programming Guide: Introduction to NSNetServices and CFNetServices Programming Guide
    http://developer.apple.com/iphone/library/documentation/Networking/Conceptual/NSNetServiceProgGuide/Introduction.html
  - Tutorial: Networking and Bonjour on iPhone
    http://www.mobileorchard.com/tutorial-networking-and-bonjour-on-iphone/
  - MDNS and caffeine: How I got Bonjour running on my iPhone
    http://www.tuaw.com/2007/10/22/mdns-and-caffeine-how-i-got-bonjour-running-on-my-iphone/

* [2010-05-20 Thu]                                                 :@cocos2d:
  - iPhone Dev » How to Implement Grabbing a Sprite with Cocos2d and Box2d
    http://iphonedev.net/2009/08/05/how-to-grab-a-sprite-with-cocos2d-and-box2d/

* [2010-05-20 Thu]                                                     :@mac:
  - Better command history browsing in Terminal | Mac OS X | Mac OS X Hints | Macworld
    http://www.macworld.com/article/146015/2010/01/termhistory.html?lsrc=nl_mwhints_h_crawl

* Télécharger des sous-titres francais pour tous les films sans vous compliquer la vie à les resynchroniser. | Sub Synchro
   Source: [2010-10-31 Sun], [[http://www.subsynchro.com/][Télécharger des sous-titres francais pour tous les films sans vous compliquer la vie à les resynchroniser. | Sub Synchro:Safari]]

* [2010-11-05 Fri] Subtitle editing on the Mac                    :@subtitle:
  - les poupees russes subtitles - Google Search
    http://www.google.com/search?q=les+poupees+russes+subtitles
  - Features
    http://www.jubler.org/features/index.php
  - Submerge
    http://www.bitfield.se/submerge/
  - RoadMovie
    http://www.bitfield.se/roadmovie/index.html
  - D-Subtitler ObjectifMac
    http://www.objectifmac.com/dsubtitler.php
  - Browse Sears Files on SourceForge.net
    http://sourceforge.net/projects/sears/files/
* [2010-11-05 Fri] Misc
** CutyCapt - A Qt WebKit Web Page Rendering Capture Utility
   http://cutycapt.sourceforge.net/
** MuseScore | Free music composition & notation software :@linux:@musicmaker:@sequencer:
   http://musescore.org/
** VocProc @ HyperGlitch                      :@musicmaker:@harmonize:@linux:
   http://hyperglitch.com/dev/VocProc
* [2010-11-05 Fri] Monome                                           :@monome:
  - monome - flin is fun
    http://post.monome.org/comments.php?DiscussionID=38
  - app:flin [monome]
    http://docs.monome.org/doku.php?id=app:flin
* [2010-11-05 Fri] How to Create iPad Formatted Videos Using HandBrake or FFMpeg :@ipad:@video:
  http://www.ioncannon.net/meta/1040/how-to-create-ipad-formatted-videos-using-handbrake-or-ffmpeg/
* [2010-11-05 Fri] Normalizing Audio for Multiple AVI files
  - Mini Guide: Normalizing Audio for Multiple AVI files
    http://forum.videohelp.com/threads/255147-Mini-Guide-Normalizing-Audio-for-Multiple-AVI-files
  - Multimedia Dynamite | Linux Journal
    http://www.linuxjournal.com/article/9787
* [2010-11-05 Fri] Watching directories for new files
  - Linux.com - Automatically process new files with fsniper
    http://www.linux.com/archive/articles/150200
  - fsniper documentation
    http://files.minuslab.net/doc.html
  - Pyinotify
    http://trac.dbzteam.org/pyinotify
  - smash at blogs.perl.org: Watching directories for new files
    http://blogs.perl.org/users/smash/2010/07/watching-directories-for-new-files.html
* [2010-11-05 Fri] Twitter stuff                            :@twitter:@emacs:
  - MRR Software
  http://www.mrrsoftware.com/MRRSoftware/Syrinx.html
- EmacsWiki: Twitter
  http://www.emacswiki.org/emacs/Twitter
- EmacsWiki: Tw It
  http://www.emacswiki.org/emacs/TwIt
- EmacsWiki: Twittering Mode
  http://www.emacswiki.org/emacs/TwitteringMode
- EmacsWiki: Identica-mode
  http://www.emacswiki.org/emacs/Identica-mode
- identica emacs - Google Search
  http://www.google.ca/search?client=safari&rls=en&q=identica+emacs&ie=UTF-8&oe=UTF-8&redir_esc=&ei=YeHTTIe9GtCgnQeJ8eSGBg
- Identi.ca mode for Emacs | Nethazard.net
  http://blog.nethazard.net/identica-mode-for-emacs/
- Pwytter: Twitter for Windows, Mac, Linux » Free Twitter client for Windows, Mac & Linux
  http://www.pwytter.com/

* [2010-11-05 Fri] Backuppc stuff                                 :@backuppc:
  - Back Up Linux And Windows Systems With BackupPC - Page 3 | HowtoForge - Linux Howtos and Tutorials
    http://www.howtoforge.com/linux_backuppc_p3

* [2010-11-05 Fri] Check avi file for errors                         :@video:
  - Scanning AVI files for errors - MvixCommunity - Forums & Wiki Dedicated to Mvix Products - Powered by FusionBB
    http://mvixcommunity.com/showtopic.php?tid/1407
  - Program to verify quality of avi files
    http://forum.videohelp.com/threads/243934-Program-to-verify-quality-of-avi-files
  - HOWTO: Check avi file for errors
    http://606u.dir.bg/avicheck/

* [2011-01-03 Mon] Commander-like interface for emacs                :@emacs:
 - EmacsWiki: Sunrise Commander Tips
   http://www.emacswiki.org/emacs/Sunrise_Commander_Tips
 - EmacsWiki: Sunrise Commander
   http://www.emacswiki.org/emacs/Sunrise_Commander

* [2011-01-25 Tue] Yasnippet notes - usage for templates             :@emacs:
  - yasnippet - Project Hosting on Google Code
    http://code.google.com/p/yasnippet/
  - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/search?group=smart-snippet&q=new&qt_g=Search+this+group
  - Issue 124 in yasnippet: yas/new-snippet default template creates spurious 'k-e-y-b-i-n-d-i-n-g' binding - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/browse_thread/thread/7e6d0b3c6448a7f7/400e1c6ceecfd5da?lnk=gst&q=new#400e1c6ceecfd5da
  - Issue 150 in yasnippet: Insertion for new created file fails - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/browse_thread/thread/b3027718dc13bc/57c0d20087253021?lnk=gst&q=new#57c0d20087253021
  - Expand snippet on visiting new file? - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/browse_thread/thread/6299b29069be4cf0/1b06c9499669cd65?lnk=gst&q=new#1b06c9499669cd65

* [2011-04-13 Wed] Recording BBC 4 shows                :@internetradio:@bbc:
  - http://forums.linuxmint.com/viewtopic.php?f=48&t=62200#p357271
    Basically use
    : get_iplayer --modes=flashaacstd --pid  http://www.bbc.co.uk/iplayer/console/...
    where http://www.bbc... is the "listen now" link on the show page.

* [2011-06-07 Tue] Controlling iTunes - Example code           :@dev:@itunes:
  - Open Alexandria » Blog Archive » My Tunes Controller – control iTunes on menu bar
    http://openalexandria.com/2010/10/my-tunes-controller/
  - iTunesController.m - mytunescontroller - MyTunesController - Google Project Hosting
    http://code.google.com/p/mytunescontroller/source/browse/trunk/iTunesController.m

* [2011-06-07 Tue] Some Cocoa source code                       :@dev:@cocoa:
** Cocoa Source Code » Matt Legend Gemmell
   http://mattgemmell.com/source
** Details
  :PROPERTIES:
  :VISIBILITY: folded
  :END:
  - MGSplitViewController
     MGSplitViewController is an enhanced replacement for
     UISplitViewController on the iPad. It allows displaying the
     master view in either orientation, toggling it with animation,
     changing the split from horizontal to vertical, dragging the
     divider, and more.
   - MGImageUtilities
     MGImageUtilities is a collection of useful UIImage categories
     for iPad and iPhone, including image-tinting and image-cropping
     functionality(which explicitly supports multiple orientations,
     and high-resolution Retina Displays).
   - iPad VGA Output
     iPad VGA Output is an open source iPad application showing how
     you can display content on an external display via the iPad VGA
     adapter. It includes a window which goes on the external screen,
     and a window which goes on the iPad, and shows how to detect
     supported external resolutions.
   - iPad Multi Touch
     iPad Multi Touch is an open source iPad application which lets
     you visually track multiple touches, up to the maximum number
     the iPad supports simultaneously (which is eleven, by the
     way). It has some nice Core Animation effects too.
   - Shady
     Shady is an open source Mac OS X application which lets you dim
     the screen beyond its usual limit, ideal for tired (or
     photo-sensitive) eyes.
   - MGScopeBar
     MGScopeBar provides a scope/filter bar much like you’ll find in
     Mail, the Finder (in the Find/Spotlight window), iTunes and
     elsewhere. You can see a demo movie of it here.
   - MGTemplateEngine
     MGTemplateEngine is a native Cocoa system for generating text
     output based on templates and data. It’s a close cousin of
     systems like Smarty, FreeMarker, Django‘s template language, and
     other such systems.
     It’s ideal for Cocoa or iPhone apps needing to generate text
     output using variable-substitution (with looping and/or
     conditional logic), including HTML for export or for apps with
     WebKit-based UIs, invoices or printable templates, mail merge,
     data export or any number of other things. It’s also great (in
     combination with WebKit) for letting your users create
     themes/styles for your application.
   - Skinnable App
     This is a small application demonstrating how to use an embedded
     WebKit WebView to easily “skin” your applications, i.e. style
     your app’s UI using standard CSS files. It shows how to switch
     CSS themes dynamically, how to use Objective-C to add HTML
     content into a WebView, how to retrieve data from the HTML
     document, how to replace existing content, and how to allow HTML
     controls (form elements) to call methods in Cocoa objects.
   - MGTwitterEngine (on github) 
     MGTwitterEngine is a class which lets you integrate Twitter
     support into your Cocoa application, by making use of the
     Twitter API. The entire API is covered, and appropriate data is
     returned as simple Cocoa objects (NSArrays, NSDictionarys,
     NSStrings, NSDates and so on), for very easy integration with
     your code. Creating a TwitterEngine is as easy as instantiating
     it, setting your Twitter username and password, and you’re
     done. See this blog post for more.
   - NSImage+QuickLook
     A category on NSImage allowing you to get an image containing a
     Quick Look preview of the file at a given path. You can specify
     the size, and whether the preview should be rendered as an icon
     (i.e. with a document border, drop-shadow, page-curl and file
     type/extension label superimposed). If Quick Look can’t generate
     a preview for the specified file, you’ll be given the file’s
     Finder icon instead (which is how the Quick Look panel itself
     behaves in Leopard).
   - MAAttachedWindow
     A cool NSWindow subclass which lets you easily attach a view to
     another window, displayed in a floating “speech-bubble”-like
     borderless window. Very handy for contextual help, showing
     options for a certain control, or just to draw attention to
     things. Have a look at this screenshot to see how it works. You
     can also grab a project showing how to use an MAAttachedWindow
     with an NSStatusItem.
   - MATrackingArea
     A simple category on NSView and an accompanying class which
     together allow you to add “tracking areas” to your
     views. Tracking areas are like tracking rectangles but are more
     robust and effective, and can be configured to track the mouse
     either at all times, only when the view’s app is active, only
     when the view’s window is key, or only when the view is First
     Responder. You can also choose whether to use the view’s visible
     rect in preference to the rect you pass in. See the example for
     details.
   - MGViewAnimation
     An NSAnimation subclass which provides more desirable behaviour
     than NSViewAnimation itself in most circumstances; i.e. it
     animates the views’ frames itself in the same thread, leading to
     visually synchronised movement. Try out the included sample app
     to see the difference between regular NSViewAnimations and
     these.
   - NSColor+ContrastingLabelExtensions
     A category on NSColor which returns another NSColor for use when
     drawing label text on top of the receiver. Either white or black
     is returned, depending on which will have most visual contrast
     with the receiver’s color. In the event of the receiver’s
     colorspace not being converted to RGB, black is returned by
     default.
   - ImageCrop
     A category on NSImage allowing you to obtain a resized version
     of the image to fit an arbitrary size, with a choice of cropping
     or scaling methods (crop center, crop start, crop end, or scale
     to fit). Uses high-quality interpolation too.
   - HUDWindow
     An NSPanel subclass which creates a translucent window like
     iPhoto “Adjust” palette. Useful for graphics applications where
     a non-intrusive, high-contrast UI style is needed. Or just to
     look cool.
   - RoundedBox
     An NSBox subclass which draws a pretty rounded-rectangle box
     with a gradient background; take a look at the screenshot to see
     how it looks. Includes lots of configurable options, and it’s
     ready to drop right into your project.
   - TunesWindow
     A project which displays a window in the iTunes 5/6
     (i.e. “polished metal”) style. Like the Unified look, but
     darker. Get the iTunes look in your own apps easily.
   - iCal Calendars
     A simple application which reads iCal’s calendars and returns an
     NSDictionary whose keys are the names of the calendars, and
     whose values are Calendar objects, with fields “title”
     (NSString), “notes” (NSString), “color” (NSColor), and both GUID
     keys used by iCal to keep track of calendars and their source
     data.
   - NSBezierPath+StrokeExtensions
     A simple category on NSBezierPath allowing you stroke inside a
     path, rather than stroking centered on the path.
   - RoundedFloatingPanel
     An NSView subclass and accompanying NSWindow subclass which
     provide the same rounded floating panel overlay which the
     Panther application switcher uses.
   - iTableColumnHeader
     An NSTableHeaderCell subclass providing the metallic column
     headers seen in iApps, including the Calendars list in iCal and
     the Source list in iTunes.
   - iTableView (Source List and Colored Checkboxes)
     A pair of NSTextFieldCell and NSImageCell subclasses (and a
     simple NSTableView subclass) which provide the blue-gradient
     selection highlighting behaviour you see in iCal’s “Calendars”
     list, iTunes’ “Source” list, and the sidebar in the Panther
     Finder. Apple calls this kind of control a Source List.
     Also includes code to draw colored checkboxes as in iCal, using
     any color you want!
   - Address Book Test
     Shows how to make use of the Mac OS X 10.2 Address Book
     API. Includes a live-filtering field which locates Address Book
     entries by forename, surname or company, and demonstrates
     finding the primary email address for a specified person, as
     well as their name and picture.
   - Better TextFinder
     Easily implement Find and Replace in your application. Adapted
     and improved from TextEdit’s implementation. Includes both the
     class and a Nib file containing an appropriate Find panel. Read
     more about the improvements here.
   - SS_PrefsController
     A class which lets you easily create Mail/iTunes/Safari-style
     Preferences windows, with toolbars and multiple panes loaded
     from bundles. Loads of configurable options and flexibility, and
     professional results. Take a look at the class documentation
     (also included in the download).
   - Window Fade-out
     Ever felt the need to have a window fade out of existence,
     instead of just closing? Here’s how.
   - Grab-Scrolling
     Shows how to implement grab-scrolling, like in Preview,
     Photoshop, Acrobat and more. Includes the two requisite
     hand-cursors.
   - Screen Sharing
     Source for two apps, a client and a server, letting you send
     full-screen screenshots of your Mac via Rendezvous. This is a
     modification of Apple’s Picture Sharing code.


* [2011-10-04 Tue] Bash completion/expansion notes             :@linux:@bash:
   - Bash Alias Utilities
     http://www.logicalpoetry.com/bashalias/
   - Working more productively with bash 2.x/3.x
     http://caliban.org/bash/#completion
   - Bashrun - X11 application launcher based on bash
     http://bashrun.sourceforge.net/
   - An introduction to bash completion: part 1
     http://www.debian-administration.org/articles/316
   - revans/bash-it - GitHub
     https://github.com/revans/bash-it
   - robbyrussell/oh-my-zsh - GitHub
     https://github.com/robbyrussell/oh-my-zsh
   - Themes - GitHub
     https://github.com/robbyrussell/oh-my-zsh/wiki/themes

* [2011-11-08 Tue] Using ediff as a mercurial merge tool  :@emacs:@mercurial:
  - emacs - Using ediff as git mergetool - Stack Overflow
    http://stackoverflow.com/questions/1817370/using-ediff-as-git-mergetool
  - configuration - How can I use ediff (emacs diff) as a diff/merge tool in Windows ClearCase? - Stack Overflow
    http://stackoverflow.com/questions/658127/how-can-i-use-ediff-emacs-diff-as-a-diff-merge-tool-in-windows-clearcase
  - Flow-Geek: Using Emacs ediff as a graphical merge tool for Subversion
    http://zaakbeekman.blogspot.com/2011/04/using-emacs-ediff-as-graphical-merge.html
  - MergingWithEmacs - Mercurial
    http://mercurial.selenic.com/wiki/MergingWithEmacs
  - MergeToolConfiguration - Mercurial
    http://mercurial.selenic.com/wiki/MergeToolConfiguration
  - ExtdiffExtension - Mercurial
    http://mercurial.selenic.com/wiki/ExtdiffExtension
  - Merging with Emacs and ediff-mode
    http://www.selenic.com/pipermail/mercurial/2008-November/022599.html

* [2011-11-08 Tue] mkv/ac3 Conversion          :@video:@conversion:@mkv:@ac3:
  - Convert mkv movies into mp4 - Page 4 - MacRumors Forums
    http://forums.macrumors.com/showthread.php?t=301017&page=4
  - Convert mkv movies into mp4 - Page 5 - MacRumors Forums
    http://att.macrumors.com/showthread.php?t=301017&page=5
  - Converting an MKV (h264) File to PS3 MP4 Without Re-encoding on Mac OS X « Just Another Odd Man Out
    http://oddmanout.wordpress.com/2008/01/26/converting-an-mkv-h264-file-to-ps3-mp4-without-re-encoding-on-mac-os-x/
  - Help: Need to put AC3 into MP4 with ffmpeg
    http://forum.videohelp.com/threads/311525-Help-Need-to-put-AC3-into-MP4-with-ffmpeg

* [2011-11-08 Tue] Ambient music                            :@music:@ambient:
  - www.darkwinter.com
    http://www.darkwinter.com/index1.html

* [2011-11-08 Tue] org-mode on MacOS                          :@orgmode:@mac:
  - org-protocol - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=org-protocol&ie=UTF-8&oe=UTF-8&redir_esc=&ei=wJKHTuaVH4XK0AH-iJ37Dw
  - Remember Mode Tutorial
    http://members.optusnet.com.au/~charles57/GTD/remember.html
  - org-protocol.el – Intercept calls from emacsclient to trigger custom actions
    http://orgmode.org/worg/org-contrib/org-protocol.html
  - Org and Mac OS X
    http://orgmode.org/worg/org-mac.html
  - org-mac-message.el – linking to messages in OS X Mail.app
    http://orgmode.org/worg/org-contrib/org-mac-message.html
  - claviclaws/org-mac-protocol - GitHub
    https://github.com/claviclaws/org-mac-protocol
  - org-mac-protocol.org at master from claviclaws/org-mac-protocol - GitHub
    https://github.com/claviclaws/org-mac-protocol/blob/master/org-mac-protocol.org
  - org-mac-protocol.el at master from claviclaws/org-mac-protocol - GitHub
    https://github.com/claviclaws/org-mac-protocol/blob/master/org-mac-protocol.el
  - org-note.applescript at master from claviclaws/org-mac-protocol - GitHub
    https://github.com/claviclaws/org-mac-protocol/blob/master/org-note.applescript

* [2011-11-08 Tue] Use Spotlight to globally index any text file :@spotlight:
  - 10.4: Use Spotlight to globally index any text file - Mac OS X Hints
    http://hints.macworld.com/article.php?story=2005052015041510

* [2011-11-08 Tue] Blade Runner soundtracks             :@bladerunner:@music:
  - The Blade Runner Soundtracks Ultimate Thread - Page 18
    http://forums.ffshrine.org/f92/blade-runner-soundtracks-ultimate-thread-72496/18.html#post1604062
  - blade runner esper retirement edition torrent - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=blade+runner+esper+retirement+edition+torrent&ie=UTF-8&oe=UTF-8&redir_esc=&ei=SDJ-TvfSBozp0QH4rqX4Dw
  - Scifi.dead-donkey.com • View topic - Blade Runner - Esper Retirement Edition
    http://scifi.dead-donkey.com/viewtopic.php?f=13&t=4553
  - Various Artists Blade Runner Esper 039 Retirement 039 Edit Torrent - TorrentFunk
    http://www.torrentfunk.com/torrent/2775394/various-artists-blade-runner-esper-039-retirement-039-edit.html
  - The Blade Runner Soundtracks Ultimate Thread - Page 28
    http://forums.ffshrine.org/f92/blade-runner-soundtracks-ultimate-thread-72496/28.html
  - blade runner ems2011 - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=blade+runner+ems2011&ie=UTF-8&oe=UTF-8&redir_esc=&ei=6DV-TsGgLqHy0gG91pzXDw
  - EMS Recombination
    http://emsrecombination.blogspot.com/
  - ems recombination definitive 3 disc edition - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=EMS+Recombination+Definitive+3+Disc+Edition&ie=UTF-8&oe=UTF-8&redir_esc=&ei=7zl-TsK7MILn0QG6rt0K
  - Do Androids Dream Of Lossless Audio Files? A Blade Runner Soundtrack Thread - Page 22
    http://forums.ffshrine.org/f92/do-androids-dream-lossless-audio-files-blade-75274/22.html

* [2011-11-08 Tue] tmux notes                              :@linux:@terminal:
  - tmux
    http://tmux.sourceforge.net/
  - Manual Pages: tmux(1)
    http://www.openbsd.org/cgi-bin/man.cgi?query=tmux&sektion=1
  - TMUX – The Terminal Multiplexer (Part 1) | Hawk Host Blog
    http://blog.hawkhost.com/2010/06/28/tmux-the-terminal-multiplexer/
  - TMUX – The Terminal Multiplexer (Part 2) | Hawk Host Blog
    http://blog.hawkhost.com/2010/07/02/tmux-%e2%80%93-the-terminal-multiplexer-part-2/
  - dayid's screen and tmux cheat sheet
    http://www.dayid.org/os/notes/tm.html

* [2011-11-08 Tue] Great color scheme                :@terminal:@colorscheme:
  - mayansmoke - Ergonomic light-background color scheme. : vim online
    http://www.vim.org/scripts/script.php?script_id=3065

* [2011-11-08 Tue] byobu notes                             :@byobu:@terminal:
  - Canonical Voices
    http://voices.canonical.com/tag/byobu/
  - Byobu - Community Ubuntu Documentation
    https://help.ubuntu.com/community/Byobu
  - Ubuntu Manpage: byobu - wrapper script for seeding a user's byobu configuration and
    http://manpages.ubuntu.com/manpages/oneiric/en/man1/byobu.1.html
  - byobu in Launchpad
    https://launchpad.net/byobu
  - From the Canyon Edge - :-Dustin Kirkland: Byobu
    http://blog.dustinkirkland.com/search/label/Byobu

* [2011-11-08 Tue] HOWTORead Feeds In Emacs Via Email    :@feeds:@wanderlust:
  - EmacsWiki: HOWTORead Feeds In Emacs Via Email
    http://www.emacswiki.org/emacs/HOWTOReadFeedsInEmacsViaEmail#toc5

* [2011-11-08 Tue] Cabinet simulator links              :@musicmaker:@cabsim:
  - Condor Cab Sim
    http://runoffgroove.com/condor.html
  - Op-Amp review page
    http://www.rock-grotto.co.uk/opamp.htm

* TODO [#A] [2011-11-08 Tue] Time machine tweaks           :@mac:timemachine:
  - Good folders to exclude from Time Machine backups – Ryan Block
    http://ryanblock.com/2008/05/good-folders-to-exclude-from-time-machine-backups/

* [2011-11-08 Tue] Amp sim                              :@musicmaker:@ampsim:
  - Head Case | AcmeBarGig
    http://www.acmebargig.com/product/head-case/

* [2011-11-08 Tue] Impulse response AU plugins      :@musicmaker:@cabsim:@au:
  - Amplifikation Lite at Kuassa Amplifikation
    http://www.kuassa.com/products/amplifikation-lite
  - Mellowmuse IR1A - Zero Latency convolver RTAS, AudioUnit and VST plug-in for OSX and Windows
    http://www.mellowmuse.com/IR1A.html

* [2011-11-08 Tue] Embed album cover art from the command line :@music:@tag:@cover:
  - How do you embed album art into an MP3 using Python? - Stack Overflow
    http://stackoverflow.com/questions/409949/how-do-you-embed-album-art-into-an-mp3-using-python
  - Howto Write APIC Tag with Mutagen - Quod Libet Development | Google Groups
    http://groups.google.com/group/quod-libet-development/browse_thread/thread/72a19593a44d6243?pli=1
  - eyeD3 0.6.17
    http://eyed3.nicfit.net/
  - Embedded Album Covers, Your PSP, Amarok, and You – Kasperian Moving Parts
    http://movingparts.net/2007/12/09/embedded-album-covers-your-psp-amarok-and-you/

* [2011-11-08 Tue] Openbox links                        :@linux:@wm:@openbox:
  - Openbox guide « urukrama’s weblog
    http://urukrama.wordpress.com/openbox-guide/

* [2011-11-08 Tue] Remove accents from filenames/dirnames      :@dev:@python:
  - \xe9 - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=%5Cxe9&ie=UTF-8&oe=UTF-8&redir_esc=&ei=CPhvToKwGIH50gHKirn-CA
  - Python Unicode Objects
    http://effbot.org/zone/unicode-objects.htm
  - Converting Unicode Strings to 8-bit Strings
    http://effbot.org/zone/unicode-convert.htm
  - string.translate - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=string.translate&ie=UTF-8&oe=UTF-8&redir_esc=&ei=EI5wTrTfCqrD0AH4uYH3CQ
  - 7.1. string — Common string operations — Python v2.7.2 documentation
    http://docs.python.org/library/string.html
  - Python String translate() Method
    http://www.tutorialspoint.com/python/string_translate.htm
  - Simple Wrapper for string.translate « Python recipes « ActiveState Code
    http://code.activestate.com/recipes/303342-simple-wrapper-for-stringtranslate/
  - pythno string translate accented - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=pythno+string+translate+accented&ie=UTF-8&oe=UTF-8&redir_esc=&ei=rY5wToybEqjL0QHi2fn3CQ
  - library - What is the best way to remove accents in a python unicode string? - Stack Overflow
    http://stackoverflow.com/questions/517923/what-is-the-best-way-to-remove-accents-in-a-python-unicode-string
  - regex - Python String Cleanup + Manipulation (Accented Characters) - Stack Overflow
    http://stackoverflow.com/questions/930303/python-string-cleanup-manipulation-accented-characters
  - How to convert an accented character in an unicode string to its unicode character code using Python? - Stack Overflow
    http://stackoverflow.com/questions/3499087/how-to-convert-an-accented-character-in-an-unicode-string-to-its-unicode-charact
  - Latin1 to ASCII -- The UNICODE Hammer « Python recipes « ActiveState Code
    http://code.activestate.com/recipes/251871-latin1-to-ascii-the-unicode-hammer/

* [2011-11-09 Wed] Making Impulse Responses                 :@musicmaker:@ir:
  - Making Impulse Responses with Logic's IR Utility
    http://www.soundonsound.com/sos/feb08/articles/logictech_0208.htm
  - GuitarAmpModeling.com • View topic - Creating Your OWN IR Files in Cubase!!
    http://www.guitarampmodeling.com/viewtopic.php?f=32&t=12276
  - Creating Your OWN IR Files by Cubase! - YouTube
    http://www.youtube.com/watch?v=Z4-L5cPYHl4

* [2011-11-09 Wed] Music file tags on the command line          :@music:@tag:
- eyeD3 0.6.17
  http://eyed3.nicfit.net/
- EyeD3 | SavvyAdmin.com - Strip All Unwanted MP3 ID3 Tags
  http://savvyadmin.com/tag/eyed3/
- mp3sort.pl - template based mp3 sorter using ID3 tags
  https://github.com/aptituz/mp3sort/blob/master/mp3sort.pl
- GNU Songanizer Home Page
  GNU Songanizer is a shell script to organize a directory containing
  a collection of Ogg Vorbis and MP3 files.
  http://www.gnu.org/s/songanizer/
- arename
  http://ft.bewatermyfriend.org/comp/arename.html
- arename - automatically rename audio files by tagging information
  http://ft.bewatermyfriend.org/comp/arename/arename.html
- ftblog: audio helpers - zsh function atag()
  atag() provides a consistent way to the aforementioned file formats meta
  information
  http://bewatermyfriend.org/posts/2008/03-10.10-53-11-computer.html

* [2011-11-12 Sat] Python Music/MIDI               :@dev:@python:@musicmaker:
  - PythonInMusic - PythonInfo Wiki
    http://wiki.python.org/moin/PythonInMusic
** General Tools                                               :@audio:@midi:
   - The MusicKit V5.6.2
     http://musickit.sourceforge.net/
     The MusicKit is an object-oriented software system for building
     music, sound, signal processing, and MIDI applications.
** Audio Tools                                                       :@audio:
   - Python Audio Tools
     http://audiotools.sourceforge.net/
     Python Audio Tools are a collection of audio handling programs
     which work from the command line.
   - zyne - Modular synthesizer - Google Project Hosting
     http://code.google.com/p/zyne/
     Zyne is a Python modular synthesizer using pyo as its audio engine.
** MIDI Tools                                                         :@midi:
   - pyrtmidi – pkaudio
     http://trac.assembla.com/pkaudio/wiki/pyrtmidi
     pyrtmidi is a Python interface to RtMidi?. It provides real-time
     midi input and output.
   - mididings - a MIDI router/processor based on Python
     http://das.nasophon.de/mididings/
     mididings is a MIDI router and processor based on Python, supporting
     ALSA and JACK MIDI. It is available under the GNU GPL and currently
     runs on Linux. 
   - pyPortMidi
     http://alumni.media.mit.edu/~harrison/code.html
     pyPortMidi is a Python wrapper I wrote for PortMidi. PortMidi is a
     cross-platform C library for realtime MIDI control. Using
     pyPortMidi, you can send and receive MIDI data in realtime from
     Python.
   - pgreloaded - PyGame Reloaded - Multimedia Framework for Python
     http://code.google.com/p/pgreloaded/
     Pygame2 is a cross-platform multimedia framework for the
     excellent Python programming language. Its purpose is to make
     writing multimedia applications, such as games, with Python as easy
     as possible, while providing the developer a reliable and
     extensible programming interface.

* [2011-11-12 Sat] edna -- an MP3 server               :@mediaserver:@python:
  http://edna.sourceforge.net/
  edna allows you to access your MP3 collection from any networked
  computer. This software streams your MP3s via HTTP to any MP3 player
  that supports playing off a remote connection (e.g. Winamp, FreeAmp,
  Sonique, XMMS, WMP).

* [2011-11-13 Sun] virtualenv                                  :@python:@dev:
  - virtualenvwrapper - Doug Hellmann
    http://www.doughellmann.com/projects/virtualenvwrapper/
  - virtualenvwrapper 2.10.1 — virtualenvwrapper v2.10.1 documentation
    http://www.doughellmann.com/docs/virtualenvwrapper/
  - Presentation: pip and virtualenv | mathematism
    http://mathematism.com/2009/07/30/presentation-pip-and-virtualenv/
  - virtualenvwrapper on Vimeo
    http://vimeo.com/5894881

* [2011-11-20 Sun] Tagging audio files       :@python:@audio:@music:@discogs:
  - oliparcol/tagog - GitHub
    https://github.com/oliparcol/tagog
  - API / DiscogsTagger: A console based python metadata tagger based on the Discogs API
    http://www.discogs.com/help/forums/topic/251892
  - jesseward/discogstagger - GitHub
    https://github.com/jesseward/discogstagger
  - Requests: Python HTTP Module
    http://kennethreitz.com/requests-python-http-module.html
  - requests 0.8.2 : Python Package Index
    http://pypi.python.org/pypi/requests
  - kennethreitz/requests - GitHub
    https://github.com/kennethreitz/requests
  - discogs python api - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=discogs+python&ie=UTF-8&oe=UTF-8&redir_esc=&ei=eXnJTvrnBMn20gHN2tEP#sclient=psy-ab&hl=en&client=safari&rls=en&source=hp&q=discogs+python+api&pbx=1&oq=discogs+python+api&aq=f&aqi=g-v1&aql=&gs_sm=e&gs_upl=37951l38255l0l38530l4l3l0l0l0l0l146l429l0.3l3l0&bav=on.2,or.r_gc.r_pw.r_cp.,cf.osb&fp=1c55a80a74b83adf&biw=1033&bih=871
  - API v2.0 Documentation
    http://www.discogs.com/help/api
  - discogs/discogs-python-client - GitHub
    https://github.com/discogs/discogs-python-client

* [2011-11-20 Sun] Move windows on Macos                          :@dev:@mac:
  - cocoa - How can I programatically move one Terminal.app window to another space? - Stack Overflow
    http://stackoverflow.com/questions/2308820/how-can-i-programatically-move-one-terminal-app-window-to-another-space
  - Move window to second display | Cocoabuilder
    http://www.cocoabuilder.com/archive/cocoa/213109-move-window-to-second-display.html
  - objective c - Controlling OSX windows - Stack Overflow
    http://stackoverflow.com/questions/1730859/controlling-osx-windows

* [2011-11-20 Sun] Blogging with org-mode                    :@blog:@orgmode:
  - Blorgit: Org-Mode based, git amenable, blogging engine
    http://orgmode.org/worg/blorgit.html
  - Using org to Blog with Jekyll
    http://orgmode.org/worg/org-tutorials/org-jekyll.html

* [2011-11-20 Sun] org-mode tagging                           :@orgmode:@tag:
  - http://lisperati.com/tagging.html
    http://lisperati.com/tagging.html
  - EmacsWiki: Bookmark Plus
    http://www.emacswiki.org/emacs-se/BookmarkPlus#BookmarkTags
  - EmacsWiki: free-tagging.el
    http://www.emacswiki.org/emacs/free-tagging.el
  - Tag searches - The Org Manual
    http://orgmode.org/manual/Tag-searches.html#Tag-searches
  - Org-Mode for GNU Emacs
    http://comments.gmane.org/gmane.emacs.orgmode/34038
  - Generate list of all tags in use?
    http://permalink.gmane.org/gmane.emacs.orgmode/34069
  - Automatic global tag list?
    http://permalink.gmane.org/gmane.emacs.orgmode/33995

* [2011-11-20 Sun] Static blog generation and scm   :@blog:@python:@markdown:
  - Byteflow - a Python/Django Blog Engine
    http://byteflow.su/
  - blohg
    http://blohg.org/
  - blohg » About blohg
    http://blohg.org/about/
  - Welcome to blohg’s documentation! — blohg v0.8 documentation
    http://docs.blohg.org/
  - dz/chisel - GitHub
    https://github.com/dz/chisel
  - Cyrax — Cyrax v2.5
    http://cyrax.readthedocs.org/en/latest/index.html
  - lakshmivyas/hyde - GitHub
    https://github.com/lakshmivyas/hyde
  - Hyde - A Python Static Website Generator
    http://ringce.com/hyde
    - Ringce : Introducing Hyde
      http://ringce.com/blog/2009/introducing_hyde
    - Hyde Templates - GitHub
      https://github.com/lakshmivyas/hyde/wiki/Templating-Guide
    - Hyde | Google Groups
      http://groups.google.com/group/hyde-dev
    - New Hyde Layout based on Bootstrap - Hyde | Google Groups
      http://groups.google.com/group/hyde-dev/browse_thread/thread/7b928bddc29d74f0#
    - auzigog/hyde-bootstrap - GitHub
      https://github.com/auzigog/hyde-bootstrap
    - Bootstrap, from Twitter
      http://twitter.github.com/bootstrap/
    - Merlin Rebrovic
      http://merlin.rebrovic.net/
    - Hyde Starter Kit
      http://merlin.rebrovic.net/hyde-starter-kit/
  - Tahchee
    http://ivy.fr/tahchee/
  - Markdoc Documentation » Index
    http://markdoc.org/
  - Markdoc Documentation » Barebones Wikis
    http://markdoc.org/tips/barebones
  - obensonne / poole / overview — Bitbucket
    https://bitbucket.org/obensonne/poole
  - Static Blog Generators
    http://www.subspacefield.org/~travis/static_blog_generators.html
  - xfire/growl - GitHub
    https://github.com/xfire/growl/tree
  - jek / blatter / overview — Bitbucket
    https://bitbucket.org/jek/blatter/
  - Welcome to lanyon’s documentation! — Lanyon v6 documentation
    http://lanyon.readthedocs.org/en/latest/index.html
  - ikiwiki
    http://ikiwiki.info/
    - features
      http://ikiwiki.info/features/
    - blog
      http://ikiwiki.info/examples/blog/
  - What is FlatPress?
   http://flatpress.org/home/
  - Stacey, The Lightweight Content Management System
    http://staceyapp.com/
  - In Use, Stacey
    http://staceyapp.com/in-use/
  - Blogofile
    http://www.blogofile.com/
  - Blogofile
    http://www.blogofile.com/blog/
  - Documentation Blogofile Blogofile v1.0 DEV documentation
    http://www.blogofile.com/documentation/
  - welcome to Mako!
    http://www.makotemplates.org/
  - obensonne / poole overview / Bitbucket
    https://bitbucket.org/obensonne/poole
  - Hyde - A Python Static Website Generator
    http://ringce.com/hyde
  - lakshmivyas/hyde - GitHub
    https://github.com/lakshmivyas/hyde
  - sjl/stevelosh - GitHub
    https://github.com/sjl/stevelosh
  - Blog / Steve Losh
    http://stevelosh.com/blog/
  - Moving from Django to Hyde / Steve Losh
    http://stevelosh.com/blog/2010/01/moving-from-django-to-hyde/
  - Stango - Static web site generator for Python programmers
    http://www.digip.org/stango/
  - Welcome Jinja2 to Jinja2 2.7-dev documentation
    http://jinja.pocoo.org/docs/
  - jinja2 themes - Google Search
    https://www.google.com/search?q=jinja2+themes
  - FlatPress     # Flask-Themes Flask-Themes v0.1 documentation
    http://packages.python.org/Flask-Themes/
  - python hyde themes - Google Search
    https://www.google.com/search?hl=en&q=python+hyde+themes&oq=python+hyde+themes&aq=f&aqi=&aql=&gs_sm=e&gs_upl=34704l35805l0l36032l7l7l0l0l0l1l235l457l2-2l2l0
  - Pelican vs. Hyde- static website generators? : Python
    http://www.reddit.com/r/Python/comments/jaqn2/pelican_vs_hyde_static_website_generators/
  - Kenneth Reitz
    http://kennethreitz.com/
  - poxd/hyde-themes - GitHub
    https://github.com/poxd/hyde-themes
  - Pelican - Pelican v2 documentation
    http://readthedocs.org/docs/pelican/en/2.7.2/
  
* [2011-11-20 Sun] System info on a web page :@server:@homenetwork:@monitoring:
  - phpSysInfo
    http://phpsysinfo.sourceforge.net/
  - System information: vz-web-3.sog (192.168.42.1)
    http://phpsysinfo.sourceforge.net/phpsysinfo/index.php?disp=dynamic

* [2011-11-20 Sun] Managing dotfiles in mercurial             :@dotfiles:@hg:
  - Smarter Code: Versioning Dotfiles in Mercurial
    http://blog.smartercode.net/2010/02/versioning-dotfiles-in-mercurial.html
  - Smarter Code: Managing Divergent Dotfiles with Mercurial Queues
    http://blog.smartercode.net/2010/02/managing-divergent-dotfiles-with.html
  - garybernhardt/dotfiles - GitHub
    https://github.com/garybernhardt/dotfiles
  - Carousel is a <i>lie!</i>: Mercurial for dotfiles
    http://saintaardvarkthecarpeted.com/blog/archive/2009/02/Mercurial_for_dotfiles.html
  - SingleDeveloperMultipleComputers - Mercurial
    http://mercurial.selenic.com/wiki/SingleDeveloperMultipleComputers
  - dotfiles « xyld
    http://xylld.wordpress.com/tag/dotfiles/

* [2011-11-20 Sun] Quicksilver notes                           :@quicksilver:
  - osasubr - a OS X unix command-line utility to pass arguments to an applescript.
    http://www.turbozen.com/mac/osasubr/
  - some Quicksilver goodness | Tamara Temple's Blog - Run [with arguments]
    http://www.tamaratemple.com/2010/08/20/some-quicksilver-goodness/
  - Quicksilver and the Command Line — Apple News, Tips and Reviews
    http://gigaom.com/apple/quicksilver-and-the-command-line/
  - "Open In" or "Run In" - Blacktree: Quicksilver | Google Groups
    http://groups.google.com/group/blacktree-quicksilver/browse_thread/thread/6dd5162d3e3108a7/e0377dca6988620e?lnk=gst&q=arguments&pli=1
  - Console commands using QS - Google Groups
    https://groups.google.com/forum/#!topic/blacktree-quicksilver/_EbnWc4oCM4
  - Executing actions - Quicksilver Wiki
    http://qsapp.com/wiki/Executing_actions
  - How to use Quicksilver's Shelf
    http://lifehacker.com/111278/how-to-use-quicksilvers-shelf
  - Mac snippet solution: Quicksilver Shelf | dotjay.co.uk
    http://dotjay.co.uk/2008/apr/mac-snippet-solution-quicksilver-shelf

* [2011-11-26 Sat]                                             :@python:@mac:
  - Multiple Python Versions on OSX with Virtualenv and Homebrew | insomnihack
    http://www.insomnihack.com/?p=442

* [2011-11-26 Sat]                                           :@linux:@rescue:
  - Rescatux - Super Grub Disk
    Rescatux is a GNU/Linux rescue cd (and eventually also Windows)
    but it is not like other rescue disks. Rescatux comes with
    Rescapp. Rescapp is a nice wizard that will guide you through your
    rescue tasks.
    http://www.supergrubdisk.org/rescatux/

* [2011-11-26 Sat] MacOS Location handling                             :@mac:
  - MarcoPolo - Context-aware computing for Mac OS X
    http://www.symonds.id.au/marcopolo/
  - Location X — The Power of X, to Go!
    http://homepage.mac.com/locationmanager/
  - Mac OS X LocationChanger - TECH.inhelsinki.nl
    http://tech.inhelsinki.nl/locationchanger/

* [2011-11-26 Sat] PaulStretch for MacOS                        :@audio:@mac:
  - Paul's Extreme Sound Stretch
    http://hypermammut.sourceforge.net/paulstretch/
  - PaulStretch 2.1 is Out! New build instructions + new x86 OS X build | Do My Eyes Look Scary?
    http://music.cornwarning.com/2011/02/11/paulstretch-2-1-is-out-new-build-instructions-new-x86-os-x-build/

* [2011-11-26 Sat] Bandwidth monitoring                        :@homenetwork:
  - wrtbwmon - Per-user bandwidth monitoring tool for linux-based routers - Google Project Hosting
    http://code.google.com/p/wrtbwmon/
  - IPTables Bandwidth Monitor - Soft-hausWiki
    http://soft-haus.com/wiki/index.php5?title=IPTables_Bandwidth_Monitor
  - The OpenNMS Project
    http://www.opennms.org/

* [2011-12-08 Thu 14:04] Quicksilver scripting            :@mac:@quicksliver:
  - AppleScript Action template - Quicksilver Wiki
    http://qsapp.com/wiki/AppleScript_Action_template

* [2011-12-08 Thu 14:45] LaTeX Tutorial - YouTube                    :@latex:
  https://www.youtube.com/playlist?list=PLDD406480D35CE390

* [2011-12-08 Thu 15:04] GRC | Ultra High Security Password Generator :@online:@password:
  https://www.grc.com/passwords.htm

* [2011-12-09 Fri 12:51] YouTube video formats                     :@youtube:
  - YouTube - Wikipedia, the free encyclopedia
    http://en.wikipedia.org/wiki/YouTube#Quality_and_codecs

* [2011-12-09 Fri 15:48] Displaying notifications without Growl :@mac:@notifications:
  - cocoaDialog
    http://mstratman.github.com/cocoadialog/

* [2011-12-11 Sun] Using VLC as a media center on AppleTV     :@vlc:@appletv:
  - Mount a Remote Drive via SMBFS - AwkwardTV
    http://wiki.awkwardtv.org/wiki/Mount_a_Remote_Drive_via_SMBFS
  - Mount a Remote Drive via AFP under 1.1 - AwkwardTV
    http://wiki.awkwardtv.org/wiki/Mount_a_Remote_Drive_via_AFP_under_1.1
  - Mount external drive via SMB on AppleTV « Jiradett BLOG
    http://kerdsri.com/2010/01/13/mount-external-drive-via-smb-on-appletv/
  - Applications Menu - AwkwardTV
    http://wiki.awkwardtv.org/wiki/Applications_Menu
  - AwkwardTV Plugin Directory
    http://plugins.awkwardtv.org/det.php?recordID=applauncher
