
* [2010-03-20 Sat] Great EBow video                                 :@guitar:
  - YouTube - Phil Keaggy Ebow
    http://www.youtube.com/watch?v=wwq0i6jP7dQ&feature=related

* [2010-03-20 Sat] The Vibesware Resonator                          :@guitar:
  - How to play with the Vibesware Guitar Resonator | eHow.com
    http://www.ehow.com/how_5108858_play-vibesware-guitar-resonator.html
  - MySpace Video - Vibesware's Video Channel & Video Clips
    http://vids.myspace.com/index.cfm?fuseaction=vids.channel&vanity=vibesware

* TODO [2010-03-20 Sat] RockSchool Keep downloading!            :@todownload:
  :PROPERTIES:
  :ID:       2098A03D-EF5A-4EA0-812A-3ACC1F0EDF57
  :END:
  - YouTube - Rockschool - Series 1 - Ep.3 - Techniques (Part 3 of 3)
    http://www.youtube.com/watch?v=dWkN6dldYt8&feature=related

* [2010-03-20 Sat] Spas et massages
  - Strom spa nordique - Île-des-Soeurs Montréal
    https://www.stromspa.com/secure.asp?Lang=F&Pid=home.asp&STID=&Music=Off
  - Massages
    http://www.skyspa.ca/fr/services-et-tarifs/massotherapie
  - massage sous la pluie - Google Search
    http://www.google.ca/search?client=safari&rls=en&q=massage+sous+la+pluie&ie=UTF-8&oe=UTF-8&redir_esc=&ei=DUulS_ydIcSAlAex3tT1Ag
  - Studio Bliss - Tarifs
    http://www.studiobliss.ca/tarifs.html
  - Laser Spa. Clinique de soins corporels - Épilation Laser - Esthétique
    http://www.laser-spa.com/
  - Vague Tropicale
    http://www.vaguetropicale.ca/index.htm

* [2010-03-20 Sat] Using Handbrake from the command line             :@video:
  - CLIGuide – HandBrake
    http://trac.handbrake.fr/wiki/CLIGuide

* [2010-03-20 Sat] Logging for iPhone development              :@dev:@iPhone:
  - iPhone Dev » How to Implement Grabbing a Sprite with Cocos2d and Box2d
    http://iphonedev.net/2009/08/05/how-to-grab-a-sprite-with-cocos2d-and-box2d/
  - Logs » Chris-Software.com
    http://chris-software.com/index.php/2009/04/29/logs/
  - How to Log to the Console Using NSLog
    http://getsetgames.com/2009/12/22/iphonedev-advent-tip-22-how-to-log-to-the-console-using-nslog/

* [2010-03-20 Sat] Adding trackers to torrents                     :@torrent:
  - PublicBitTorrent - An open tracker project
    http://publicbt.com/tracker_modify.html

* [2010-03-20 Sat] Remote control for transmission   :@torrent:@transmission:
  - man/transmission-remote – Transmission
    http://trac.transmissionbt.com/wiki/man/transmission-remote

* [2010-03-20 Sat] Emacs Mac OS X tweaks                             :@emacs:
  - EmacsWiki: Mac OSTweaks
    http://www.emacswiki.org/emacs/MacOSTweaks#toc22

* [2010-03-23 Tue] Time machine tips                      :@mac:@timemachine:
  - Migrate a Time Machine backup | Business Center | Working Mac | Macworld
    http://www.macworld.com/article/146085/2010/02/migratebackups.html
  - Access alternate Time Machine drives | Mac OS X | Mac OS X Hints | Macworld
    http://www.macworld.com/article/147185/2010/03/alttimemachinedrives.html?lsrc=nl_mwhints_h_crawl

* [2010-03-28 Sun] Relaxation music
  - Alex Theory - Wikipedia, the free encyclopedia
    http://en.wikipedia.org/wiki/Alex_Theory
  - Amazon.com: Alex Theory: Music
    http://www.amazon.com/exec/obidos/search-handle-url?_encoding=UTF8&search-type=ss&index=music&field-artist=Alex%20Theory
  - - Sounds True - Full Spectrum Sound Healing
    http://shop.soundstrue.com/shop.soundstrue.com/SelectProd.do;jsessionid=7CAD05B248360D7F13BE93888D37ACA4?prodId=2214&manufacturer=Sounds%20True&category=Meditation%20&%20Massage%20Music&name=Full%20Spectrum%20Sound%20Healing

* [2010-03-28 Sun] Logging with NSLog              :@objectivec:@development:
  - CocoaDev: NSLog
    http://www.cocoadev.com/index.pl?NSLog
  - CocoaDev: UsingTheDescriptionMethod
    http://www.cocoadev.com/index.pl?UsingTheDescriptionMethod
* [2010-03-28 Sun] iPhone Bonjour                     :@dev:@iphone:@bonjour:
  - iPhone Dev Center: NSNetServices and CFNetServices Programming Guide: Introduction to NSNetServices and CFNetServices Programming Guide
    http://developer.apple.com/iphone/library/documentation/Networking/Conceptual/NSNetServiceProgGuide/Introduction.html
  - Tutorial: Networking and Bonjour on iPhone
    http://www.mobileorchard.com/tutorial-networking-and-bonjour-on-iphone/
  - MDNS and caffeine: How I got Bonjour running on my iPhone
    http://www.tuaw.com/2007/10/22/mdns-and-caffeine-how-i-got-bonjour-running-on-my-iphone/

* [2010-05-20 Thu]                                                 :@cocos2d:
  - iPhone Dev » How to Implement Grabbing a Sprite with Cocos2d and Box2d
    http://iphonedev.net/2009/08/05/how-to-grab-a-sprite-with-cocos2d-and-box2d/

* [2010-05-20 Thu]                                                     :@mac:
  - Better command history browsing in Terminal | Mac OS X | Mac OS X Hints | Macworld
    http://www.macworld.com/article/146015/2010/01/termhistory.html?lsrc=nl_mwhints_h_crawl

* Télécharger des sous-titres francais pour tous les films sans vous compliquer la vie à les resynchroniser. | Sub Synchro
   Source: [2010-10-31 Sun], [[http://www.subsynchro.com/][Télécharger des sous-titres francais pour tous les films sans vous compliquer la vie à les resynchroniser. | Sub Synchro:Safari]]

* [2010-11-05 Fri] Subtitle editing on the Mac                    :@subtitle:
  - les poupees russes subtitles - Google Search
    http://www.google.com/search?q=les+poupees+russes+subtitles
  - Features
    http://www.jubler.org/features/index.php
  - Submerge
    http://www.bitfield.se/submerge/
  - RoadMovie
    http://www.bitfield.se/roadmovie/index.html
  - D-Subtitler ObjectifMac
    http://www.objectifmac.com/dsubtitler.php
  - Browse Sears Files on SourceForge.net
    http://sourceforge.net/projects/sears/files/
* [2010-11-05 Fri] Misc
** CutyCapt - A Qt WebKit Web Page Rendering Capture Utility
   http://cutycapt.sourceforge.net/
** MuseScore | Free music composition & notation software :@linux:@musicmaker:@sequencer:
   http://musescore.org/
** VocProc @ HyperGlitch                      :@musicmaker:@harmonize:@linux:
   http://hyperglitch.com/dev/VocProc
* [2010-11-05 Fri] Monome                                           :@monome:
  - monome - flin is fun
    http://post.monome.org/comments.php?DiscussionID=38
  - app:flin [monome]
    http://docs.monome.org/doku.php?id=app:flin
* [2010-11-05 Fri] How to Create iPad Formatted Videos Using HandBrake or FFMpeg :@ipad:@video:
  http://www.ioncannon.net/meta/1040/how-to-create-ipad-formatted-videos-using-handbrake-or-ffmpeg/
* [2010-11-05 Fri] Normalizing Audio for Multiple AVI files
  - Mini Guide: Normalizing Audio for Multiple AVI files
    http://forum.videohelp.com/threads/255147-Mini-Guide-Normalizing-Audio-for-Multiple-AVI-files
  - Multimedia Dynamite | Linux Journal
    http://www.linuxjournal.com/article/9787
* [2010-11-05 Fri] Watching directories for new files
  - Linux.com - Automatically process new files with fsniper
    http://www.linux.com/archive/articles/150200
  - fsniper documentation
    http://files.minuslab.net/doc.html
  - Pyinotify
    http://trac.dbzteam.org/pyinotify
  - smash at blogs.perl.org: Watching directories for new files
    http://blogs.perl.org/users/smash/2010/07/watching-directories-for-new-files.html
* [2010-11-05 Fri] Twitter stuff                            :@twitter:@emacs:
  - MRR Software
  http://www.mrrsoftware.com/MRRSoftware/Syrinx.html
- EmacsWiki: Twitter
  http://www.emacswiki.org/emacs/Twitter
- EmacsWiki: Tw It
  http://www.emacswiki.org/emacs/TwIt
- EmacsWiki: Twittering Mode
  http://www.emacswiki.org/emacs/TwitteringMode
- EmacsWiki: Identica-mode
  http://www.emacswiki.org/emacs/Identica-mode
- identica emacs - Google Search
  http://www.google.ca/search?client=safari&rls=en&q=identica+emacs&ie=UTF-8&oe=UTF-8&redir_esc=&ei=YeHTTIe9GtCgnQeJ8eSGBg
- Identi.ca mode for Emacs | Nethazard.net
  http://blog.nethazard.net/identica-mode-for-emacs/
- Pwytter: Twitter for Windows, Mac, Linux » Free Twitter client for Windows, Mac & Linux
  http://www.pwytter.com/

* [2010-11-05 Fri] Backuppc stuff                                 :@backuppc:
  - Back Up Linux And Windows Systems With BackupPC - Page 3 | HowtoForge - Linux Howtos and Tutorials
    http://www.howtoforge.com/linux_backuppc_p3

* [2010-11-05 Fri] Check avi file for errors                         :@video:
  - Scanning AVI files for errors - MvixCommunity - Forums & Wiki Dedicated to Mvix Products - Powered by FusionBB
    http://mvixcommunity.com/showtopic.php?tid/1407
  - Program to verify quality of avi files
    http://forum.videohelp.com/threads/243934-Program-to-verify-quality-of-avi-files
  - HOWTO: Check avi file for errors
    http://606u.dir.bg/avicheck/

* [2011-01-03 Mon] Commander-like interface for emacs                :@emacs:
 - EmacsWiki: Sunrise Commander Tips
   http://www.emacswiki.org/emacs/Sunrise_Commander_Tips
 - EmacsWiki: Sunrise Commander
   http://www.emacswiki.org/emacs/Sunrise_Commander

* [2011-01-25 Tue] Yasnippet notes - usage for templates             :@emacs:
  - yasnippet - Project Hosting on Google Code
    http://code.google.com/p/yasnippet/
  - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/search?group=smart-snippet&q=new&qt_g=Search+this+group
  - Issue 124 in yasnippet: yas/new-snippet default template creates spurious 'k-e-y-b-i-n-d-i-n-g' binding - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/browse_thread/thread/7e6d0b3c6448a7f7/400e1c6ceecfd5da?lnk=gst&q=new#400e1c6ceecfd5da
  - Issue 150 in yasnippet: Insertion for new created file fails - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/browse_thread/thread/b3027718dc13bc/57c0d20087253021?lnk=gst&q=new#57c0d20087253021
  - Expand snippet on visiting new file? - smart-snippet and YASnippet | Google Groups
    http://groups.google.com/group/smart-snippet/browse_thread/thread/6299b29069be4cf0/1b06c9499669cd65?lnk=gst&q=new#1b06c9499669cd65

* [2011-04-13 Wed] Recording BBC 4 shows                :@internetradio:@bbc:
  - http://forums.linuxmint.com/viewtopic.php?f=48&t=62200#p357271
    Basically use
    : get_iplayer --modes=flashaacstd --pid  http://www.bbc.co.uk/iplayer/console/...
    where http://www.bbc... is the "listen now" link on the show page.

* [2011-06-07 Tue] Controlling iTunes - Example code           :@dev:@itunes:
  - Open Alexandria » Blog Archive » My Tunes Controller – control iTunes on menu bar
    http://openalexandria.com/2010/10/my-tunes-controller/
  - iTunesController.m - mytunescontroller - MyTunesController - Google Project Hosting
    http://code.google.com/p/mytunescontroller/source/browse/trunk/iTunesController.m

* [2011-06-07 Tue] Some Cocoa source code                       :@dev:@cocoa:
** Cocoa Source Code » Matt Legend Gemmell
   http://mattgemmell.com/source
** Details
  :PROPERTIES:
  :VISIBILITY: folded
  :END:
  - MGSplitViewController
     MGSplitViewController is an enhanced replacement for
     UISplitViewController on the iPad. It allows displaying the
     master view in either orientation, toggling it with animation,
     changing the split from horizontal to vertical, dragging the
     divider, and more.
   - MGImageUtilities
     MGImageUtilities is a collection of useful UIImage categories
     for iPad and iPhone, including image-tinting and image-cropping
     functionality(which explicitly supports multiple orientations,
     and high-resolution Retina Displays).
   - iPad VGA Output
     iPad VGA Output is an open source iPad application showing how
     you can display content on an external display via the iPad VGA
     adapter. It includes a window which goes on the external screen,
     and a window which goes on the iPad, and shows how to detect
     supported external resolutions.
   - iPad Multi Touch
     iPad Multi Touch is an open source iPad application which lets
     you visually track multiple touches, up to the maximum number
     the iPad supports simultaneously (which is eleven, by the
     way). It has some nice Core Animation effects too.
   - Shady
     Shady is an open source Mac OS X application which lets you dim
     the screen beyond its usual limit, ideal for tired (or
     photo-sensitive) eyes.
   - MGScopeBar
     MGScopeBar provides a scope/filter bar much like you’ll find in
     Mail, the Finder (in the Find/Spotlight window), iTunes and
     elsewhere. You can see a demo movie of it here.
   - MGTemplateEngine
     MGTemplateEngine is a native Cocoa system for generating text
     output based on templates and data. It’s a close cousin of
     systems like Smarty, FreeMarker, Django‘s template language, and
     other such systems.
     It’s ideal for Cocoa or iPhone apps needing to generate text
     output using variable-substitution (with looping and/or
     conditional logic), including HTML for export or for apps with
     WebKit-based UIs, invoices or printable templates, mail merge,
     data export or any number of other things. It’s also great (in
     combination with WebKit) for letting your users create
     themes/styles for your application.
   - Skinnable App
     This is a small application demonstrating how to use an embedded
     WebKit WebView to easily “skin” your applications, i.e. style
     your app’s UI using standard CSS files. It shows how to switch
     CSS themes dynamically, how to use Objective-C to add HTML
     content into a WebView, how to retrieve data from the HTML
     document, how to replace existing content, and how to allow HTML
     controls (form elements) to call methods in Cocoa objects.
   - MGTwitterEngine (on github) 
     MGTwitterEngine is a class which lets you integrate Twitter
     support into your Cocoa application, by making use of the
     Twitter API. The entire API is covered, and appropriate data is
     returned as simple Cocoa objects (NSArrays, NSDictionarys,
     NSStrings, NSDates and so on), for very easy integration with
     your code. Creating a TwitterEngine is as easy as instantiating
     it, setting your Twitter username and password, and you’re
     done. See this blog post for more.
   - NSImage+QuickLook
     A category on NSImage allowing you to get an image containing a
     Quick Look preview of the file at a given path. You can specify
     the size, and whether the preview should be rendered as an icon
     (i.e. with a document border, drop-shadow, page-curl and file
     type/extension label superimposed). If Quick Look can’t generate
     a preview for the specified file, you’ll be given the file’s
     Finder icon instead (which is how the Quick Look panel itself
     behaves in Leopard).
   - MAAttachedWindow
     A cool NSWindow subclass which lets you easily attach a view to
     another window, displayed in a floating “speech-bubble”-like
     borderless window. Very handy for contextual help, showing
     options for a certain control, or just to draw attention to
     things. Have a look at this screenshot to see how it works. You
     can also grab a project showing how to use an MAAttachedWindow
     with an NSStatusItem.
   - MATrackingArea
     A simple category on NSView and an accompanying class which
     together allow you to add “tracking areas” to your
     views. Tracking areas are like tracking rectangles but are more
     robust and effective, and can be configured to track the mouse
     either at all times, only when the view’s app is active, only
     when the view’s window is key, or only when the view is First
     Responder. You can also choose whether to use the view’s visible
     rect in preference to the rect you pass in. See the example for
     details.
   - MGViewAnimation
     An NSAnimation subclass which provides more desirable behaviour
     than NSViewAnimation itself in most circumstances; i.e. it
     animates the views’ frames itself in the same thread, leading to
     visually synchronised movement. Try out the included sample app
     to see the difference between regular NSViewAnimations and
     these.
   - NSColor+ContrastingLabelExtensions
     A category on NSColor which returns another NSColor for use when
     drawing label text on top of the receiver. Either white or black
     is returned, depending on which will have most visual contrast
     with the receiver’s color. In the event of the receiver’s
     colorspace not being converted to RGB, black is returned by
     default.
   - ImageCrop
     A category on NSImage allowing you to obtain a resized version
     of the image to fit an arbitrary size, with a choice of cropping
     or scaling methods (crop center, crop start, crop end, or scale
     to fit). Uses high-quality interpolation too.
   - HUDWindow
     An NSPanel subclass which creates a translucent window like
     iPhoto “Adjust” palette. Useful for graphics applications where
     a non-intrusive, high-contrast UI style is needed. Or just to
     look cool.
   - RoundedBox
     An NSBox subclass which draws a pretty rounded-rectangle box
     with a gradient background; take a look at the screenshot to see
     how it looks. Includes lots of configurable options, and it’s
     ready to drop right into your project.
   - TunesWindow
     A project which displays a window in the iTunes 5/6
     (i.e. “polished metal”) style. Like the Unified look, but
     darker. Get the iTunes look in your own apps easily.
   - iCal Calendars
     A simple application which reads iCal’s calendars and returns an
     NSDictionary whose keys are the names of the calendars, and
     whose values are Calendar objects, with fields “title”
     (NSString), “notes” (NSString), “color” (NSColor), and both GUID
     keys used by iCal to keep track of calendars and their source
     data.
   - NSBezierPath+StrokeExtensions
     A simple category on NSBezierPath allowing you stroke inside a
     path, rather than stroking centered on the path.
   - RoundedFloatingPanel
     An NSView subclass and accompanying NSWindow subclass which
     provide the same rounded floating panel overlay which the
     Panther application switcher uses.
   - iTableColumnHeader
     An NSTableHeaderCell subclass providing the metallic column
     headers seen in iApps, including the Calendars list in iCal and
     the Source list in iTunes.
   - iTableView (Source List and Colored Checkboxes)
     A pair of NSTextFieldCell and NSImageCell subclasses (and a
     simple NSTableView subclass) which provide the blue-gradient
     selection highlighting behaviour you see in iCal’s “Calendars”
     list, iTunes’ “Source” list, and the sidebar in the Panther
     Finder. Apple calls this kind of control a Source List.
     Also includes code to draw colored checkboxes as in iCal, using
     any color you want!
   - Address Book Test
     Shows how to make use of the Mac OS X 10.2 Address Book
     API. Includes a live-filtering field which locates Address Book
     entries by forename, surname or company, and demonstrates
     finding the primary email address for a specified person, as
     well as their name and picture.
   - Better TextFinder
     Easily implement Find and Replace in your application. Adapted
     and improved from TextEdit’s implementation. Includes both the
     class and a Nib file containing an appropriate Find panel. Read
     more about the improvements here.
   - SS_PrefsController
     A class which lets you easily create Mail/iTunes/Safari-style
     Preferences windows, with toolbars and multiple panes loaded
     from bundles. Loads of configurable options and flexibility, and
     professional results. Take a look at the class documentation
     (also included in the download).
   - Window Fade-out
     Ever felt the need to have a window fade out of existence,
     instead of just closing? Here’s how.
   - Grab-Scrolling
     Shows how to implement grab-scrolling, like in Preview,
     Photoshop, Acrobat and more. Includes the two requisite
     hand-cursors.
   - Screen Sharing
     Source for two apps, a client and a server, letting you send
     full-screen screenshots of your Mac via Rendezvous. This is a
     modification of Apple’s Picture Sharing code.
