#+TITLE: Notes on Mac OS
#+FILETAGS: @mac

* Typing accented characters with dead keys
  - Easily type accented characters | Mac OS X | Mac OS X Hints | Macworld
  http://www.macworld.com/article/147039/2010/03/accentinput.html?lsrc=nl_mwhints_h_crawl


* Login/Logout scripts
  - Mac OS X: Creating a login hook
    http://support.apple.com/kb/HT2420
  - Bombich.com: Mac OS X Management Custom Shell Script Library
    http://www.bombich.com/mactips/scripts.html
  - Scripting Mac OS X - O'Reilly Media
    http://macdevcenter.com/pub/a/mac/2003/11/07/scripting_osx.html?page=2
  - Bombich.com: Implementing Login and Logout hooks for System Management
    http://www.bombich.com/mactips/loginhooks.html
  - AppleScript: Integrating shell scripts
    http://www.tuaw.com/2008/06/23/applescript-integrating-shell-scripts/
  - Technical Note TN2065: do shell script in AppleScript
    http://developer.apple.com/mac/library/technotes/tn2002/tn2065.html

* Moving Time Machine backup to another drive                  :@timemachine:
  http://www.macosxhints.com/article.php?story=20071128055047339

* Magic mouse middle click                                           :@mouse:
  [2009-12-29 Tue 17:01] I have not verified that this works yet.
  - Apple Magic Mouse: Middle Button click "hack" - gdgt
    http://discuss.gdgt.com/apple/magic-mouse/tips/Middle-Button-click-hack/
  - Better multi monitor & multitouch experience for Mac OS X by Andreas Hegenberg » SecondBar & BetterTouchTool Blog
    http://blog.boastr.net/
  - 3-tap Middleclick on OSX for MacBook & Magic Mouse
    http://clement.beffa.org/labs/projects/middleclick/

* Merging files in folders when copying
  - Mac OS X Manual Page For ditto(1)
    http://developer.apple.com/mac/library/documentation/Darwin/Reference/ManPages/man1/ditto.1.html
  - foldermerge - Project Hosting on Google Code
    http://code.google.com/p/foldermerge/

* Adding file types to Spotlight                                 :@spotlight:
  I ended up using the MyUTIs.bundle.zip approach. After adding the
  UTIs to the plist, renaming the bundle to MyUTIs.app and copying to
  the /Applications directory, it worked. I can now search in org
  files.
  - Adding filetypes to Spotlight
    http://guides.macrumors.com/Adding_filetypes_to_Spotlight
  - 10.4: Use Spotlight to globally index any text file
    http://www.macosxhints.com/article.php?story=2005052015041510

* List open ports on your machine (Mac OS X)
  http://juretta.com/log/2007/08/08/list_open_ports_on_your_machine_mac_os_x_/

* Emacs notes                                                        :@emacs:
  - EmacsWiki: Mac Key Mode
    http://www.emacswiki.org/cgi-bin/emacs-en/MacKeyMode
  - EmacsWiki: Carbon Emacs Package
    http://www.emacswiki.org/emacs-en/CarbonEmacsPackage


* How To Make MacFUSE Follow Symlinks Using SSHFS           :@macfuse:@sshfs:
  http://philnelson.name/2007/01/30/a-quick-note-on-macfuse-sshfs-and-how-to-make-fuse-follow-symlinks/

* Installing meld and making it work
  [[http://connectedflow.com/changes/][Changes]] is very nice, but if something free is needed (like at
  work), then install [[http://meld.sourceforge.net/][meld]] using MacPorts. Unfortunately, this does
  not work out of the box. You need some of the tips described
  [[http://www.ubuntuproductivity.com/journal/macintosh/07/2009/meld-redux/][here]]. The snow leopard steps are in the comments:
  : launchctl load -w /Library/LaunchAgents/org.freedesktop.dbus-session.plist
  : sudo launchctl load -w /Library/LaunchDaemons/org.freedesktop.dbus-system.plist

* Hiding application dock icon                                        :@dock:
  - From the LaunchBar web page:

    In order to get rid of the dock icon, you must modify the file
    named 'Info.plist' inside the Application's package
    (i.e. Sherlock.app/Contents/Info.plist). Open this file in your
    favorite text editor and add the following section (if it's
    already present simply change the 0 to a 1 in the string tag:

    : [KEY]NSUIElement[/KEY]
    : [STRING]1[/STRING]
