* Remember
** org-protocol on mac
  	•	org-protocol.el -- Intercept calls from emacsclient to trigger custom actions (Source)
	•	 
	•	JCardente: Saving weblinks to org-mode from Safari (Source)
	•	 
	•	[Orgmode] [ANN] org-mac-protocol, fully updated for 10.6 and with added (Source)
	•	 
	•	claviclaws's org-mac-protocol at master - GitHub (Source)
	•	 
	•	org-mac-protocol.org at master from claviclaws's org-mac-protocol - GitHub (Source)

   Source: [2010-10-28 Thu], [[message://b4a7c84644eded5e1e95bc12840a2065@imap.bouzou.org][org-protocol on mac:Mail]]

** YouTube - Level - Living Inside Of Me                        :@todownload:
    Source: [2010-10-31 Sun], [[http://www.youtube.com/watch?v%3DQRo_gCzSRUU][YouTube - Level - Living Inside Of Me:Safari]]

** Mocapped live series - Marc Takerkart   
   - New app exports Kinect motion data as BVH files | CG Channel
     http://www.cgchannel.com/2011/01/new-app-exports-kinect-motion-data-as-bvh-files/
   - ACTINIA Software
     http://actinia-software.com/
   - Twinmotion®2 - Real Time Rendering - Twinmotion®2 - Overview
     http://www.twinmotion.com/twinmotion2/overview.html
   - UDK - Unreal Development Kit - Epic Games
     http://udk.com/index.html

** iPad stylus                                                        :@ipad:
  - Amazon.com: BoxWave Capacitive iPad Stylus (Jet Black): Electronics
    http://www.amazon.com/BoxWave-Capacitive-iPad-Stylus-Black/dp/B000BUI76S%3FSubscriptionId%3D14H876SFAKFS0EHBYQ02%26tag%3Dhubp09f0-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB000BUI76S

** Transmission e-mail notification           :@transmission:@email:@torrent:
   - Transmission • View topic - Email notification
     https://forum.transmissionbt.com/viewtopic.php?f=1&t=10617&p=49385&hilit=email+script#p49385

* [2011-12-09 Fri 11:44] Wanderlust new folders           :@wanderlust:@mail:
  Updating the folder list when new folders were created:
  - C-u SPC on the Desktop folder makes the folders appear (on top)
  - m s on the Inbox folder sorts the folders under the Inbox (do not
    do on Desktop if ordering that is important.

* [2011-12-09 Fri] Extract audio from mp4                       :@audio:@mp4:
  - List the tracks:
    : MP4Box -info <file>
  - Extract the audio track:
    : MP4Box -raw <track number> <file>
  - Make the .aac file into a proper music file (.m4a)
    :  MP4Box -add <file.aac> <file.m4a>

* [2012-05-01 Tue] Git - fix initial commit without name and mail      :@git:
  This is mentioned when you do the commit, but on a large one, it quickly
  disappears.
  : git config --global user.name "Your Name"
  : git config --global user.email you@example.com
   Then the identity used for the commit with:
  : git commit --amend --reset-author

* [2012-05-11 Fri 11:53] From the [[http://emacsmovies.org/blog/2012/05/01/the_region/][Emacs Region video]]                 :@emacs:
  - Print the current point position in the minibuffer:
    : C-x =
  - Exchange point and mark
    : C-x C-x
  - When a region is selected, undo only undoes in the region.
  - Same with replacing.



