#+TITLE: Blog entries for Paul's Random Thoughts
#+AUTHOR: Paul Provost
#+EMAIL: paul@bouzou.org
#+DESCRIPTION: 
#+FILETAGS: :blog:@prt:

* [2012-04-19 Thu] Emacs and applescript integration    :@emacs:@applescript:
  You can run applescript code from emacs-lisp using the
  =do-applescript= function. I haven't figured out a good use for it
  yet, but I see possibilities... For now, this defines a bit of
  utilities and inserts the current tab open in Safari in org-mode
  format:

  #+BEGIN_SRC emacs-lisp 
  (defun as-tell-app (app something)
     (let ((res (do-applescript (concat "tell application \""
                                        app "\" to " something))))
       )
     res
     )

  (defun as-safari-doc ()
     (interactive)
     (let ((url (as-tell-app "Safari" 
                                 "get the URL of document 1"))
           (name (as-tell-app "Safari" 
                                 "get the name of window 1")))
       (cons url name)))

  (defun org-insert-safari-link ()
     (interactive)
     (let ((l (as-safari-doc)))
       (insert (org-make-link-string (car l) (cdr l)))
       (message "Link to %s inserted" (car l))))
  #+END_SRC

* [2012-04-03 Tue] Saving a read-only file in vi                  :@unix:@vi:
  From [[http://www.unixmen.com/10-great-and-powerful-linux-commands-you-may-need-to-know/][here]]. This has happened to me more times than I care to
  mention. A trick for saving a file you edited in vim/vi without the
  needed permissions:
  : :w !sudo tee %
  And a version for emacs, using tramp:
  : C-x C-w /sudo::/path/to/file

* [2012-03-27 Tue] Org-mode discoveries                    :@emacs:@org:blog:
  :PROPERTIES:
  :POST_DATE: [2012-03-27 Tue]
  :WEB_CAT: test
  :END:
  Today's discoveries in org-mode's agenda view:
  - Follow mode ('F'): going through the agenda view displays the
    related lines in another window. Using 'o' gets rid of the other
    windows.
  - Entry text mode ('E'): shows some lines (as per the
    org-agenda-add-entry-text-maxlines variable) from the entry inline
    in the agenda buffer.

* [2012-03-26 Mon] Started using deft             :@emacs:@org:@deft:ol:blog:
  :PROPERTIES:
  :POST_DATE: [2012-03-26 Mon]
  :WEB_CAT: test
  :END:
  Started using [[http://jblevins.org/projects/deft/][deft]] for quickly accessing my [[http://orgmode.org/][org]] files. My setup so
  far (adapted from [[http://emacs-fu.blogspot.ca/2011/09/quick-note-taking-with-deft-and-org.html][here]]):
  : (when (require 'deft nil 'noerror) 
  :    (setq
  :       deft-extension "org"
  :       deft-directory "~/Documents/orgfiles/"
  :       deft-text-mode 'org-mode
  :       deft-use-filename-as-title t
  :       )
  :    (global-set-key (kbd "<f9>") 'deft)
  :    )
  This works nicely so far, although F9 on the Mac is already assigned
  to Mission Control (which I rarely use). I'll have to decide which
  is more important, I guess.

