#+TITLE: Text for facebook posts
#+AUTHOR: Paul Provost
#+EMAIL: paul@bouzou.org
#+DESCRIPTION: 
#+FILETAGS: @redbeardcables

* Generic
** English
   Hand built guitar cables, from low-capacitance cable, high quality
   plugs and flexible sleeving. Length and type of plugs according to
   your specifications. Available in red, blue or black (additional
   colors on request). Personalized service and quick
   turnaround. Lifetime warranty! Want one? Contact us! $40 for 10
   feet, $45 for 15 feet, $50 for 20 feet and $55 for 25 feet.

** French
   Cables de guitare assemblés à la main, avec du cable basse
   capacitance, des prises de qualité et une gaine flexible. Vous
   spécifiez la longueur et le type de prise. Disponible en rouge,
   bleu ou noir (d'autres couleurs disponibles sur demande). Service
   personnalisé et rapide. Garantis à vie! Vous en voulez un?
   Contactez nous! $40 pour 10 pieds, $45 pour 15 pieds, $50 pour 20
   pieds et $55 pour 25 pieds.

* Specific
** English
   15' cable in red with a 90 degree plug for Frédéric Mailloux in
   Chambly. Thanks Frédéric!

   Hand-built using low-capacitance cables and high-quality plugs.
   Want one for yourself? Contact us!

** French
   Cable de 15’ en rouge avec une prise à 90 pour Frédéric Mailloux de
   Chambly. Merci Frédéric!

   Assemblé à la main avec du cable basse capacitance et des prises de
   qualité. Vous en voulez un aussi? Contactez nous!

* Combined
** French
   Cables de guitare assemblés à la main, avec du cable basse
   capacitance, des prises de qualité et une gaine flexible. Vous
   spécifiez la longueur et le type de prise. Disponible en rouge,
   bleu ou noir (d'autres couleurs disponibles sur demande). Service
   personnalisé et rapide. Garantis à vie!

   Vous en voulez un? Contactez nous! $40 pour 10 pieds, $45 pour 15
   pieds, $50 pour 20 pieds et $55 pour 25 pieds.

   La photo est un cable de 25’ en bleu avec une prise à 90 pour Mario
   Cormier de Verchères. Merci Mario!
